== Controller Shield Developer Guide

=== Overview
The Controller Shield project creates a Unified-Security Plugin (USecPlugin). The Unified-Security Plugin is a general purpose plugin to provide controller security information to north-bound applications

=== Architecture

Please refer to the https://wiki.opendaylight.org/view/Project_Proposals:Controller_Shield[project proposal wiki page] for more details on architecture.

=== Getting Started

====  Prerequisite
Follow the installation steps of controller in https://wiki.opendaylight.org/view/OpenDaylight_Controller:Pulling,_Hacking,_and_Pushing_the_Code_from_the_CLI 

==== Initiating Controller Shield
Download the following from OpenDaylight Gerrit links

  git clone https://git.opendaylight.org/gerrit/usecplugin.git

or

  git clone ssh://<username>@git.opendaylight.org:29418/usecplugin.git

==== How to Start and Run
The USecPlugin is created using the https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL:Startup_Project_Archetype[MD-SAL archetype]. The folders in the plugin are:

  api/
  artifacts/
  features/
  impl/
  karaf/
  pom.xml

Relevant Files:
* impl/UsecpluginDataBase.java: For creating the database and function definition for populating the database.
* impl/PacketHandler.java: To process the incoming packets and maintain the process for watermark levels.
* impl/UsecpluginProvider.java:To initiate and start the plugin


==== Related Documents
https://wiki.opendaylight.org/view/Controller_Shield:_Beryllium_User_Guide
