[[]]


===Installing from Zip 

Installing from zip is an easy way to get started with OpenDaylight. When installing from zip, the process is as simple as running the completely packaged environment. However unlike official distribution packages OpenDaylight will have to be upgraded manually after each release when installing from zip files.

[[]]


====Prerequisites

In order to be able to install and run the zip file the following prerequisites have to be fulfilled:
* A Java 1.7 compatible JDK or JRE have to be installed (i.e. Oracle JDK 1.7 or OpenJDK 1.7)


* In general, OpenDaylight requires appropriate setting of the JAVA_HOME directory


* More information can be found in the link:$$https://wiki.opendaylight.org/view/Release/Hydrogen/Release_Notes$$[OpenDaylight Hydrogen Release Notes] 

 

 
[WARNING]
====
On some platforms, there are known issues with Oracle Java 1.7.0_21 and 1.7.0_25, but 1.7.0_45 and 1.7.0_51 have worked fine


====


 

[[]]


====Getting the Zip File

You can find the OpenDaylight Hydrogen Release Base Edition zip file on the download page here:

 link:$$http://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/distributions-base/0.1.1/distributions-base-0.1.1-osgipackage.zip$$[http://nexus.opendaylight.org/content/repositories/opendaylight.release/org/opendaylight/integration/distributions-base/0.1.1/distributions-base-0.1.1-osgipackage.zip] 

[[]]


====Understanding Structure

The main content of OpenDaylight Hydrogen is in a directory called _opendaylight_, where you will see the following files:_run.sh_:: launches OpenDaylight on Linux/Mac/Unix systems

_run.bat_:: launches OpenDaylight on Windows systems

_version.properties_:: indicates the build version

_configuration_:: basic initialization files (internal to OpenDaylight)

_lib_:: Java libraries

 

[[]]


====Running OpenDaylight

To launch OpenDaylight follow these easy steps from the root _opendaylight_ directory 

Enter _./run.sh_ or _./run.bat_ with administrator privileges to launch OpenDaylight.
[NOTE]
====
 Starting:: To run OpenDaylight in background enter ./run.sh -start with administrator priviledges.

 Stopping:: To stop OpenDaylight, which is running in background enter ./run.sh -stop with administrator priviledges.

 Status:: In order to see the status of OpenDaylight, enter ./run.sh -status. It will show whether it is running or has been stopped.

 


====


 

Navigate to _http://&lt;ip-address-of-machine-where-you-ran-opendaylight&gt;:8080_ to open the web interface, then use the following credentials to log in:
* User: admin


* Password: admin

 


[NOTE]
====
If you are running OpenDaylight on the same machine as your browser, you can browse to _http://localhost:8080_ or _http://127.0.0.1:8080_ to avoid needing to know the IP address of the machine you are using.


====


You will now have a completely running OpenDaylight installation.

