== TSDR H2 datastore User Guide
This document describes how to use the embedded JPA datastore H2, which is the default datastore (recommended for non-production use case) introduced as part of OpenDaylight Time Series Data Respository(TSDR) project. This store captures the  time series data. This document contains configuration, administration, management, using, and troubleshooting
sections for the feature.

=== Overview
In the Beryllium Release of Time Series Data Repository (TSDR), time series metrics corresponding to the OpenFlow statistics are captured. For users trying out things on their laptop or non-production environment, TSDR functionality can be enabled with default datastore H2 by installing the feature odl-tsdr-all.  

=== TSDR Architecture
The following wiki pages capture the TSDR Model/Architecture 

TBD. 



=== Configuring TSDR with default datastore H2
The H2 based storage files get stored automatically in <karaf install folder>/tsdr/ directory. If you want to change the default storage location, the configuration file to change can be found in <karaf install folder>/etc directory. The filename is org.ops4j.datasource-metric.cfg. Change the last portion of the  url=jdbc:h2:./tsdr/metric  to point to different directory. 
 
=== Administering or Managing TSDR with default datastore H2 
Once the TSDR default datastore feature (odl-tsdr-all) is enabled, the TSDR captured OpenFlow statistics metrics can be accessed from Karaf Console by executing the command 

 tsdr:list <metric-category> <starttimestamp> <endtimestamp>

wherein

* <metric-category> = any one of the following categories FlowGroupStats, FlowMeterStats, FlowStats, FlowTableStats, PortStats, QueueStats
* <starttimestamp> = to filter the list of metrics starting this timestamp 
* <endtimestamp>   = to filter the list of metrics ending this timestamp 

If either of <starttimestamp> or <endtimestamp> is not specified, this command displays the latest 1000 metrics captured. 

With TSDR functionality with default H2 datastore you get an additional command 

 tsdr:purgeAll 

This will  purge the entire collected tsdr metrics record. 
