== TSDR H2 datastore User Guide
This document describes how to use the embedded JPA datastore H2, which is a default datastore (for non-production use case)inside the controller. The default datastore will capture time series data using Time Series Data Repository (TSDR) feature introduced in OpenDaylight Lithium release. This document contains configuration, administration, management, using, and troubleshooting
sections for the feature.

=== Overview
In the first release(Lithium Release) of Time Series Data Repository (TSDR), time series metrics corresponding to the OpenFlow statistics are captured. For developers trying out things on their laptop or non-production environment, TSDR functionality can be enabled with default datastore H2 by installing the feature odl-tsdr-all.  

=== TSDR Architecture
The following wiki(s) captures the TSDR Model/Architecture 

a) https://wiki.opendaylight.org/view/TSDR_Data_Storage_Service_and_Persistence_with_HBase_Plugin
b)https://wiki.opendaylight.org/view/TSDR_Data_Collection_Service

Note in Lithium the DataCollection Service is implemented just for OpenFlow Statistics metrics. 


=== Configuring TSDR
Once the controller is up, TSDR functionality with default datastore (non-production usage) can be enabled by installing the feature "odl-tsdr-all". The H2 based storage files get stored automatically in <karaf install folder>/tsdr/ directory. If you want to change the default storage location, the configuration file to change can be found in <karaf install folder>/etc directory. The filename is org.ops4j.datasource-metric.cfg. Change the last portion of the  url=jdbc:h2:./tsdr/metric  to point to different directory. 
 
=== Administering or Managing <feature>
Once the TSDR default datastore feature is enabled. The TSDR captured OpenFlow statistics metrics can be accessed from Karaf Console by executing the command 

tsdr:list

This command displays the latest 1000 metrics captured. 

With TSDR functionality with default H2 datastore you get additional command 
tsdr:purgeAll using which you can purge the entire collected tsdr metrics record. 

=== Tutorials
The way to enable TSDR functionality with default datastore has been simplified -  wherein once you install the odl-tsdr-all feature, the TSDR functionality will be ready to capture data. By connecting mininet to controller and creating a simple topology and using tsdr:list command in opendaylight console, you can see the collected TSDR metrics data.   




