== Yang Tools 
This chapter contains the following sections:

* <<Installation Overview>>
* <<Adding Plugin Repositories>>
* <<Using Plugin>>

== Installation Overview
Yang tools is a infrastructure project aiming to develop necessary tooling and libraries providing support for NETCONF and YANG for Java (JVM-language based) projects and applications.
Yang tools is used for application such as Model Driven SAL for Controller (which uses YANG as the modeling language) and Netconf or OFConfig plugins. 

=== Installing the Project
To configure your project and generate source code from YANG edit your projects *pom.xml* and add Opendaylight SNAPSHOT repository for snapshot releases (currently only snapshots are available). 

== Adding Plugin Repositories 
==== Plugin Repository
To add following plugin repositories for plugin use: +

[literal]
<pluginRepositories>
    <pluginRepository>	   
       <id>opendaylight-release</id>
       <name>opendaylight-release</name>
       <url>http://nexus.opendaylight.org/content/repositories/opendaylight.release/</url>
        </pluginRepository>
    <pluginRepository>	   
       <id>opendaylight-snapshot</id>
       <name>opendaylight-snapshot</name>
       <url>http://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/</url>
        </pluginRepository>

==== Dependency Repository

To add repositories for required dependencies use: 
[literal]
<repositories>
    <repository>	   
       <id>opendaylight-release</id>
       <name>opendaylight-release</name>
       <url>http://nexus.opendaylight.org/content/repositories/opendaylight.release/</url>
        </repositories>
    <repository>	   
       <id>opendaylight-snapshot</id>
       <name>opendaylight-snapshot</name>
       <url>http://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/</url>
        </repository>
   </repositories>
   
==== Using Plugin

To add yang-maven-plugin to build section of your pom.xml use:
[literal]
<build>
       <plugins>
           <plugin>
               <groupId>org.opendaylight.yangtools</groupId>
               <artifactId>yang-maven-plugin</artifactId>
               <version>0.6.1-SNAPSHOT</version>
               <!-- configuration -->
           </plugin>
       </plugins>
   </build>

    


