== Authentication Service
Authentication uses the credentials presented by a user to identify the user.

NOTE: The Authentication user store provided in the Lithium release does not fully support a clustered node deployment. Specifically, the AAA user store provided by the H2 database needs to be synchronized using out of band means. The AAA Token cache is however cluster-capable.

=== Authentication data model
A user requests authentication within a domain in which the user has defined roles.
The user chooses either of the following ways to request authentication:

* Provides credentials
* Creates a token scoped to a domain. In OpenDaylight, a domain is a grouping of resources (direct or indirect, physical, logical, or virtual) for the purpose of access control.

==== Terms and definitions in the model
Token:: A claim of access to a group of resources on the controller
Domain:: A group or isolation of resources, direct or indirect, physical, logical, or virtual, for the purpose of access control
User:: A person who either owns and has, or has access to a resource or group of resources on the controller
Role:: Opaque representation of a set of permissions, which is merely a unique string, such as "admin" or "guest"
Credential:: Proof of identity such as username and password, OTP, biometrics, or others
Client:: A service or application that requires access to the controller

==== Authentication methods
There are three ways a user may authenticate in OpenDaylight:

* Token-based Authentication
** Direct authentication:  A user presents username/password and a domain the user wishes to access to the controller and obtains a timed (default is 1 hour) scoped access token.  The user then uses this token to access RESTCONF (for example).
** Federated authentication:  A user presents credentials to a third-party Identity Provider (for example, https://fedorahosted.org/sssd/[SSSD]) trusted by the controller.  Upon successful authentication, the controller returns a refresh (unscoped) token with a list of domains that the user has access to.  The user then presents this refresh token scoped to a domain that the user has access to obtain a scoped access token.  The user then uses this access token to access RESTCONF (for example).
* Basic Authentication
:: For backward compatibility with the ODL Hydrogen release, the controller also supports the normal basic authentication with username/password.

===== Example with token authentication using curl (username/password = admin/admin, domain = sdn):

 # Create a token
 curl -ik -d 'grant_type=password&username=admin&password=admin&scope=sdn' http://localhost:8181/oauth2/token

 # Use the token (e.g.,  ed3e5e05-b5e7-3865-9f63-eb8ed5c87fb9) obtained from above (default token validity is 1 hour):
 curl -ik -H 'Authorization:Bearer ed3e5e05-b5e7-3865-9f63-eb8ed5c87fb9' http://localhost:8181/restconf/config/toaster:toaster

Example with basic auth using curl:

 curl -ik -u 'admin:admin' http://localhost:8181/restconf/config/toaster:toaster

=== How the ODL Authentication Service works
In direct authentication, a service relationship exists between the user and the ODL controller. The user and the controller establish trust that allows them to use, and validate credentials.
The user establishes user identity through credentials.

In direct authentication, a user request progresses through the following steps:

. The user requests the controller administrator for a  user account.

:: Associated with the user account are user credentials, initially created by the administrator.  OpenDaylight supports only username/password credentials.   By default, an administrator account is included with ODL out-of-the-box the username and password for which are admin/admin.
In addition to creating the user account, the controller administrator also assigns roles to that account on one or more domains.  By default, there are two user roles:  admin and user.  By default, there is only one domain: sdn.
[start=2]
. The user presents the credentials to the service within a domain in a request for a token.
. The request is then passed on to the controller token endpoint.
. The controller token endpoint sends it to the credential authentication entity which returns a claim for the client.
. The controller token entity transforms the claim (for user, domain, and roles) into a token which it then provides to the user.

In federated authentication, with the absence of a direct trust relationship between the user and the service, a third-party Identity Provider (IdP) is used for authentication. Federated authentication relies on third-party identity providers (IdP) to authenticate the user.  Examples of an external IdPs are Linux SSSD (System Security Services Daemon) and OpenStack Keystone.

The user is authenticated by the trusted IdP and a claim is returned to the ODL authentication services upon successful authentication.  The claim is mapped into ODL users or roles and transformed into a token that is passed onto the user. The request is passed on to the claim authentication broker that transforms it to a claim. The controller turns the claim into a token that is passed on to the user.

In a federated authentication set-up, the OpenDaylight controller extends SSSD claim support. SSSD also provides mapping capabilities. SSSD maps users in an external LDAP server to users defined on the OpenDaylight controller.

=== Configuring Authentication service
Changes to AAA configurations can be made as follows:

For Authentication functionality via one of:

* Web console
* CLI (config command in the Karaf shell)
* Editing the etc/org.opendaylight.aaa.*.cfg files directly

For Token Cache Store settings via one of:

* Editing the 08-authn-config.xml configuration file in etc/opendaylight/karaf
* Using RESTCONF

NOTE: Configurations for AAA are all dynamic and require no restart.

==== Configuring Authentication

To configure features from the Web console:

. Install the Web console:
+
----
feature:install webconsole
----
+
. On the console (http://localhost:8181/system/console) (default Karaf username/password:  karaf/karaf), go to *OSGi* > *Configuration* > *ODL AAA Authentication Configuration*.
.. *Authorized Clients*:  List of software clients that are authorized to access ODL NB APIs.
.. *Enable Authentication*:  Enable or disable authentication. (The default is enable.)

==== Configuring the token store
. Open in a text editor etc/opendaylight/karaf/08-authn-config.xml
:: The fields you can configure are as follows:
.. *timeToLive*: Configure the maximum time, in seconds, that tokens are to be cached. Default is 360000.
.. *timeToWait*: Configure the maximum time, in seconds, for a token cache read operation. Default is 10s.
. Save the file.

NOTE: When Token's are expired, they are lazily removed from the cache.

==== Configuring AAA federation

. On the console, click *ODL AAA Federation Configuration*.
. Use the *Custom HTTP Headers* or *Custom HTTP Attributes* fields to specify the HTTP headers or attributes for federated authentication. Normally, such specification is not required.

NOTE: As the changes you make to the configurations are automatically committed when they are saved, no restart of the Authentication service is required.

=== How federated authentication is set up
Use the following steps to set up federated authentication:

. Set up an Apache front-end and Apache mods for the ODL controller.
. Set up mapping rules (from LDAP users to ODL users).
. Use the ClaimAuthFilter in federation to allow claim transformation.

=== Mapping users to roles and domains
The ODL authentication service transforms assertions from an external federated IdP into Authentication Service data:

. The Apache web server which fronts ODL AAA sends data to SssdAuthFilter.
. SssdAuthFilter constructs a JSON document from the data.
. ODL Authentication Service uses a general purpose transformation mapper to transform the JSON document.

==== Operational model
The mapping model works as follows:

. Assertions from an IdP are stored in an associative array.
. A sequence of rules is applied, and the first rule which returns success is considered a match.
. Upon success, an associative array of mapped values is returned.

** The mapped values are taken from the local variables set during the rule execution.
** The definition of the rules and mapped results are expressed in JSON notation.

==== Operational Model: Sample code
----
mapped = null
foreach rule in rules {
    result = null
    initialize rule.variables with pre-defined values

    foreach block in rule.statement_blocks {
        for statement in block.statements {
            if statement.verb is exit {
                result = exit.status
                break
            }
            elif statement.verb is continue {
                break
            }
        }
        if result {
            break
        }
    if result == null {
        result = success
    }
if result == success {
    mapped = rule.mapping(rule.variables)
}
return mapped
----

==== Mapping Users
A JSON Object acts as a mapping template to produce the final associative array of name/value pairs. The value in a name/value pair can be a constant or a variable.
An example of a mapping template and rule variables in JSON:

.Template
----
{
    "organization": "BigCorp.com",
    "user: "$subject",
    "roles": "$roles"
}
----

.Local variables
----
{
    "subject": "Sally",
    "roles": ["user", "admin"]
}
----

.The final mapped result will be
----
{
    "organization": "BigCorp.com",
    "user: "Sally",
    "roles": ["user", "admin"]
}
----

==== Example: Splitting a fully qualified username into user and realm components
Some IdPs return a fully qualified username (for example, principal or subject). The fully qualified username is the concatenation of the user name, separator, and realm name.
The following example shows the mapped result that returns the user and realm as independent values for the fully qualified username is bob@example.com .

.The mapping in JSON
----
{
    "user": "$username",
    "realm": "$domain"
}
----

.The assertion in JSON
----
{
    "Principal": "bob@example.com"
}
----

.The rule applied
----
[
    [
        ["in", "Principal", "assertion"],
        ["exit", "rule_fails", "if_not_success"],
        ["regexp", "$assertion[Principal]", (?P<username>\\w+)@(?P<domain>.+)"],
        ["set", "$username", "$regexp_map[username]"],
        ["set", "$domain", "$regexp_map[domain]"],
        ["exit, "rule_succeeds", "always"]
    ]
]
----

.The mapped result in JSON
----
{
    "user": "bob",
    "realm": "example.com"
}
----
Also, users may be granted roles based on their membership in certain groups.

The Authentication Service allows white lists for users with specific roles. The white lists ensure that users are unconditionally accepted and authorized with specific roles. Users who must be unconditionally denied access can be placed in a black list.

=== Actors in ODL Authentication Service
*ODL Controller administrator* +
The ODL Controller administrator has the following responsibilities:

* Authors Authentication policies using the REST API
* Provides credentials, usernames and passwords to users who request them

*ODL resource owners* +
Resource owners authenticate (either by means of federation or directly providing their own credentials to the controller) to obtain an access token.  This access token can then be used to access resources on the controller.
An ODL resource owner enjoys the following privileges:

* Creates, refreshes, or deletes access tokens
* Gets access tokens from the Secure Token Service
* Passes secure tokens to resource users

*ODL resource users* +
Resource users do not need to authenticate: they can access resources if they are given an access tokens by the resource owner.  The default timeout for access tokens is 1 hour (This duration is configurable.).
An ODL resource user does the following:

*	Gets access tokens either from a resource owner or the controller administrator
*	Uses tokens at access applications from the north-bound APIs

=== Sub-components of ODL Authentication Service
AuthX authoring service:: Provides AuthN and AuthZ Authoring service
Light-weight Identity Manager (IdmLight):: Stores local user authentication and authorization data, and roles +
Provides an Admin REST API for CRUD users/roles/domains
Pluggable authenticators:: Provides domain-specific authentication mechanisms
Authenticator:: Authenticates users against the authentication policy and establishes claims
Authentication Cache:: Caches all authentication states and tokens
Authentication Filter:: Verifies tokens and extracts claims
Authentication Manager:: Contains the session token and authentication claim store

=== Authorization Service
In progress is the addition of an authorization feature to the authentication service. Authorization will follow successful authentication. Modeled on the Role Based Access Control (RBAC) approach for authentication, the Authorization service will assign roles that define permissions and decide access levels.
Authorization will do the following:

* Verify the operations the user or service is authorized to do
* Enforce policies to grant or deny access to resources
