== Authentication Service
Authentication uses the credentials presented by a user to identify the user.

NOTE: The Authentication user store provided in the Lithium release does not fully support a clustered node deployment. Specifically, the AAA user store provided by the H2 database needs to be synchronised using out of band means. The AAA Token cache is however cluster-capable.

=== Authenthentication data model
A user requests authentication within a domain in which the user has defined roles.
The user chooses either of the following ways to request authentication:

* Provides credentials
* Creates a token scoped to a domain. In OpenDaylight, a domain is a grouping of resources (direct or indirect, physical, logical, or virtual) for the purpose of access control.

==== Terms and definitions in the model
Token:: A claim of access to a group of resources on the controller
Domain:: A group of resources, direct or indirect, physical, logical, or virtual, for the purpose of access control
User:: A person who either owns or has  access to a resource or group of resources on the controller
Role:: Opaque representation of a set of permissions, which is merely a unique string as admin or guest
Credential:: Proof of identity such as username and password, OTP, biometrics, or others
Client:: A service or application that requires access to the controller
Claim:: A data set of validated assertions regarding a user, e.g. the role, domain, name, etc.

==== Authentication methods
There are three ways a user may authenticate in OpenDaylight: +

* Basic HTTP Authentication
** Regular, non-token based, authentication with username/password.
* Token-based Authentication
** Direct authentication:  A user presents username/password and a domain the user wishes to access to the controller and obtains a timed (default is 1 hour) scoped access token.  The user then uses this token to access Restconf (for example).
** Federated authentication:  A user presents credentials to a third-party Identity Provider (for example, SSSD) trusted by the controller.  Upon successful authentication, the controller returns a refresh (unscoped) token with a list of domains that the user has access to.  The user then presents this refresh token scoped to a domain that the user has access to obtain a scoped access token.  The user then uses this access token to access Restconf (for example).


===== Example with token authentication using curl:

(username/password = admin/admin, domain = sdn)

[source,bash] 
----
# Create a token
curl -ik -d 'grant_type=password&username=admin&password=admin&scope=sdn' http://localhost:8181/oauth2/token

# Use the token (e.g.,  ed3e5e05-b5e7-3865-9f63-eb8ed5c87fb9) obtained from above (default token validity is 1 hour):
curl -ik -H 'Authorization:Bearer ed3e5e05-b5e7-3865-9f63-eb8ed5c87fb9' http://localhost:8181/restconf/config/toaster:toaster
----

===== Example with basic HTTP auth using curl: +

[source,bash] 
---- 
curl -ik -u 'admin:admin' http://localhost:8181/restconf/config/toaster:toaster
----

=== How the OpenDaylight Authentication Service works
In direct authentication, a service relationship exists between the user and the OpenDaylight controller. The user and the controller establish trust that allows them to use, and validate credentials.
The user establishes user identity through credentials.

In direct authentication, a user request progresses through the following steps:

. The user requests the controller administrator for a  user account.  
+
:: Associated with the user account are user credentials, initially created by the administrator.  OpenDaylight supports only username/password credentials. By default, an administrator account is present in OpenDaylight out-of-the-box with the default username and password being admin/admin.  
In addition to creating the user account, the controller administrator also assigns roles to that account on one or more domain.  By default, there are two user roles; admin, and user, and there is only one domain; sdn.
+
. The user presents credentials in a token request to the token service within a domain.  
. The request is then passed on to the controller token endpoint.
. The controller token endpoint uses the credential authentication entity which returns a claim for the client. 
. The controller token entity transforms the claim (user, domain, and roles) into a token which it then provides to the user.

In federated authentication, with the absence of a direct trust relationship between the user and the service, a third-party Identity Provider (IdP) is used for authentication. Federated authentication relies on third-party identity providers (IdP) to authenticate the user.

The user is authenticated by the trusted IdP and a claim is returned to the OpenDaylight authentication service.  The claim is transformed into an OpenDaylight claim and successively into a token that is passed on to the user. 

In a federated authentication set-up, the OpenDaylight controller AAA module provides SSSD claim support. SSSD can be used to map users in an external LDAP server to users defined on the OpenDaylight controller.

=== Configuring Authentication service
Changes to AAA configurations can be made as follows:

For Authentication functionality via one of:

* Webconsole
* CLI (config command in the Karaf shell)
* Editing the etc/org.opendaylight.aaa.*.cfg files directly

For Token Cache Store settings via one of:

* Editing the 08-authn-config.xml configuration file in etc/opendaylight/karaf
* Using Restconf

NOTE: Configurations for AAA are all dynamic and require no restart.

==== Configuring Authentication

To configure features from the Web console: +

. Install the Web console:
+
----
feature:install webconsole
----
+
. On the console (http://localhost:8181/system/console) (default Karaf username/password:  karaf/karaf), go to *OSGi* > *Configuration* > *OpenDaylight AAA Authentication Configuration*.
.. *Authorized Clients*:  List of software clients that are authorized to access OpenDaylight northbound APIs.
.. *Enable Authentication*:  Enable or disable authentication. (The default is enable.)

==== Configuring the token store
. Open in a text editor etc/opendaylight/karaf/08-authn-config.xml
:: The fields you can configure are as follows:
.. *timeToLive*: Configure the maximum time, in milliseconds, that tokens are to be cached. Default is 360000.
. Save the file.

NOTE: When token's are expired, they are lazily removed from the cache.

==== Configuring AAA federation

. On the console, click *OpenDaylight AAA Federation Configuration*.
. Use the *Custom HTTP Headers* or *Custom HTTP Attributes* fields to specify the HTTP headers or attributes for federated authentication. Normally, additional specification beyond the default is not 
required.

NOTE: As the changes you make to the configurations are automatically committed when they are saved, no restart of the Authentication service is required.

=== Configuring federated authentication
Use the following steps to set up federated authentication: +

. Set up an Apache front-end and Apache mods for the OpenDaylight controller.
. Set up mapping rules (from LDAP users to OpenDaylight users).
. Use the ClaimAuthFilter in federation to allow claim transformation.

=== Mapping users to roles and domains
The OpenDaylight authentication service transforms assertions from an external federated IdP into Authentication Service data: +

. The Apache web server which fronts OpenDaylight AAA sends data to SssdAuthFilter.
. SssdAuthFilter constructs a JSON document from the data.
. OpenDaylight Authentication Service uses a general purpose transformation mapper to transform the JSON document.

==== Operational model
The mapping model works as follows: +

. Assertions from an IdP are stored in an associative array.
. A sequence of rules is applied, and the first rule which returns success is considered a match.
. Upon success, an associative array of mapped values is returned.

** The mapped values are taken from the local variables set during the rule execution.
** The definition of the rules and mapped results are expressed in JSON notation.

==== Operational Model: Sample code
[source,java]
----
mapped = null
foreach rule in rules {
    result = null
    initialize rule.variables with pre-defined values

    foreach block in rule.statement_blocks {
        for statement in block.statements {
            if statement.verb is exit {
                result = exit.status
                break
            }
            elif statement.verb is continue {
                break
            }
        }
        if result {
            break
        }
    if result == null {
        result = success
    }
if result == success {
    mapped = rule.mapping(rule.variables)
}
return mapped
----

==== Mapping Users
A JSON Object acts as a mapping template to produce the final associative array of name/value pairs. The value in a name/value pair can be a constant or a variable.
An example of a mapping template and rule variables in JSON: +
Template: +
[source,json]
----
{
    "organization": "BigCorp.com",
    "user: "$subject",
    "roles": "$roles"
}
----
Local variables: +
[source,json]
----
{
    "subject": "Sally",
    "roles": ["user", "admin"]
}
----
The final mapped result will be: +
[source,json]
----
{
    "organization": "BigCorp.com",
    "user: "Sally",
    "roles": ["user", "admin"]
}
----

==== Example: Splitting a fully qualified username into user and realm components
Some IdPs return a fully qualified username (for example, principal or subject). The fully qualified username is the concatenation of the user name, separator, and realm name.
The following example shows the mapped result that returns the user and realm as independent values for the fully qualified username is bob@example.com .

The mapping in JSON: +
[source,json]
----
{
    "user": "$username",
    "realm": "$domain"
}
----
The assertion in JSON: +
[source,json]
----
{
    "Principal": "bob@example.com"
}
----
The rule applied: +
[source,json]
----
[
    [
        ["in", "Principal", "assertion"],
        ["exit", "rule_fails", "if_not_success"],
        ["regexp", "$assertion[Principal]", (?P<username>\\w+)@(?P<domain>.+)"],
        ["set", "$username", "$regexp_map[username]"],
        ["set", "$domain", "$regexp_map[domain]"],
        ["exit, "rule_succeeds", "always"]
    ]
]
----
The mapped result in JSON: +
[source,json]
----
{
    "user": "bob",
    "realm": "example.com"
}
----
Also, users may be granted roles based on their membership in certain groups.

The Authentication Service allows white lists for users with specific roles. The white lists ensure that users are unconditionally accepted and authorized with specific roles. Users who must be unconditionally denied access can be placed in a black list.

== Administering OpenDaylight Authentication Services

=== Actors in the System
*OpenDaylight Controller administrator* +
The OpenDaylight Controller administrator has the following responsibilities:

* Author Authentication policies using the IdmLight Service API
* Provides credentials, usernames and passwords to users who request them

*OpenDaylight resource owners* +
Resource owners authenticate (either by means of federation or directly providing their own credentials to the controller) to obtain an access token.  This access token can then be used to access resources on the controller.
An OpenDaylight resource owner enjoys the following privileges:

* Creates, refreshes, or deletes access tokens
* Gets access tokens from the Secure Token Service
* Passes secure tokens to resource users

*OpenDaylight resource users* +
Resource users do not need to authenticate: they can access resources if they are given an access tokens by the resource owner.  The default timeout for access tokens is 1 hour (This duration is configurable.).
An OpenDaylight resource user does the following:

*	Gets access tokens either from a resource owner or the controller administrator
*	Uses tokens at access applications from the north-bound APIs

=== System Components
IdmLight Identity manager:: Stores local user authentication and authorization data, provides an Admin REST API for CRUD operations.
Pluggable authenticators:: Provides domain-specific authentication mechanisms
Authenticator:: Authenticates users against and establishes claims
Authentication Cache:: Caches all authentication states and tokens
Authentication Filter:: Verifies tokens and extracts claims
Authentication Manager:: Contains the session token and authentication claim store


==== IdmLight Identity manager
The Light-weight Identity Manager (IdmLight) Stores local user authentication and authorization data, and roles and provides an Admin REST API for CRUD operations on the users/roles/domains database.
The IdmLight REST API is by default accessed via the {controller baseURI:8181}/auth/v1/ API end point. 
Access to the API is restricted to authenticated clients only, or those possessing a token:

Example: To retrieve the users list.

[source,bash] 
---- 
curl http://admin:admin@localhost:8181/auth/v1/users
----


The following document contains a detailed list of supported CRUD operations allowed by the API:

 https://wiki.opendaylight.org/images/a/ad/AAA_Idmlight_REST_APIs.xlsx


== OpenDaylight Authorization Service
The authorization service currently included in OpenDaylight is of an experimental kind and only briefly documented here. 
Authorization follows successful authentication and is modelled on the Role Based Access Control (RBAC) approach for defining permissions and decide access levels to API resources on the controller.

