== Armoury
This section describes how to use the Armoury feature in OpenDaylight
and contains contains configuration, administration, and management
sections for the feature.

=== Overview
TBD: An overview of the Armoury feature and the use case and the
audience who will use the feature.

=== Armoury Architecture
TBD: Information about Armoury components and how they work together.
Also include information about how the feature integrates with
OpenDaylight.

=== Armoury Catalog
The NF Catalog contains metadata describing a NF.

==== Configuring Armoury Catalog
TBD: Describe how to configure Armoury Catalog after installation.

==== Administering Armoury Catalog
TBD: Include related command reference or operations
for using Armoury Catalog.

=== Armoury Workload Manager
The Workload Manager defines RPCs to manage instances.

=== Configuring Armoury Workload Manager
TBD: Describe how to configure Armoury Workload Manager after installation.

=== Administering Armoury Workload Manager
TBD: Include related command reference or operations
for using Armoury Workload Manager.

=== Tutorials
Below are tutorials for Armoury.

==== Using Armoury Catalog
TBD: State the purpose of tutorial

===== Overview
TBD: An overview of the Armoury Catalog tutorial

===== Prerequisites
TBD: Provide any prerequisite information, assumed knowledge, or environment
required to execute the use case.

===== Target Environment
TBD: Include any topology requirement for the use case.

===== Instructions
TBD: Step by step procedure for using Armoury Catalog.

==== Using Armoury Workload Manager
TBD: State the purpose of tutorial

===== Overview
TBD: An overview of the Armoury Workload Manager tutorial

===== Prerequisites
TBD: Provide any prerequisite information, assumed knowledge, or environment
required to execute the use case.

===== Target Environment
TBD: Include any topology requirement for the use case.

===== Instructions
TBD: Step by step procedure for using Armoury Workload Manager.
