== Kick-starter for OpenDaylight developers

See updated developer getting started information at the https://wiki.opendaylight.org/view/GettingStarted:Developer_Main[Getting Started for Developers Page].

=== Downloading the OpenDaylight software

You can either download the software using CLI or Eclipse. See the relevant sections in the OpenDaylight wiki.


=== OpenDaylight infrastructure


NOTE: This section is for developers who wish to contribute to the OpenDaylight project. For developers who wish to build proprietary applications based on OpenDaylight, see the section on RESTCONF.

The OpenDaylight infrastructure consists of the following components.

* *Source code manager:* http://git-scm.com/[Git]. For more information, see https://wiki.opendaylight.org/view/OpenDaylight_Controller:Gerrit_Setup[Getting started with Git and Gerrit].

* *Code review tool:* https://git.opendaylight.org/gerrit/[Gerrit]. For more information, see https://wiki.opendaylight.org/view/OpenDaylight_Controller:Gerrit_Setup[Getting started with Git and Gerrit].

* *Continuous integration:* https://jenkins.opendaylight.org/[OpenDaylight Jenkins]. For more information, see Getting started with Jenkins.

* *Artefact repository:* https://nexus.opendaylight.org/[OpenDaylight Nexus] For more information, see https://wiki.opendaylight.org/view/Infrastructure:Nexus[Getting started with Nexus].

* *Quality Management:* https://sonar.opendaylight.org/[OpenDaylight Sonar]. 

* *Bug tracking:* http://bugs.opendaylight.org/[OpenDaylight Bugzilla]. 

* *Wiki:* https://wiki.opendaylight.org/[OpenDaylight wiki]. 

=== Development workflow for contributing to the OpenDaylight project

The steps below detail the development workflow for contributing to the OpenDaylight project, including any of its sub projects.


. *Identifying the project:* Identify the project under OpenDaylight for which you are going to contribute code. For the list of available projects, see https://wiki.opendaylight.org/view/Main_Page#Projects[OpenDaylight Projects].

[start=2]
. *Locating the project repository:* Navigate to the selected project page and identify the repository for the project. It maybe listed in the main page or in one of the sub-pages.

[start=4]
. *Pulling the dependent artefacts:* Pull the dependent artefacts. Most Java and OSGI code bases have a large number of dependencies that are managed by maven. During build, the artefacts (usually binary jars) for those dependencies are pulled from a Development Nexus Artefact Repository.

[start=3]
. *Pulling the code:* Pull the code from the repository to your local system. For more information, see the relevant section about the project in this developer's guide.


[start=5]
. *Contributing to the code:* Start working on the code in your local system. If you think your contributions are ready for review by a group of peer collaborators, push the code to the repository.

. *Triggering a Jenkins verification:* Trigger a Jenkins verification in Gerrit. Jenkins runs continuous integration tests.

[start=8]
. *Running CI and verifying the patch:* If the Jenkins tests are successful, the patch is verified in Gerrit.

. *Reviewing the patch:* A committer picks the patch for consideration. The committer may have comments for you to fix in your code. In this case, make the code changes and re-submit the code for review.

. *Submitting the patch:* If there are no more comments, the committer indicates to Gerrit that the patch is approved and verified.

. *Merging the patch:* Gerrit merges the patch into the branch.

. *Triggering a Jenkins verification:* Jenkins is triggered to run the continuous integration tests on the result of the merge.

. *Running a Jenkins merge:* Jenkins kicks off the builds for the new artefacts that need to be in the Development Nexus Artifact Repository.

. *Uploading new artefacts:* If builds (and possible other CI tasks) are successful, Jenkins uploads the new artefacts to the Development Nexus Artefact Repository.


=== OpenDaylight architectural principles


* *Runtime Modularity and Extensibility*: Allow for a modular, extensible controller that supports installation, removal, and updates to service implementations within a running controller. The feature is also known as in service software upgrade (ISSU).

* *Multiprotocol Southbound*: Allow for more than one protocol interface with network elements with diverse capabilities southbound from the controller.


* *Service Abstraction Layer (SAL)*: Where possible, allow for multiple southbound protocols to present the same northbound service interfaces.


* *Open Extensible Northbound API*: Allow for an extensible set of application-facing APIs both across runtimes using REST (level 3 API) and within the same runtime using function calls (level 2 API). The set of accessible functions must be the same.


* *Support for Multitenancy/Slicing*: Allow for the network to be logically (and/or physically) split into different slices or tenants with parts of the controller and modules explicitly dedicated to one or a subset of these slices. This includes allowing the controller to present different views of the controller depending on which slice the caller is from.


* *Consistent Clustering*: Clustering that gives fine-grained redundancy and scale-out while insuring network consistency.


=== Open extensible northbound API

Allow for an extensible set of application-facing APIs both across runtimes using REST (level 3 API) and within the same runtime using function calls (level 2 API). The set of accessible functions must be the same.


Here are the APIs presented by the OpenDaylight projects:

* OpenDaylight Controller:
** AD-SAL https://wiki.opendaylight.org/view/OpenDaylight_Controller:REST_Reference_and_Authentication[REST and Java APIs]


** MD-SAL https://wiki.opendaylight.org/view/OpenDaylight_Controller:RESTCONF_Northbound_APIs[RESTCONF Northbound APIs]


* OpenDaylight Virtual Tenant Network - https://wiki.opendaylight.org/view/OpenDaylight_Virtual_Tenant_Network_(VTN):VTN_Coordinator:RestApi[REST API]


* Open DOVE - https://wiki.opendaylight.org/view/Open_DOVE:API[Northbound API]


* OpenFlow Plugin - N/A


* Affinity Metadata Service - N/A


* YANG Tools - https://wiki.opendaylight.org/view/YANG_Tools:Available_Models[Available YANG models]


* LISP Flow Mapping - https://wiki.opendaylight.org/view/OpenDaylight_Lisp_Flow_Mapping:Java_API[Java API] and https://wiki.opendaylight.org/view/OpenDaylight_Lisp_Flow_Mapping:REST_API[REST API]


* OVSDB - https://wiki.opendaylight.org/view/OVSDB_Integration:REST_API[REST API]


* OpenFlow Protocol Library - https://wiki.opendaylight.org/view/Openflow_Protocol_Library:Main#Public_API[public API]


* BGP-LS/PCEP - N/A


* Defense4All - N/A


* SNMP4SDN - https://wiki.opendaylight.org/view/File:SAL_API_for_SNMP_SouthBound_Plugin.pdf[(proposed) API]

