== Welcome to the OpenDaylight project


The Open Daylight Project is a collaborative open source project under the Linux foundation that aims to accelerate adoption of Software-Defined Networking (SDN) and create a solid foundation for Network Functions Virtualization (NFV) for a more transparent approach that fosters new innovation and reduces risk. Founded by industry leaders and open to all, the OpenDaylight community is developing a common, open SDN framework consisting of code and blueprints.


=== OpenDaylight project scope

The projects chosen by the Technical Steering Committee (TSC) are limited to the following areas:

* The OpenDaylight controller

* Software for forwarding elements

* Southbound plugins to enable the controller to speak to the OpenDaylight supplied and other network elements

* Northbound plugins to expose interfaces to those writing applications to the controller

* Network services and applications intended to run on top of the controller, integration between the controller and other elements

* Support projects such as tools, infrastructure, or testing

* Plugins for inter-controller communication


=== OpenDaylight project goals

* *Code*: To create a robust, extensible, open source code base that covers the major common components required to build an SDN solution.

* *Acceptance*: To get broad industry acceptance amongst vendors and users.

* *Community*: To have a thriving and growing technical community contributing to the code base, using the code in commercial products,  and adding value above, below and around. 

=== Additional information for the OpenDaylight project

* For frequently asked questions about the OpenDaylight project, see the  http://www.opendaylight.org/project/faq[FAQ].


* You can join OpenDaylight as a user, developer, or as a member of the project. See the    http://www.opendaylight.org/resources/getting-started-guide[ Getting Started with OpenDaylight].


* Exhaustive information about OpenDaylight is available in the  https://wiki.opendaylight.org/view/Main_Page[OpenDaylight Wiki].




