*The local.conf is a user-maintained settings file. This allows all custom settings for DevStack to be contained in a single file. This file is processed strictly in sequence.
The following datas are needed to be set in the local.conf file:   
 Set the Host_IP as the detection is unreliable. 
 Set FLOATING_RANGE to a range not used on the local network, i.e. 192.168.1.224/27. This configures IP addresses ending in 225-254 to be used as floating IPs.
 Set FLAT_INTERFACE to the Ethernet interface that connects the host to your local network. This is the interface that should be configured with the static IP address mentioned above.
 If the *_PASSWORD variables are not set, we will be prompted to enter values during the execution of stack.sh.
 Set ADMIN_PASSWORD . This password is used for the admin and demo accounts set up as OpenStack users. We can login to the OpenStack GUI with this credentials only.
 Set the MYSQL_PASSWORD. The default here is a random hex string which is inconvenient if you need to look at the database directly for anything.
 Set the RABBIT_PASSWORD. This is used by messaging services used by both the nodes.
 Set the service password. This is used by the OpenStack services (Nova, Glance, etc) to authenticate with Keystone.

= local.conf (devstack control node) =
local.conf(control)
<source lang="text">
[[local|localrc]]

#IP Details
HOST_IP=<CONTROL_NODE_IP_ADDRESS>
FLAT_INTERFACE=<FLAT_INTERFACE_NAME>
SERVICE_HOST=$HOST_IP

#Instance Details
MULTI_HOST=1
FLOATING_RANGE=192.168.35.0/24

#config Details
RECLONE=no
VERBOSE=True
LOG_COLOR=True
LOGFILE=/opt/stack/logs/stack.sh.log
SCREEN_LOGDIR=/opt/stack/logs
OFFLINE=True

#Passwords
ADMIN_PASSWORD=labstack
MYSQL_PASSWORD=supersecret
RABBIT_PASSWORD=supersecret
SERVICE_PASSWORD=supersecret
SERVICE_TOKEN=supersecrettoken

#Services
disable_service rabbit
enable_service qpid
enable_service quantum
enable_service n-cpu
enable_service n-cond
disable_service n-net
enable_service q-svc
enable_service q-dhcp
enable_service q-meta
enable_service horizon
enable_service quantum
enable_service tempest

ENABLED_SERVICES+=,n-api,n-crt,n-obj,n-cpu,n-cond,n-sch,n-novnc,n-cauth,n-cauth,nova
ENABLED_SERVICES+=,cinder,c-api,c-vol,c-sch,c-bak

#ML2 Details
Q_PLUGIN=ml2
Q_ML2_PLUGIN_MECHANISM_DRIVERS=opendaylight,logger
#Q_ML2_PLUGIN_TYPE_DRIVERS=local
enable_service odl-compute
ODL_MGR_IP=<ODL_IP_ADDRESS>
OVS_PHYSICAL_BRIDGE=br-int
#ENABLE_TENANT_TUNNELS=True

#Details of the Control node for various services
Q_HOST=$SERVICE_HOST
MYSQL_HOST=$SERVICE_HOST
RABBIT_HOST=$SERVICE_HOST
GLANCE_HOSTPORT=$SERVICE_HOST:9292
KEYSTONE_AUTH_HOST=$SERVICE_HOST
KEYSTONE_SERVICE_HOST=$SERVICE_HOST

[[post-config|/etc/nova/nova.conf]]
[DEFAULT]
vif_plugging_timeout = 10
vif_plugging_is_fatal = False

# Branches
KEYSTONE_BRANCH=stable/icehouse
NOVA_BRANCH=stable/icehouse
NEUTRON_BRANCH=stable/icehouse
SWIFT_BRANCH=stable/icehouse
GLANCE_BRANCH=stable/icehouse
CINDER_BRANCH=stable/icehouse
HEAT_BRANCH=stable/icehouse
TROVE_BRANCH=stable/icehouse
HORIZON_BRANCH=stable/icehouse

[[post-config|/etc/neutron/plugins/ml2/ml2_conf.ini]]
[ml2_odl]
url=http://<ODL_IP_ADDRESS>:8080/controller/nb/v2/neutron
username=admin
password=admin
[ovs]
local_ip=192.168.35.1

[[post-config|/etc/neutron/dhcp_agent.ini]]
[DEFAULT]
ovs_use_veth=True
ovs_integration_bridge=br-int

[[post-config|/etc/nova/nova.conf]]
[DEFAULT]
novncproxy_host=0.0.0.0
novncproxy_port=6080
novncproxy_base_url=http://<CONTROL_NODE_IP_ADDRESS>:6080/vnc_auto.html
</source>

= local.conf (devstack compute node) =
local.conf(compute)
<source lang="text">

[[local|localrc]]

#IP Details
HOST_IP=<COMPUTE_NODE_IP>
FLAT_INTERFACE=<FLAT_INTERFACE_NAME>
SERVICE_HOST=<CONTROL_NODE_IP>

#Instance Details
MULTI_HOST=1
FLOATING_RANGE=192.168.35.0/24

#config Details
RECLONE=no
OFFLINE=True
VERBOSE=True
LOG_COLOR=True
LOGFILE=/opt/stack/logs/stack.sh.log

#Passwords
ADMIN_PASSWORD=labstack
MYSQL_PASSWORD=supersecret
RABBIT_PASSWORD=supersecret
SERVICE_PASSWORD=supersecret
SERVICE_TOKEN=supersecrettoken

#Services
ENABLED_SERVICES=n-cpu,n-net,n-api,c-sch,c-api,c-vol,qpid

#ML2 Details
Q_PLUGIN=ml2
Q_ML2_PLUGIN_MECHANISM_DRIVERS=opendaylight
#Q_ML2_PLUGIN_TYPE_DRIVERS=local
enable_service odl-compute
ODL_MGR_IP=<ODL_IP_ADDRESS>
OVS_PHYSICAL_BRIDGE=br-int
#ENABLE_TENANT_TUNNELS=True

#Details of the Control node for various services
Q_HOST=$SERVICE_HOST
MYSQL_HOST=$SERVICE_HOST
RABBIT_HOST=$SERVICE_HOST
GLANCE_HOSTPORT=$SERVICE_HOST:9292
KEYSTONE_AUTH_HOST=$SERVICE_HOST
KEYSTONE_SERVICE_HOST=$SERVICE_HOST

[[post-config|/etc/nova/nova.conf]]
[DEFAULT]
vif_plugging_timeout = 10
vif_plugging_is_fatal = False

# Branches
KEYSTONE_BRANCH=stable/icehouse
NOVA_BRANCH=stable/icehouse
NEUTRON_BRANCH=stable/icehouse
SWIFT_BRANCH=stable/icehouse
GLANCE_BRANCH=stable/icehouse
CINDER_BRANCH=stable/icehouse
HEAT_BRANCH=stable/icehouse
TROVE_BRANCH=stable/icehouse
HORIZON_BRANCH=stable/icehouse
QUANTUM_BRANCH=stable/icehouse

[[post-config|/etc/neutron/plugins/ml2/ml2_conf.ini]]
[ml2_odl]
url=http://<ODL_IP_ADDRESS>:8080/controller/nb/v2/neutron
username=admin
password=admin
[ovs]
local_ip=192.168.35.2

[[post-config|/etc/neutron/dhcp_agent.ini]]
[DEFAULT]
ovs_use_veth=True
ovs_integration_bridge=br-int

[[post-config|/etc/nova/nova.conf]]
[DEFAULT]
vnc_enabled=true
novncproxy_base_url=http://<CONTROL_NODE_IP_ADDRESS>:6080/vnc_auto.html
vncserver_listen=0.0.0.0
vncserver_proxyclient_address=<COMPUTE_NODE_IP_ADDRESS>

</source>
Note:
* We have to comment OFFLINE=TRUE in local.conf files, this will make all the installations to happen automatically.
* RECLONE=yes only when we set up the DevStack environment from scratch.