== PCEP User Guide ==

=== Overview ===

The OpenDaylight Karaf distribution comes preconfigured with baseline PCEP configuration.

- *32-pcep.xml* (basic PCEP configuration, including session parameters)
- *39-pcep-provider.xml* (configuring for PCEP provider)

=== Configuring PCEP ===

The default shipped configuration will start a PCE server on 0.0.0.0:4189. You can change this behavior in *39-pcep-provider.xml*:

[source,xml]
----
<module>
 <type xmlns:prefix="urn:opendaylight:params:xml:ns:yang:controller:pcep:topology:provider">prefix:pcep-topology-provider</type>
 <name>pcep-topology</name>
 <listen-address>192.168.122.55</listen-address>
 <listen-port>4189</listen-port>
...
</module>
----

- *listen-address* - adress on which PCE will be started and listen
- *listen-port* - port on which the address will be started and listen

PCEP default configuration is set to conform stateful PCEP extension:

link:http://tools.ietf.org/html/draft-ietf-pce-stateful-pce-07[draft-ietf-pce-stateful-pce-07] - PCEP Extensions for Stateful PCE and
https://tools.ietf.org/html/draft-ietf-pce-pce-initiated-lsp-00[draft-ietf-pce-pce-initiated-lsp-00] - PCEP Extensions for PCE-initiated LSP Setup in a Stateful PCE Model

==== PCEP Segment Routing ====

Conforms link:http://tools.ietf.org/html/draft-ietf-pce-segment-routing-01[draft-ietf-pce-segment-routing] - PCEP extension for Segment Routing

The default configuration file is located in etc/opendaylight/karaf.

- *33-pcep-segment-routing.xml* - You don't need to edit this file.

