== BGP Monitoring Protocol User Guide ==

=== Overview ===

The OpenDaylight Karaf distribution comes preconfigured with baseline BMP configuration.

- *32-bmp.xml* (initial configuration for BMP messages handler service provider and BMP client/server dispatcher settings)
- *42-bmp-example.xml* (sample initial configuration for the BMP Monitoring Station application)

=== Configuring BMP ===

==== Server Binding ====
The default shipped configuration will start a BMP server on 0.0.0.0:12345.You can change this behavior in *42-bmp-example.xml*:

[source,xml]
----
 <module>
  <type xmlns:prefix="urn:opendaylight:params:xml:ns:yang:controller:bmp:impl">prefix:bmp-monitor-impl</type>
  <name>example-bmp-monitor</name>
  <!--<binding-address>0.0.0.0</binding-address>-->
  <binding-port>12345</binding-port>
  ...
 </module>
----

- *binding-address* - adress on which BMP will be started and listen; to change value, uncomment then line first
- *binding-port* - port on which the address will be started and listen

Multiple instances of the BMP monitoring station (*bmp-monitor-impl* module) can be created. However, each instance must have a unique pair of *binding-address* and *binding-port*

==== Active mode ====
OpenDaylight's BMP might be configured to act as an active party of the connection (ODL BMP < = > Monitored router). To enable this functionality,
configure monitored-router with mandatory parameters:

* address (must be unique for each configured "monitored-router"),
* port,
* active.

See following example from 42-bmp-example.xml: 

[source,xml]
----
 <monitored-router>
  <address>192.0.2.2</address>
  <port>1234</port>
  <active>true</active>
 </monitored-router>
----

=== Configuration through RESTCONF ===

==== Server Binding ====

*URL:*
_http://<controllerIP>:8181/restconf/config/network-topology:network-topology/topology/topology-netconf/node/controller-config/yang-ext:mount/config:modules/config:module/odl-bmp-impl-cfg:bmp-monitor-impl/example-bmp-monitor_

*Content-Type:*
application/xml

*Method:*
PUT

*Body:*
[source,xml]
----
<module xmlns="urn:opendaylight:params:xml:ns:yang:controller:config">
  <name>example-bmp-monitor</name>
  <type xmlns:x="urn:opendaylight:params:xml:ns:yang:controller:bmp:impl">x:bmp-monitor-impl</type>
  <bmp-dispatcher xmlns="urn:opendaylight:params:xml:ns:yang:controller:bmp:impl">
    <type>bmp-dispatcher</type>
    <name>global-bmp-dispatcher</name>
  </bmp-dispatcher>
  <codec-tree-factory xmlns="urn:opendaylight:params:xml:ns:yang:controller:bmp:impl">
    <type xmlns:x="urn:opendaylight:params:xml:ns:yang:controller:md:sal:binding">x:binding-codec-tree-factory</type>
    <name>runtime-mapping-singleton</name>
  </codec-tree-factory>
  <extensions xmlns="urn:opendaylight:params:xml:ns:yang:controller:bmp:impl">
    <type xmlns:x="urn:opendaylight:params:xml:ns:yang:controller:bgp:rib:spi">x:extensions</type>
    <name>global-rib-extensions</name>
  </extensions>
  <binding-address xmlns="urn:opendaylight:params:xml:ns:yang:controller:bmp:impl">0.0.0.0</binding-address>
  <dom-data-provider xmlns="urn:opendaylight:params:xml:ns:yang:controller:bmp:impl">
    <type xmlns:x="urn:opendaylight:params:xml:ns:yang:controller:md:sal:dom">x:dom-async-data-broker</type>
    <name>pingpong-broker</name>
  </dom-data-provider>
  <binding-port xmlns="urn:opendaylight:params:xml:ns:yang:controller:bmp:impl">12345</binding-port>
</module>
----

* change values for *binding-address* and/or *binding-port*

==== Active mode ====

*URL:*
_http://<controllerIP>:8181/restconf/config/network-topology:network-topology/topology/topology-netconf/node/controller-config/yang-ext:mount/config:modules/config:module/odl-bmp-impl-cfg:bmp-monitor-impl/example-bmp-monitor_

*Content-Type:*
application/xml

*Method:*
PUT

*Body:*
[source,xml]
----
<module xmlns="urn:opendaylight:params:xml:ns:yang:controller:config">
  <name>example-bmp-monitor</name>
  <type xmlns:x="urn:opendaylight:params:xml:ns:yang:controller:bmp:impl">x:bmp-monitor-impl</type>
  <bmp-dispatcher xmlns="urn:opendaylight:params:xml:ns:yang:controller:bmp:impl">
    <type>bmp-dispatcher</type>
    <name>global-bmp-dispatcher</name>
  </bmp-dispatcher>
  <codec-tree-factory xmlns="urn:opendaylight:params:xml:ns:yang:controller:bmp:impl">
    <type xmlns:x="urn:opendaylight:params:xml:ns:yang:controller:md:sal:binding">x:binding-codec-tree-factory</type>
    <name>runtime-mapping-singleton</name>
  </codec-tree-factory>
  <extensions xmlns="urn:opendaylight:params:xml:ns:yang:controller:bmp:impl">
    <type xmlns:x="urn:opendaylight:params:xml:ns:yang:controller:bgp:rib:spi">x:extensions</type>
    <name>global-rib-extensions</name>
  </extensions>
  <binding-address xmlns="urn:opendaylight:params:xml:ns:yang:controller:bmp:impl">0.0.0.0</binding-address>
      <dom-data-provider xmlns="urn:opendaylight:params:xml:ns:yang:controller:bmp:impl">
    <type xmlns:x="urn:opendaylight:params:xml:ns:yang:controller:md:sal:dom">x:dom-async-data-broker</type>
    <name>pingpong-broker</name>
  </dom-data-provider>
  <binding-port xmlns="urn:opendaylight:params:xml:ns:yang:controller:bmp:impl">12345</binding-port>
  <monitored-router xmlns="urn:opendaylight:params:xml:ns:yang:controller:bmp:impl">
    <address xmlns="urn:opendaylight:params:xml:ns:yang:controller:bmp:impl">127.0.0.1</address>
    <port xmlns="urn:opendaylight:params:xml:ns:yang:controller:bmp:impl">1234</port>
    <active xmlns="urn:opendaylight:params:xml:ns:yang:controller:bmp:impl">true</active>
  </monitored-router>
</module>
----

* change values for *address* and *port*
