@startuml
object SffGraphEntry_0 {
srcSff=INGRESS
dstSff=sff1
sf=SF1
pathId=3315
serviceIndex=255
}
object SffGraphEntry_1 {
srcSff=sff1
dstSff=sff2
sf=SF2
pathId=3315
serviceIndex=254
}
object SffGraphEntry_2 {
srcSff=sff2
dstSff=EGRESS
sf=
pathId=3315
serviceIndex=253
}

SffGraphEntry_0 -right-> SffGraphEntry_1
SffGraphEntry_1 -right-> SffGraphEntry_2
caption Example graph for a RSP including two different SFs
@enduml

