== VTN Installation Guide

=== Overview

OpenDaylight Virtual Tenant Network (VTN) is an application that provides multi-tenant virtual network on an SDN controller.

Conventionally, huge investment in the network systems and operating expenses are needed because the network is configured as a silo for each department and system. Therefore various network appliances must be installed for each tenant and those boxes cannot be shared with others. It is a heavy work to design, implement and operate the entire complex network.

The uniqueness of VTN is a logical abstraction plane. This enables the complete separation of logical plane from physical plane. Users can design and deploy any desired network without knowing the physical network topology or bandwidth restrictions.

VTN allows the users to define the network with a look and feel of conventional L2/L3 network. Once the network is designed on VTN, it will automatically be mapped into underlying physical network, and then configured on the individual switch leverage SDN control protocol. The definition of logical plane makes it possible not only to hide the complexity of the underlying network but also to better manage network resources. It achieves reducing reconfiguration time of network services and minimizing network configuration errors. OpenDaylight Virtual Tenant Network (VTN) is an application that provides multi-tenant virtual network on an SDN controller. It provides API for creating a common virtual network irrespective of the physical network.

It is implemented as two major components

* <<_vtn_manager,VTN Manager>>
* <<_vtn_coordinator,VTN Coordinator>>

==== VTN Manager
An OpenDaylight Controller Plugin that interacts with other modules to implement the components of the VTN model. It also provides a REST interface to configure VTN components in ODL controller. VTN Manager is implemented as one plugin to the OpenDaylight controller. This provides a REST interface to create/update/delete VTN components. The user command in VTN Coordinator is translated as REST API to VTN Manager by the ODC Driver component. In addition to the above mentioned role, it also provides an implementation to the Openstack L2 Network Functions API.

==== VTN Coordinator

The VTN Coordinator is an external application that provides a REST interface for a user to use the VTN Virtualization. It interacts with VTN Manager plugin to implement the user configuration. It is also capable of multiple controller orchestration. It realizes Virtual Tenant Network (VTN) provisioning in OpenDaylight Controllers (ODC). In the OpenDaylight architecture VTN Coordinator is part of the network application, orchestration and services layer. VTN Coordinator has been implemented as an external application to the OpenDaylight controller. This component is responsible for the VTN virtualization. VTN Coordinator will use the REST interface exposed by the VTN Manger to realize the virtual network using the OpenDaylight controller. It uses OpenDaylight APIs (REST) to construct the virtual network in ODCs. It provides REST APIs for northbound VTN applications and supports virtual networks spanning across multiple ODCs by coordinating across ODCs.

=== Downloading the Karaf Distribution

* Go to the download page of opendaylight.org.
  http://www.opendaylight.org/software/downloads
* Download the "Pre-Built Zip File" or "Pre-Built Tar File" of the latest Lithium.
* Extract files from the downloaded file.
  e.g.,

----
    unzip distribution-karaf-0.2.1-Lithium-SR1.zip
    or
    tar zxvf distribution-karaf-0.2.1-Lithium-SR1.tar.gz
----

=== Preparing for Installation

==== VTN Manager

===== Running the Karaf distribution

. Unzip the zip file
. cd into the directory
. run ./bin/karaf

NOTE: By default the VTN packages will be installed
For example:

[frame="none"]
|===
a|
----
$ ls distribution-karaf-0.2.1-Lithium-SR1.zip 
distribution-karaf-0.2.1-Lithium-SR1.zip
$ unzip distribution-karaf-0.2.1-Lithium-SR1.zip 
Archive:  distribution-karaf-0.2.1-Lithium-SR1.zip
   creating: distribution-karaf-0.2.1-Lithium-SR1/
   creating: distribution-karaf-0.2.1-Lithium-SR1/configuration/
   creating: distribution-karaf-0.2.1-Lithium-SR1/data/
   creating: distribution-karaf-0.2.1-Lithium-SR1/data/tmp/
   creating: distribution-karaf-0.2.1-Lithium-SR1/deploy/
   creating: distribution-karaf-0.2.1-Lithium-SR1/etc/
   creating: distribution-karaf-0.2.1-Lithium-SR1/externalapps/
...
  inflating: distribution-karaf-0.2.1-Lithium-SR1/bin/start.bat  
  inflating: distribution-karaf-0.2.1-Lithium-SR1/bin/status.bat  
  inflating: distribution-karaf-0.2.1-Lithium-SR1/bin/stop.bat
$ cd distribution-karaf-0.2.1-Lithium-SR1
$ ./bin/karaf 

    ________                       ________                .__  .__       .__     __       
    \_____  \ ______   ____   ____ \______ \ _____  ___.__.\|  \| \|__\| ____ \|  \|___/  \|_     
     /   \|   \\____ \_/ __ \ /    \ \|    \|  \\__  \<   \|  \|\|  \| \|  \|/ ___\\|  \|  \   __\    
    /    \|    \  \|_> >  ___/\|   \|  \\|    `   \/ __ \\___  \|\|  \|_\|  / /_/  >   Y  \  \|      
    \_______  /   __/ \___  >___\|  /_______  (____  / ____\|\|____/__\___  /\|___\|  /__\|      
            \/\|__\|        \/     \/        \/     \/\/            /_____/      \/          


Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown OpenDaylight.

opendaylight-user@root>
----
|===

==== VTN Coordinator

* Arrange a physical/virtual server with any one of the supported 64-bit OS environment.
** RHEL 6 / 7 
** CentOS 6 / 7
* Install these packages

  yum install perl-Digest-SHA uuid libxslt libcurl unixODBC json-c

  rpm -ivh http://yum.postgresql.org/9.3/redhat/rhel-6-x86_64/pgdg-redhat93-9.3-1.noarch.rpm

  yum install postgresql93-libs postgresql93 postgresql93-server postgresql93-contrib postgresql93-odbc

=== Installing VTN

==== VTN Manager

Install Feature

  feature:install odl-vtn-manager-all

==== VTN Coordinator

* Enter into the externalapps directory in the top directory of Lithium

  cd distribution-karaf-0.2.1-Lithium-SR1/externalapps
  
* Run the below command to extract VTN Coordinator from the tar.bz2 file in the externalapps directory.

  tar –C/ -jxvf distribution.vtn-coordinator-6.0.0.1-Lithium-SR1-bin.tar.bz2

This will install VTN Coordinator to /usr/local/vtn directory.
The name of the tar.bz2 file name varies depending on the version. Please give the same tar.bz2 file name which is there in your directory.

* Configuring database for VTN Coordinator

  /usr/local/vtn/sbin/db_setup

* To start the Coordinator

  /usr/local/vtn/bin/vtn_start

Using VTN REST API:

Get the version of VTN REST API using the below command, and make sure the setup is working.

  curl --user admin:adminpass -H 'content-type: application/json' -X GET http://<VTN_COORDINATOR_IP_ADDRESS>:8083/vtn-webapi/api_version.json

The response should be like this, but version might differ:

  {"api_version":{"version":"V1.2"}}

=== Verifying your Installation

==== VTN Manager

* In the karaf prompt, type the below command to ensure that vtn packages are installed.

  feature:list i | grep vtn

* Run any VTN Manager REST API

  curl --user "admin":"admin" -H "Accept: application/json" -H \"Content-type: application/json" -X GET \http://localhost:8282/controller/nb/v2/vtn/default/vtns

==== VTN Coordinator

* ps –ef | grep unc will list all the vtn apps
* Run any REST API for VTN Coordinator version

=== Post Installation Configuration

N/A

=== Upgrading From a Previous Release

N/A

=== Uninstalling VTN

==== VTN Manager

  Feature:uninstall odl-vtnmanager-all

==== VTN Coordinator

  /usr/local/vtn/bin/vtn_stop

  Remove the usr/local/vtn folder
