== Getting and Installing OpenDaylight Lithium

=== Downloading the Karaf Distribution

// ==== Getting the Default Distribution

The default distribution can be found on the OpenDaylight Software Download page here: http://www.opendaylight.org/software/downloads

This distribution comes with no features enabled by default, but all
features are able to be installed and run.

CAUTION: Not all features can be run at the same time without negative
         consequences.

// ==== Using the Custom Distribution Download Tool

// Fill in info once this exists.

=== Running the Karaf distribution

. Unzip the zip file
. cd into the directory
. run ./bin/karaf

For example:

[frame="none"]
|===
a|
----
$ ls distribution-karaf-0.3.0-Lithium.zip 
distribution-karaf-0.3.0-Lithium.zip
$ unzip distribution-karaf-0.3.0-Lithium.zip 
Archive:  distribution-karaf-0.3.0-Lithium.zip
   creating: distribution-karaf-0.3.0-Lithium/
   creating: distribution-karaf-0.3.0-Lithium/configuration/
   creating: distribution-karaf-0.3.0-Lithium/data/
   creating: distribution-karaf-0.3.0-Lithium/data/tmp/
   creating: distribution-karaf-0.3.0-Lithium/deploy/
   creating: distribution-karaf-0.3.0-Lithium/etc/
   creating: distribution-karaf-0.3.0-Lithium/externalapps/
...
  inflating: distribution-karaf-0.3.0-Lithium/bin/start.bat  
  inflating: distribution-karaf-0.3.0-Lithium/bin/status.bat  
  inflating: distribution-karaf-0.3.0-Lithium/bin/stop.bat
$ cd distribution-karaf-0.3.0-Lithium
$ ./bin/karaf 

    ________                       ________                .__  .__       .__     __       
    \_____  \ ______   ____   ____ \______ \ _____  ___.__.\|  \| \|__\| ____ \|  \|___/  \|_     
     /   \|   \\____ \_/ __ \ /    \ \|    \|  \\__  \<   \|  \|\|  \| \|  \|/ ___\\|  \|  \   __\    
    /    \|    \  \|_> >  ___/\|   \|  \\|    `   \/ __ \\___  \|\|  \|_\|  / /_/  >   Y  \  \|      
    \_______  /   __/ \___  >___\|  /_______  (____  / ____\|\|____/__\___  /\|___\|  /__\|      
            \/\|__\|        \/     \/        \/     \/\/            /_____/      \/          


Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown OpenDaylight.

opendaylight-user@root>
----
|===

=== Installing Components

The following table describes a list of components in OpenDaylight Lithium and the relevant Karaf feature to install in order to enable that component. To install a feature use the +feature:install+ Karaf command, for example:

-----
feature:install <feature-name>
-----

Multiple features can be installed in the same command:

-----
feature:install <feature1-name> <feature2-name> ... <featureN-name>
-----

.Lithium Components
[options="header",cols="18%,50%,18%,14%"]
|=======================
| Component Name                   | Component Description | Karaf feature name                    | Compatibility
| BGPCEP                           | Enables support for BGP LS PCEP | odl-bgpcep-all                        | all
| Defense4All                      | Enable DDoS detection and protection | n/a | all
| Group Based Policy               | Enable Endpoint Registry and Policy Repository REST APIs and associated functionality for the Group Based Policy Proof of Concept demonstration | odl-groupbasedpolicy-ofoverlay        | self+all
| L2 Switch                        | Provides L2 (Ethernet) forwarding across connected OppenFlow switches and support for host tracking | odl-l2switch-switch-ui                | self+all
| LISP Flow Mapping                | Enable LISP control plane services including the mapping system services REST API and LISP protocol SB plugin | odl-lispflowmapping-all               | all
| MD-SAL Clustering                | Provides support for operating a cluster of OpenDaylight instances | odl-mdsal-clustering                  | special
| Netconf over SSH                 | Provide support to manage Netconf-enabled devices over SSH | odl-netconf-connector-ssh             | all
| OpenFlow Flow Programming        | Enables discovery and control of OpenFlow switches and the topology between them | odl-openflowplugin-flow-services-ui   | all
| OpenFlow Table Type Patterns     | Allows OpenFlow Table Type Patterns to be manually associated with network elements | odl-ttp-all                          |all
| OVS Management                   | Enable OVS management using OVSDB plugin and its associated OVSDB northbound APIs | odl-ovsdb-all                        | all
| OVSDB OpenStack Neutron          | OpenStack Network Virtualization using OpenDaylight's OVSDB support | odl-ovsdb-openstack                   | all
| Packetcable PCMM                 | Enable flow-based dynamic QoS management of CMTS using in the DOCSIS infrastructure | odl-packetcable-all                   | all
| Plugin to OpenContrail           | Provides OpenStack Neutron support via OpenContrail | odl-plugin2oc                         | self+all
| RESTCONF API Support             | Enables REST API access to the MD-SAL including the data store | odl-restconf                          | all
| SDN Interface                    | Provides support for interaction and sharing of state between (non-clustered) OpenDaylight instances | odl-sdninterfaceapp-all               | all
| Secure Networking Bootstrap      | Define a SNBI domain and associated white lists of devices to be accommodated to the domain | odl-snbi-all                          | all
| Service Flow Chaining (SFC)      | Enables support for applying chains of network services to certain traffic | odl-sfc-all                           | all
| SFC over LISP                    | Supports implementing SFC using LISP | odl-sfclisp                           | all
| SFC over L2                      | Supports implementing SFC using Layer 2 forwarding | odl-sfcofl2                           | all
| SFC over VXLAN                   | Supports implementing SFC using VXLAN via OVSDB | odl-ovsdb-ovssfc                      | self+all
| SNMP4SDN                         | Enables monitoring and control of network elements via SNMP | odl-snmp4sdn-all                      | all
| VTN Manager                      | Enables Virtual Tenant Network support including support for OpenStack Neutron | odl-vtn-manager-all                   | self+all
|=======================

In the table a compatibility value of "all" means that it can be run with any other features. A value of "self+all" indicates that the feature can be installed with anything with a value of "all", but not any other features with a value of "self+all".

==== Installing the DLUX Web Interface

The OpenDaylight Web Interface, DLUX, draws information from the OpenFlow Flow Programming and L2 Switch components to display information about the topology of the network, flow statistics, host locations and the like. It will automatically be installed when you install either of these components.

==== Installing support for REST APIs

Most components that offer REST APIs will automatically load the RESTCONF API Support component, but if for whatever reason they seem to be missing, you can activate this support by installing the +odl-restconf+ feature.

==== Installing MD-SAL Clustering

The MD-SAL clustering feature is noted to have "special" compatibility. It *must* be installed first, before any other features. That is, the first command run at the Karaf CLI should be:

----
feature:install odl-mdsal-clustering
----

==== Listing Available and Installed Karaf Features

Note, that this is not an exhaustive list of Karaf features, however you can find a full list by running the following command at the Karaf CLI:

----
feature:list
----

To just list the installed Karaf features, run the command:

----
feature:list -i
----

=== Project-Specific Installation Instructions

The Defense4All and Yang Tools projects provide project-specific installation instructions here. Other projects can either be installed by simply installing the appropriate Karaf feature(s) or, in some cases, further instructions can be found in the User Guide or Developer Guide.

=== Further Information

Further information can be found in the User Guide and Developer Guide, which should be available in the same location as this guide.
