== Cardinal- OpenDayLight Monitoring as a Service
This section describes how to use the cardinal feature in OpenDaylight
and contains contains configuration, administration, and management
sections for the feature.

=== Overview
Cardinal (OpenDaylight Monitoring as a Service) enables SDN Controller - OpenDaylight (ODL) and the underlying software defined network to be remotely monitored by deployed Network Management Systems (NMS) or Analytics suite. In the Boron release, Cardinal will add

.OpenDaylight MIB
.Enable ODL diagnostics/monitoring to be exposed across SNMP (v2c, v3) and REST north-bound
.Extend ODL System health, Karaf parameter and feature info, ODL plugin scalability and network parameters and
.Support autonomous notifications (SNMP Traps)


=== Cardinal Architecture

Cardinal architecture can be found at the below link:

https://wiki.opendaylight.org/images/8/89/Cardinal-ODL_Monitoring_as_a_Service_V2.pdf

=== Configuring Cardinal feature
To start cardinal feature, start karaf and type the following command
	feature:install odl-cardinal
After this cardinal should be up and working with snmpdaemon running on port 161.

=== Tutorials
Below are tutorials for Cardinal.

==== Using Cardinal
These tutorials are intended for any user who wants to monitor three basic component in OpenDaylight

.System Info in which controller is running.
.Karaf Info
.Project Specific Information.


===== Prerequisites
There is no as such specific prerequisite. Cardinal can work without installing any third party software. However If one
wants to see the output of a snmpget/snmpwalk on the cli prompt, than one can install the snmp using the below link:

https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-an-snmp-daemon-and-client-on-ubuntu-14-04

Using the above command line utility one can get the same result as the cardinal apis will give for the snmpget/snmpwalk
request.

===== Target Environment
This tutorial is developed considering the following environment:

controller-Linux(Ubuntu 14.02)


===== Instructions

====== Install Cardinal feature
Open karaf and install the cardinal feature using the following command:
	
----
feature:install odl-cardinal
----

======  Verify that Snmp Daemon is up on port 161 using the following command on the terminal window of Linux machine:

----
netstat -anp | grep "161"
----

If the grep on the snmpd port is successfull than snmp daemon is up and working.

======  Api Reference
Please see Developer guide for usage of Cardinal apis
