== TSDR HBase Data Store Installation Guide
This document is for the user to install the artifacts that are needed
for using HBase Data Store in Time Series Data Repository, which is 
a new feature available in OpenDaylight Lithium release.
=== Overview
Add overview of the feature. Include Architecture diagram and the
positioning of this feature in overall controller architecture.
Highlighting  the feature in a different color within the overall
architecture must help. Include information to describe if the project
is within ODL installation package or to be installed separately.

=== Pre Requisites for Installing <Feature>
* Hardware Requirements
* Software Requirements

=== Preparing for Installation
Include any pre configuration, database, or other software downloads
required to install <feature>.

=== Installing <Feature>
Include if you have separate procedures for Windows and Linux

=== Verifying your Installation
Describe how to verify the installation.

==== Troubleshooting
<optional>
Text goes here.

=== Post Installation Configuration
Post Installation Configuration section must include some basic
(must-do) procedures if any, to get started.

Mandatory instructions to get started with the product.
* Logging in
* Getting Started
* Integration points with controller

=== Upgrading From a Previous Release
Text goes here.

=== Uninstalling <Feature>
Text goes here.
