[[bk-user-guide]]
= OpenDaylight Developer Guide
:docinfo:

///////
[dedication]
Example Dedication
------------------
Optional dedication.

This document is an AsciiDoc book skeleton containing briefly
annotated example elements plus a couple of example index entries and
footnotes.

Books are normally used to generate DocBook markup and the titles of
the preface, appendix, bibliography, glossary and index sections are
significant ('specialsections').


[preface]
Example Preface
---------------
Optional preface.

Preface Sub-section
~~~~~~~~~~~~~~~~~~~
Preface sub-section body.
///////

//////////////////////////
Please note and leave the blank line between include statements here.

It is a defensive measure to prevent individual projects' .adoc files
from eating the next section if they forget to leave a blank line at
the end of their file.
//////////////////////////
= Overview

include::section_Git_and_Gerrit_Setup.adoc[]

include::section_Hacking_from_CLI.adoc[]

= Project-Specific Development Guides

include::aaa.adoc[]

include::bgpcep.adoc[]

include::controller.adoc[]

include::defense4all.adoc[]

include::dlux.adoc[]

include::groupbasedpolicy.adoc[]

include::l2switch.adoc[]

include::lispflow.adoc[]

include::neutron/neutron.adoc[]

include::odlsdni.adoc[]

include::openflowlibrary.adoc[]

include::openflowplugin.adoc[]

include::ovsdb.adoc[]

include::pcmm.adoc[]

include::plugin2oc.adoc[]

include::sfc.adoc[]

include::snbi.adoc[]

include::snmp4sdn.adoc[]

include::tcpmd5.adoc[]

include::ttp.adoc[]

include::VTN_developer_guide.adoc[]

include::yangtools.adoc[]

:numbered!:

///////
[appendix]
Example Appendix
----------------
One or more optional appendixes go here at section level 1.

Appendix Sub-section
~~~~~~~~~~~~~~~~~~~
Sub-section body.


[glossary]
Example Glossary
----------------
Glossaries are optional. Glossaries entries are an example of a style
of AsciiDoc labeled lists.

[glossary]
A glossary term::
  The corresponding (indented) definition.

A second glossary term::
  The corresponding (indented) definition.


[colophon]
Example Colophon
----------------
Text at the end of a book describing facts about its production.


[index]
Example Index
-------------
///////

////////////////////////////////////////////////////////////////
The index is normally left completely empty, it's contents being
generated automatically by the DocBook toolchain.
////////////////////////////////////////////////////////////////
