[[bk-user-guide]]
= OpenDaylight Developer Guide
:docinfo:

///////
[dedication]
Example Dedication
------------------
Optional dedication.

This document is an AsciiDoc book skeleton containing briefly
annotated example elements plus a couple of example index entries and
footnotes.

Books are normally used to generate DocBook markup and the titles of
the preface, appendix, bibliography, glossary and index sections are
significant ('specialsections').


[preface]
Example Preface
---------------
Optional preface.

Preface Sub-section
~~~~~~~~~~~~~~~~~~~
Preface sub-section body.
///////

//////////////////////////
Please note and leave the blank line between include statements here.

It is a defensive measure to prevent individual projects' .adoc files
from eating the next section if they forget to leave a blank line at
the end of their file.
//////////////////////////
= Overview

include::section_Git_and_Gerrit_Setup.adoc[]

include::section_Hacking_from_CLI.adoc[]

= Project-Specific Development Guides

include::controller/controller.adoc[Controller]

include::bgpcep/odl-bgpcep-bgp-all-dev.adoc[BGP]

include::bgpcep/odl-bgpcep-pcep-all-dev.adoc[PCEP]

include::dlux/dlux-core-dev.adoc[]

include::iotdm/iotdm-dev.adoc[]

include::lacp/lacp-dev.adoc[]

include::l2switch/l2switch-dev.adoc[]

include::nic/nic-model-dev.adoc[]

include::neutron/neutron.adoc[]

include::openflowjava/odl-openflowjava-protocol-dev.adoc[]

include::ovsdb/ovsdb-developer.adoc[]

include::reservation/reservation-dev.adoc[]

include::sfc/sfc.adoc[]

include::sdninterfaceapp/odl-sdninterfaceapp-all-dev.adoc[]

include::tcpmd5/odl-tcpmd5-all-dev.adoc[TCP-MD5]

include::topoprocessing/odl-topoprocessing-framework-dev.adoc[]

include::ttp/ttp-model-dev.adoc[]

include::ttp/ttp-cli-tools-dev.adoc[]

include::didm/didm-dev.adoc[]

:numbered!:

///////
[appendix]
Example Appendix
----------------
One or more optional appendixes go here at section level 1.

Appendix Sub-section
~~~~~~~~~~~~~~~~~~~
Sub-section body.


[glossary]
Example Glossary
----------------
Glossaries are optional. Glossaries entries are an example of a style
of AsciiDoc labeled lists.

[glossary]
A glossary term::
  The corresponding (indented) definition.

A second glossary term::
  The corresponding (indented) definition.


[colophon]
Example Colophon
----------------
Text at the end of a book describing facts about its production.


[index]
Example Index
-------------
///////

////////////////////////////////////////////////////////////////
The index is normally left completely empty, it's contents being
generated automatically by the DocBook toolchain.
////////////////////////////////////////////////////////////////
