== Link Aggregation Control Protocol User Guide

=== Overview
This section contains information about how to use the LACP plugin project with OpenDaylight, including configurations.

=== Link Aggregation Control Protocol Architecture
The LACP Project within OpenDaylight implements Link Aggregation Control Protocol (LACP) as an MD-SAL service module and will be used to auto-discover and aggregate multiple links between an OpenDaylight controlled network and LACP-enabled endpoints or switches. The result is the creation of a logical channel, which represents the aggregation of the links. Link aggregation provides link resiliency and bandwidth aggregation. This implementation adheres to IEEE Ethernet specification link:http://www.ieee802.org/3/hssg/public/apr07/frazier_01_0407.pdf[802.3ad].

=== Configuring Link Aggregation Control Protocol

This feature can be enabled in the Karaf console of the OpenDaylight Karaf distribution by issuing the following command:

 feature:install odl-lacp-plugin

[NOTE]
====
1. Ensure that legacy (non-OpenFlow) switches are configured with LACP mode active with a long timeout to allow for the LACP plugin in OpenDaylight to respond to its messages. 
2. Flows that want to take advantage of LACP-configured Link Aggregation Groups (LAGs) must explicitly use a OpenFlow group table entry created by the LACP plugin. The plugin only creates group table entries, it does not program any flows on its own.
====

=== Administering or Managing Link Aggregation Control Protocol
LACP-discovered network inventory and network statistics can be viewed using the following REST APIs.

1. List of aggregators available for a node:
+
 http://<ControllerIP>:8181/restconf/operational/opendaylight-inventory:nodes/node/<node-id>
+
Aggregator information will appear within the +<lacp-aggregators>+ XML tag.

2. To view only the information of an aggregator:
+
 http://<ControllerIP>:8181/restconf/operational/opendaylight-inventory:nodes/node/<node-id>/lacp-aggregators/<agg-id>
+
The group ID associated with the aggregator can be found inside the +<lag-groupid>+ XML tag.
+
The group table entry information for the +<lag-groupid>+ added for the aggregator is also available in the +opendaylight-inventory+ node database.

3. To view physical port information.
+
 http://<ControllerIP>:8181/restconf/operational/opendaylight-inventory:nodes/node/<node-id>/node-connector/<node-connector-id>
+
Ports that are associated with an aggregator will have the tag +<lacp-agg-ref>+ updated with valid aggregator information.

=== Tutorials
To be updated later

==== <Tutorial Name>
To be updated later

===== Overview
An overview of the use case.

===== Prerequisites
Legacy (non-openflow) switches should be enabled with LACP mode and configured with a long timeout.

===== Target Environment
To be updated later

===== Instructions
To be updated 
