== Network Intent Composition (NIC) User Guide

=== Overview
Network Intent Composition (NIC) is an interface that allows clients to
express a desired state in an implementation-neutral form that will be
enforced via modification of available resources under the control of
the OpenDaylight system.

This description is purposely abstract as an intent interface might
encompass network services, virtual devices, storage, etc.

The intent interface is meant to be a controller-agnostic interface
so that "intents" are portable across implementations, such as OpenDaylight
and ONOS. Thus an intent specification should not contain implementation
or technology specifics.

The intent specification will be implemented by decomposing the intent
and augmenting it with implementation specifics that are driven by
local implementation rules, policies, and/or settings.

=== Network Intent Composition (NIC) Architecture
The core of the NIC architecture is the intent model, which specifies
the details of the desired state. It is the responsibility of the NIC
implementation transforms this desired state to the resources under
the control of OpenDaylight. The component that transforms the
intent to the implementation is typically referred to as a renderer.

For the Boron release, multiple, simultaneous renderers will not be supported.
Instead either the VTN or GBP renderer feature can be installed, but
not both.

For the Boron release, the only actions supported are "ALLOW" and
"BLOCK". The "ALLOW" action indicates that traffic can flow between
the source and destination end points, while "BLOCK" prevents that
flow; although it is possible that an given implementation may augment
the available actions with additional actions.

Besides transforming a desired state to an actual state it is the
responsibility of a renderer to update the operational state tree for
the NIC data model in OpenDaylight to reflect the intent which the
renderer implemented.

=== Configuring Network Intent Composition (NIC)
For the Boron release there is no default implementation of a renderer,
thus without an additional module installed the NIC will not function.

=== Administering or Managing Network Intent Composition (NIC)
There is no additional administration of management capabilities
related to the Network Intent Composition features.

=== Interactions
A user can interact with the Network Intent Composition (NIC) either
through the RESTful interface using standard RESTCONF operations and
syntax or via the Karaf console CLI.

==== REST

===== Configuration
The Network Intent Composition (NIC) feature supports the following REST
operations against the configuration data store.

* POST - creates a new instance of an intent in the configuration store,
which will trigger the realization of that intent. An ID _must_ be specified
as part of this request as an attribute of the intent.

* GET - fetches a list of all configured intents or a specific configured
intent.

* DELETE - removes a configured intent from the configuration store, which
triggers the removal of the intent from the network.

===== Operational
The Network Intent Composition (NIC) feature supports the following REST
operations against the operational data store.

* GET - fetches a list of all operational intents or a specific operational
intent.

==== Karaf Console CLI
This feature provides karaf console CLI command to manipulate the intent
data model. The CLI essentailly invokes the equivalent data operations.

===== intent:add

Creates a new intent in the configuration data tree

----
DESCRIPTION
        intent:add

    Adds an intent to the controller.

Examples: --actions [ALLOW] --from <subject> --to <subject>
          --actions [BLOCK] --from <subject>

SYNTAX
        intent:add [options]

OPTIONS
        -a, --actions
                Action to be performed.
                -a / --actions BLOCK/ALLOW
                (defaults to [BLOCK])
        --help
                Display this help message
        -t, --to
                Second Subject.
                -t / --to <subject>
                (defaults to any)
        -f, --from
                First subject.
                -f / --from <subject>
                (defaults to any)
----

===== intent:delete
Removes an existing intent from the system

----
DESCRIPTION
        intent:remove

    Removes an intent from the controller.

SYNTAX
        intent:remove id

ARGUMENTS
        id  Intent Id
----

===== intent:list
Lists all the intents in the system

----
DESCRIPTION
        intent:list

    Lists all intents in the controller.

SYNTAX
        intent:list [options]

OPTIONS
        -c, --config
                List Configuration Data (optional).
                -c / --config <ENTER>
        --help
                Display this help message
----

===== intent:show
Displayes the details of a single intent

----
DESCRIPTION
        intent:show

    Shows detailed information about an intent.

SYNTAX
        intent:show id

ARGUMENTS
        id  Intent Id
----


===== intent:map

List/Add/Delete current state from/to the mapping service.

----
DESCRIPTION
        intent:map

        List/Add/Delete current state from/to the mapping service.

SYNTAX
        intent:map [options]

         Examples: --list, -l [ENTER], to retrieve all keys.
                   --add-key <key> [ENTER], to add a new key with empty contents.
                   --del-key <key> [ENTER], to remove a key with it's values."
                   --add-key <key> --value [<value 1>, <value 2>, ...] [ENTER],
                     to add a new key with some values (json format).
OPTIONS
       --help
           Display this help message
       -l, --list
           List values associated with a particular key.
       -l / --filter <regular expression> [ENTER]
       --add-key
           Adds a new key to the mapping service.
       --add-key <key name> [ENTER]
       --value
           Specifies which value should be added/delete from the mapping service.
       --value "key=>value"... --value "key=>value" [ENTER]
           (defaults to [])
       --del-key
           Deletes a key from the mapping service.
       --del-key <key name> [ENTER]
----

=== NIC Usage Examples

In addition to the one example here, please see the wiki for more use cases:
https://wiki.opendaylight.org/view/Network_Intent_Composition:Use_Cases

include::NIC_How_To_configure_VTN_Renderer.adoc[How to configure VTN Renderer]
