== Network Intent Composition (NIC) User Guide

=== Overview
Network Intent Composition (NIC) is a interface that allows clients to
express a desired state in an implementation neutral form that will be
enforced via modification of available resources under the control of
the OpenDaylight (ODL) system.

This description is purposely abstract as an intent interface might
encompass network services, virtual devices, storage, etc.

The intent interface is meant to be an implementation agnostic interface
so that "intents" are portable across implementations, such as ODL
and ONOS. Thus an intent specification shall not contain implementation
or technologies specifics.

The intent specification will be implemented by decomposing the intent
and augmenting it with implementation specifics that are driven by
local implementation rules/policies/settings.

=== Network Intent Composition (NIC) Architecture
The core of the NIC architecture is the intent model, which specifies
the details of the desired state. It is the responsibility of the NIC
implementation transforms this desired state to the resources under
the control of OpenDaylight (ODL). The component that transforms the
intent to the implementation is typically refered to as a renderer.

For the Lithium release, ODL will support a single renderer per an
intent tuple, where a tuple is defined as a source end point type,
destination end point type, and set of actions. And end point type
in this context is an end point specification the resolves to a
specific network connection point such as MAC or IP address.

For the Litium release, the only actions supported are "ALLOW" and
"BLOCK". The "ALLOW" action indicates that traffic can flow between
the source and destination end points, where "BLOCK" prevents that
flow; although it is possible that an given implementation may augment
the available actions with additional actions.

Besides transforming a desired state to an actual state it is the
responsibility of a renderer to update the operational state in
ODL to reflect the intent which the renderer implemented.

=== Configuring Network Intent Composition (NIC)
For the Litium release there is no default implementation of a renderer,
thus without an additional module installed the NIC will not function.

=== Administering or Managing Network Intent Composition (NIC)
There is no additional administration of management capabilities
related to the Network Intent Composition features.

=== Interactions
A user can interact with the Network Intent Composition (NIC) either
through the RESTful interface using standard RESTCONF operations and
syntax or via the Karaf console CLI.

==== REST

===== Configuration
The Network Intent Composition (NIC) feature supports the following REST
operations against the configuration data store.

* POST - creates a new instance of an intent in the configuration store,
which will trigger the realization of that intent. An ID _must_ be specified
as part of this request as an attribute of the intent.

* PUT - creates or updates an instance of an intent in the configuration store,
which will trigger the realization of that intent.

* GET - fetches a list of all configured intents or a specific configured
intent.

* DETELE - removes a configured intent from the configuration store, which
triggers the removal of the intent from the network.

===== Operational
The Network Intent Composition (NIC) feature supports the following REST
operations against the operational data store.

* GET - fetches a list of all operational intents or a specific operational
intent.

==== Karaf Console CLI
Using the Karaf console CLI intents can be manipulated. The following Karaf
console CLI commands are available.

* intent:add <intent-data> - creates a new intent

* intent:update <id> <intent-data> - updates an existing intent

* intent:list - lists all intents in the system

* intent:show <id> - display the details of a specific intent

* intent:delete <id> - removes an intent from the system

