== DIDM Developer Guide

=== Overview
The Device Identification and Driver Management (DIDM) project addresses the
need to provide device-specific functionality. Device-specific functionality is
code that performs a feature, and the code is knowledgeable of the capability
and limitations of the device. For example, configuring VLANs and adjusting
FlowMods are features, and there may be different implementations for different
device types. Device-specific functionality is implemented as Device Drivers.
Device Drivers need to be associated with the devices they can be used with. To
determine this association requires the ability to identify the device type.


=== DIDM Architecture
The DIDM project creates the infrastructure to support the following functions:

 * *Discovery* - Determination that a device exists in the controller
   management domain and connectivity to the device can be established. For
   devices that support the OpenFlow protocol, the existing discovery
   mechanism in OpenDaylight suffices. Devices that do not support OpenFlow
   will be discovered through manual means such as the operator entering
   device information via GUI or REST API.
 * *Identification* – Determination of the device type.
 * *Driver Registration* – Registration of Device Drivers as routed RPCs.
 * *Synchronization* – Collection of device information, device configuration,
   and link (connection) information.
 * *Data Models for Common Features* – Data models will be defined to
   perform common features such as VLAN configuration. For example,
   applications can configure a VLAN by writing the VLAN data to the data store
   as specified by the common data model.
 * *RPCs for Common Features* – Configuring VLANs and adjusting
   FlowMods are example of features. RPCs will be defined that specify the
   APIs for these features. Drivers implement features for specific devices and
   support the APIs defined by the RPCs. There may be different Driver
   implementations for different device types.


=== Identification process flow
This section talks about the identification process for an OpenFlow device.

.Manual Discovery
[NOTE]
Manual discovery APIs will be made available in the next release for non-openflow devices

. Device connects to the controller through Openflowplugin discovery
. Inventory node gets created in config and operational datastore
. Identification Manager gets notified when the node is created in the operational tree
. It, then, will try to connect to the device to fetch information in sequence via:
... OpenFlow
... SNMP
... If both fail then it will declair the type "unknown"
. Augment the operational tree with the device type
. Device driver is notified when a specific device type augmentation is applied
. Driver augments the sync data collected 
. Device driver registers routed RPCs or data change notifications


=== Key APIs and Interfaces
* User facing APIs become available from individual drivers such as openflow-feature under didm-drivers-api
* More device specific APIs come from device drivers such as Mininet driver mininet-impl, and HP 3800 driver hp-3800-impl


=== API Reference Documentation
Go to http://${CONTROLLER-IP}:8181/apidoc/explorer/index.html,and look under DIDM section
to see all the available REST calls and tables
