== DIDM Developer Guide

=== Overview
The Device Identification and Driver Management (DIDM) project addresses the
need to provide device-specific functionality. Device-specific functionality is
code that performs a feature, and the code is knowledgeable of the capability
and limitations of the device. For example, configuring VLANs and adjusting
FlowMods are features, and there may be different implementations for different
device types. Device-specific functionality is implemented as Device Drivers.
Device Drivers need to be associated with the devices they can be used with. To
determine this association requires the ability to identify the device type.

=== DIDM Architecture
The DIDM project creates the infrastructure to support the following functions:

 * *Discovery* - Determination that a device exists in the controller
   management domain and connectivity to the device can be established. For
   devices that support the OpenFlow protocol, the existing discovery
   mechanism in OpenDaylight suffices. Devices that do not support OpenFlow
   will be discovered through manual means such as the operator entering
   device information via GUI or REST API.
 * *Identification* – Determination of the device type.
 * *Driver Registration* – Registration of Device Drivers as routed RPCs.
 * *Synchronization* – Collection of device information, device configuration,
   and link (connection) information.
 * *Data Models for Common Features* – Data models will be defined to
   perform common features such as VLAN configuration. For example,
   applications can configure a VLAN by writing the VLAN data to the data store
   as specified by the common data model.
 * *RPCs for Common Features* – Configuring VLANs and adjusting
   FlowMods are example of features. RPCs will be defined that specify the
   APIs for these features. Drivers implement features for specific devices and
   support the APIs defined by the RPCs. There may be different Driver
   implementations for different device types.


=== Key APIs and Interfaces
* User facing APIs become available from individual drivers such as openflow-feature under odl-didm-drivers
* More device specific APIs come from device drivers such as Mininet driver odl-didm-ovs-all, and HP 3800 driver odl-didm-hp-all
=== Run REST adjust-flow command to adjust flows and push to the device

Flow mod driver for HP 3800 device is added in Beryllium release
This driver adjusts the flows and push the same to the device. 
This API takes the flow to be adjusted as input and displays the adjusted flow as output in the rest output container.
Here is the REST API to adjust and push flows to HP 3800 device:
----
http://<CONTROLLER-IP:8181>/restconf/operations/openflow-feature:adjust-flow
----

=== API Reference Documentation
Go to http://${CONTROLLER-IP}:8181/apidoc/explorer/index.html, and look under DIDM section
to see all the available REST calls and tables