== <Project Name> <Release Name> Release Notes
For example, the title might be "OpenFlow Plugin Lithium Release Notes"

Provide an overview about the high level feature. Explain the smaller
features developed within the highlevel feature to provide a solution.
For example,OpenFlow Support could contain sub features such as TLS
support, Tables, Ports, Queue Configuration, and so on.

=== Major Capabilities and Enhancements
Provide information about the major capabilities this project provides
in this release. Include those from previous release unless they have
been deprecated or removed (see below).

==== New Capabilities and Enhancements
Call out the new capabilities and/or enhancements that are present in
this release, but were not present in prior releases.

==== Resolved Bugs
List open and resolved bugs if any.

=== Deprecated and Removed Capabilities
Provide information about the capabilities that are removed or
deprecated in this release.

=== Known Limitations
List any feature limitations that the user must be aware.

==== Open Bugs
List any remaining open bugs. Ideally provide a short description and a 
link to the entry in bugzilla.

=== Compatibility with Previous Releases
<optional, required if there's a previous release>

Is it compatible? Did anything about how a user or developer would
consume it change? If so, document it here.

=== Migration from Previous Releases
<optional, required if there's a previous release>

Describe any special step somebody would have to take to migrate from a
previous release to this one. If migration isn't supported for some
combinations, state that as well.
