== Group Based Policy OfOverlay User Guide
This section is for Application Developers and Network Administrators
who are looking to use the OfOverlay renderer for Group Based Policy
to create a network virtualization solution on their infrastructure.

=== Overview
The OpenFlow Overlay (OfOverlay) feature enables the OpenFlow Overlay
renderer, which creates a network virtualization solution across nodes
that host Open vSwitch software switches.  The user configures the required
infrastructure, such as instantiating vSwitch bridges, attaching hosts to
the bridges, and creating the tunnel ports on the bridges used in the
OpenFlow Overlay.  The user can then create the policy they want that
allows Endpoints in Endpoint Groups to communicate with each other,
as expressed by the policy, and the OfOverlay renderer creates the
flow-mods on the vSwitches to create the overlay and enforce the
policy.

The nodes participating in the overlay must run Open vSwitch,
as it has features such as Nicira Extensions that are needed in order
to implement the overlay.  Common use cases for the OpenFlow Overlay
renderer include Data Center and Campus.

=== OpenFlow Overlay Architecture
The OpenFlow Overlay feature renders the policy defined by the user
into OpenFlow flow-mods on the devices in the managed infrastructure.
The renderer uses the OpenFlow plugin to communicate with and program
the vSwitches.

The feature uses the OpenFlow plugin to communicate with the vSwitches
and generate the flow-mods to implement the OpenFlow overlay.

Provide information about feature components and how they work together.
Also include information about how the feature integrates with
OpenDaylight. An architecture diagram could help.

=== Configuring OpenFlow Overlay
The OpenFlow Overlay renderer requires additional configuration to
the normal configuration required in Group Based Policy. In addition
to configuring the policy and registering Endpoints, you must also
configure augmentations in both the Inventory model and on the
Endpoints.

Tunnel ports can be created on Open vSwitch using ovs-vsctl commands.
The following is an example of how to create a VXLAN overlay tunnel
port called s1_vxlan0, on bridge s1:

----
sudo ovs-vsctl add-port <bridge name> <port name> -- set interface s1_vxlan0 type=vxlan options:key=flow options:remote_ip=flow
----
To create a VXLAN port named s1_vxlan0 on bridge s1, this would be the command:
----
sudo ovs-vsctl add-port s1 s1_vxlan0 -- set interface s1_vxlan0 type=vxlan options:key=flow options:remote_ip=flow
----

The options key=flow and remote_ip=flow means that the VXLAN tunnel ID
("key") and tunnel destination IP address will be set using flow-mods 
in Open vswitch.

The bridges also must be connected to the controller. This can be
done using another ovs-vsctl command:
----
sudo ovs-vsctl set-controller s1 tcp:<IP address of the controller>:6653
----
To connect bridge s1 to a controller with an IP address of 192.168.194.1,
you would do the following:
----
sudo ovs-vsctl set-controller s1 tcp:192.168.194.1:6653
----

The following is an example of how the Inventory model augmentations
are used to tell Group Based Policy which vSwitches will be managed
by the OpenFlow Overlay renderer. In this case, there are two vSwitches,
openflow:1 and openflow:2, each with an overlay tunnel (openflow:1:1
and openflw:2:1, respectively).

----
PUT http://{{controllerIp}}:8181/restconf/config/opendaylight-inventory:nodes/
{
    "opendaylight-inventory:nodes": {
        "node": [
            {
                "id": "openflow:1", 
                "ofoverlay:tunnel": [
                    {
                        "tunnel-type": "overlay:tunnel-type-vxlan",
                        "ip": "192.168.194.142",
                        "port": 4789,
                        "node-connector-id": "openflow:1:1"
                    }
                ]
            }, 
            {
                "id": "openflow:2", 
                "ofoverlay:tunnel": [
                    {
                        "tunnel-type": "overlay:tunnel-type-vxlan",
                        "ip": "192.168.194.146",
                        "port": 4789,
                        "node-connector-id": "openflow:2:1"
                    }
                ]
            }
        ]
    }
}
----

For instructions on how to configure policy and register Endpoints,
refer to the odl-groupbasedpolicy-base feature User Guide.

The following is an example of Endpoint registration using the additional
"port-name" attribute provided by the OpenFlow Overlay augmentation:
----
POST http://{{controllerIp}}:8181/restconf/operations/endpoint:register-endpoint
{
    "input": {
        "endpoint-group": "1eaf9a67-a171-42a8-9282-71cf702f61dd", 
        "network-containment" : "d2779562-ebf1-45e6-93a4-78e2362bc418",
        "l2-context": "7b796915-adf4-4356-b5ca-de005ac410c1", 
        "mac-address": "00:00:00:00:35:02", 
        "l3-address": [
            {
                "ip-address": "10.0.35.2", 
                "l3-context": "cbe0cc07-b8ff-451d-8171-9eef002a8e80"
            }
        ], 
        "port-name": "vethl-h35_2", 
        "tenant": "f5c7d344-d1c7-4208-8531-2c2693657e12"
    }
}
----

You should be able to see the location information augmentation
when reading the endpoint back:
----
GET http://{{controllerIp}}:8181/restconf/operational/endpoint:endpoints/endpoint:endpoint/7b796915-adf4-4356-b5ca-de005ac410c1/00:00:00:00:35:02
{
    "endpoint": [
        {
            "l2-context": "7b796915-adf4-4356-b5ca-de005ac410c1",
            "mac-address": "00:00:00:00:35:02",
            "tenant": "f5c7d344-d1c7-4208-8531-2c2693657e12",
            "timestamp": 1432216646793,
            "network-containment": "d2779562-ebf1-45e6-93a4-78e2362bc418",
            "ofoverlay:port-name": "vethl-h35_2",
            "ofoverlay:node-connector-id": "openflow:1:2",
            "ofoverlay:node-id": "openflow:1",
            "l3-address": [
                {
                    "l3-context": "cbe0cc07-b8ff-451d-8171-9eef002a8e80",
                    "ip-address": "10.0.35.2"
                }
            ],
            "endpoint-group": "1eaf9a67-a171-42a8-9282-71cf702f61dd"
        }
    ]
}
----
The augmentations show up as fields with the "ofoverlay:" prefix.
The OfOverlay renderer determines this dynamically based on the port
name provided when the Endpoints are registered. In this case, the
Endpoint lives on the bridge "openflow:1" in the OpenDaylight inventory
model, on the port "openflow:1:1", again in the inventory model.

=== Administering or Managing Group Based Policy OpenFlow Overlay
To start the OpenFlow Overlay renderer, do the following:

. Step 1: start karaf
. Step 2: load the OpenFlow Overlay Renderer feature with restconf
----
opendaylight-user@root> feature:install odl-groupbasedpolicy-ofoverlay odl-restconf
----
. Step 3: Verify that the controller is running
After a few seconds, the controller should be up and the OfOverlay renderer
should be running. You can verify this using the following command in
the karaf console:
----
opendaylight-user@root>log:display | grep OFOverlayRenderer
----

You should see something like the following:
----
2015-05-21 09:55:51,712 | INFO  | config-pusher    | OFOverlayRenderer                |
313 - org.opendaylight.groupbasedpolicy.ofoverlay-renderer - 0.2.0.SNAPSHOT | Initialized OFOverlay renderer
----
. Step 4: Configure the vSwitches that will participate in the overlay
. Step 5: Register the Endpoints that will participate in the overlay
. Step 6: Configure any policy


Include related command reference or  operations that you could perform
using the feature. For example viewing network statistics, monitoring
the network,  generating reports, and so on.

NOTE:  Ensure that you create a step procedure whenever required and
avoid concepts.

For example:

.To configure L2switch components perform the following steps.
. Step 1:
. Step 2:
. Step 3:

=== Tutorials
The groupbasedpolicy repo contains scripts that can be used to
demonstrate the openflow overlay renderer. There is also information
on the Group Based Policy wiki page.

If there is only one tutorial, you skip the "Tutorials" section and
instead just lead with the single tutorial's name.

==== <Tutorial Name>
Ensure that the title starts with a gerund. For example using,
monitoring, creating, and so on.

===== Overview
An overview of the use case.

===== Prerequisites
Provide any prerequisite information, assumed knowledge, or environment
required to execute the use case.

===== Target Environment
Include any topology requirement for the use case. Ideally, provide
visual (abstract) layout of network diagrams and any other useful visual
aides.

===== Instructions
Use case could be a set of configuration procedures. Including
screenshots to help demonstrate what is happening is especially useful.
Ensure that you specify them separately. For example:

. *Setting up the VM*
To set up a VM perform the following steps.
.. Step 1
.. Step 2
.. Step 3

. *Installing the feature*
To install the feature perform the following steps.
.. Step 1
.. Step 2
.. Step 3

. *Configuring the environment*
To configure the system perform the following steps.
.. Step 1
.. Step 2
.. Step 3
