== TCPMD5 Developer Guide

=== Overview

The TCPMD5 project delivers the support for providing access to MD5 Signature
Option on operating systems which support it in their TCP stack.  The
implementation is compliant with link:http://tools.ietf.org/html/rfc2385[RFC-2385].

The project is available from the tcpmd5 repository. It is split into:

tcpmd5-api

tcpmd5-jni

tcpmd5-nio

tcpmd5-netty

tcpmd5-controller-config

tcpmd5-feature

=== TCPMD5 Architecture

This project defines a new TCP option for carrying an MD5 digest
in a TCP segment. This digest acts like a signature for that segment,
incorporating information known only to the connection end points.

=== Key APIs and Interfaces

As this project is fairly small, it provides only one feature that installs and
provides all APIs and implementations for this project.

==== tcpmd5-api

Defines the basic API and a dummy implementation.

==== tcpmd5-jni

Contains the JNI implementation and its Java binding. The core of the artifact
is NativeKeyAccess.java, which is the Java frontend and binding class. It
defines the two native methods, setChannelKey0() and isClassSupported0(). These
are implemented in tcpmd5_jni.c. Individual instances are then provided by
NativeKeyAccessFactory, which runs basic sanity tests before allowing itself
being instantiated.

==== tcpmd5-nio

Contains the code to bridge the JNI component with java.nio package,
specifically ServerSocketChannel, SocketChannel and SocketOption classes.

==== tcpmd5-netty

Contains the code to bridge the JNI component with netty.io, by providing the
appropriate SocketChannelFactory.

