== TCP-MD5 Developer Guide

=== Overview

The project is available from the tcpmd5 repository. It is split into:

.[big]#*tcpmd5-api*#

Defines the basic API and a dummy implementation.

.[big]#*tcpmd5-jni*#

Contains the JNI implementation and its Java binding. The core of the artifact is NativeKeyAccess.java, which is the Java frontend and binding class. It defines the two native methods, setChannelKey0() and isClassSupported0(). These are implemented in tcpmd5_jni.c. Individual instances are then provided by NativeKeyAccessFactory, which runs basic sanity tests before allowing itself being instantiated.

.[big]#*tcpmd5-nio*#

Contains the code to bridge the JNI component with java.nio package, specifically ServerSocketChannel, SocketChannel and SocketOption classes.

.[big]#*tcpmd5-netty*#

Contains the code to bridge the JNI component with netty.io, by providing the appropriate SocketChannelFactory.

.[big]#*tcpmd5-controller-config*#

Default (disabled) configuration for activation.

.[big]#*tcpmd5-feature*#

Karaf feature artifact, pulling in all the other artifacts.

=== TCPMD5 Architecture

Provide information about feature components and how they work together.
Also include information about how the feature integrates with
OpenDaylight. An architecture diagram could help. This may be the same
as the diagram used in the user guide, but it should likely be less
abstract and provide more information that would be applicable to a
developer.

=== Key APIs and Interfaces

Document the key things a user would want to use. For some features,
there will only be one logical grouping of APIs. For others there may be
more than one grouping.

Assuming the API is MD-SAL- and YANG-based, the APIs will be available
both via RESTCONF and via Java APIs. Giving a few examples using each is
likely a good idea.

==== API Group 1
Provide a description of what the API does and some examples of how to
use it.

==== API Group 2
Provide a description of what the API does and some examples of how to
use it.

=== API Reference Documentation
Provide links to JavaDoc, REST API documentation, etc.
