== L3VPN Service: User Guide

=== Overview
L3VPN Service in Opendaylight provides a framework to create L3VPN based on BGP-MP.  It also helps to create Network Virtualization for DC Cloud environment.

=== Modules & Interfaces
L3VPN service can be realized using the following modules -

==== VPN Service Modules
. *VPN Manager* : Creates and manages VPNs and VPN Interfaces
. *BGP Manager* : Configures BGP routing stack and provides interface to routing services
. *FIB Manager* : Provides interface to FIB, creates and manages forwarding rules in Dataplane
. *Nexthop Manager* : Creates and manages nexthop egress pointer, creates egress rules in Dataplane
. *Interface Manager* : Creates and manages different type of network interfaces, e.g., VLAN, l3tunnel etc.,
. *Id Manager* : Provides cluster-wide unique ID for a given key. Used by different modules to get unique IDs for different entities.
. *MD-SAL Util* : Provides interface to MD-SAL. Used by service modules to access MD-SAL Datastore and services.
. *ITM* : Internal Transport Manager creates and maintains mesh of tunnels of type VxLAN or GRE between Openflow switches forming an overlay transport network

All the above modules can function independently and can be utilized by other services as well.

==== Configuration Interfaces
The following modules expose configuration interfaces through which user can configure L3VPN Service.

. BGP Manager
. VPN Manager
. Interface Manager
. ITM

===== Configuration Interface Details

.BGP Manager Interface
. Data Node Path : _/config/bgp:bgp-router/_
.. Fields :
... local-as-identifier
... local-as-number
.. REST Methods : GET, PUT, DELETE, POST
. Data Node Path : _/config/bgp:bgp-neighbors/_
.. Fields :
... List of bgp-neighbor
.. REST Methods : GET, PUT, DELETE, POST
. Data Node Path : _/config/bgp:bgp-neighbors/bgp-neighbor/`{as-number}`/_
.. Fields :
... as-number
... ip-address
.. REST Methods : GET, PUT, DELETE, POST

.VPN Manager Interface
. Data Node Path : _/config/l3vpn:vpn-instances/_
.. Fields :
... List of vpn-instance
.. REST Methods : GET, PUT, DELETE, POST
. Data Node Path : _/config/l3vpn:vpn-instances/vpn-instance_
.. Fields :
... name
... route-distinguisher
... vpnTargets
.. REST Methods : GET, PUT, DELETE, POST
. Data Node Path : _/config/l3vpn:vpn-interfaces/_
.. Fields :
... List of vpn-interface
.. REST Methods : GET, PUT, DELETE, POST
. Data Node Path : _/config/l3vpn:vpn-interfaces/vpn-interface_
.. Fields :
... name
... vpn-instance-name
.. REST Methods : GET, PUT, DELETE, POST
. Data Node Path : _/config/l3vpn:vpn-interfaces/vpn-interface/`{name}`/adjacency_
.. Fields :
... ip-address
... mac-address
.. REST Methods : GET, PUT, DELETE, POST

.Interface Manager Interface
. Data Node Path : _/config/if:interfaces/interface_
.. Fields :
... name
... type
... enabled
... datapath-node-identifier
... parent-interface
.. type specific fields
... when type = _l2vlan_
.... vlan-id
.... vlan-mode
... when type = _stacked_vlan_
.... stacked-vlan-id
... when type = _tunnel_
.... internal
.... tunnel-interface-type
.... tunnel-source
.... tunnel-destination
.... tunnel-gateway
... when type = _mpls_
.... list labelStack
.... num-labels
.. REST Methods : GET, PUT, DELETE, POST

.ITM Interface
. Data Node Path : _/config/itm:transport-zones/_
.. Fields :
... List of transport-zone
.. REST Methods : GET, PUT, DELETE, POST
. Data Node Path : _/config/itm:transport-zones/transport-zone_
.. Fields :
... zone-name
... tunnel-type
.. REST Methods : GET, PUT, DELETE, POST
. Data Node Path : _/config/itm:transport-zones/transport-zone/subnets_
.. Fields :
... prefix
... gateway-ip
... vlan-id
... List of vteps
.. REST Methods : GET, PUT, DELETE, POST
. Data Node Path : _/config/itm:transport-zones/transport-zone/subnets/vteps/_
.. Fields :
... dpn-id
... portname
... ip-address
.. REST Methods : GET, PUT, DELETE, POST

=== Provisioning Sequence & Sample Configurations

[[install]]
==== Installation
1. Edit 'etc/custom.properties' and set the following property:
'vpnservice.bgpspeaker.host.name = <bgpserver-ip>'
'<bgpserver-ip>' here refers to the IP address of the host where BGP is running.

2. Run ODL and install VPN Service
'feature:install odl-vpnservice-core'

Use REST interface to configure L3VPN service

[[prer]]
==== Pre-requisites:

1. BGP stack with VRF support needs to installed and configured
a. _Configure BGP as specified in Step 1 below._

2. Create pairs of GRE/VxLAN Tunnels between each switch(internal tunnel) and between each switch to the gateway node(external tunnel).
a. _Create 'tunnel' interfaces corresponding to each tunnel in interfaces DS as specified in Step 2 below._

==== Step 1 : Configure BGP

===== 1. Configure BGP Router

*REST API* : _PUT /config/bgp:bgp-router/_

*Sample JSON Data*
[source,json]
-----------------
{
    "bgp-router": {
        "local-as-identifier": "10.10.10.10",
        "local-as-number": 108
    }
}
-----------------


===== 2. Configure BGP Neighbors

*REST API* : _PUT /config/bgp:bgp-neighbors/_

*Sample JSON Data*

[source,json]
-----------------
  {
     "bgp-neighbor" : [
            {
                "as-number": 105,
                "ip-address": "169.144.42.168"
            }
       ]
   }
-----------------

==== Step 2 : Create Tunnel Interfaces
Create tunnels between two switches with the following REST interface

*REST API* : _/config/itm:transport-zones/transport-zone_

*Sample JSON Data*

[source,json]
-----------------
{
  "transport-zones": {
    "transport-zone": [
      {
        "zone-name": "TZA",
        "subnets": [
          {
            "prefix": "10.0.0.0/29",
            "vlan-id": 0,
            "vteps": [
              {
                "dpn-id": 1,
                "portname": "phy0",
                "ip-address": "192.168.56.102"
              },
              {
                "dpn-id":2,
                "portname": "phy0",
                "ip-address": "192.168.56.101"
              },
             ],
            "gateway-ip": "10.0.0.5"
          }
        ],
        "tunnel-type": "GRE"
      }
    ]
  }
}

-----------------

===== Following is expected as a result of these configurations

1. Unique If-index is generated
2. 'Interface-state' operational DS is updated
3. Corresponding Nexthop Group Entry is created

==== Step 3 : OS Create Neutron Ports and attach VMs

At this step user creates VMs. <TBD>

==== Step 4 : Create VM Interfaces
Create l2vlan interfaces corresponding to VM created in step 3

*REST API* : _PUT /config/if:interfaces/if:interface_

*Sample JSON Data*

[source,json]
-----------------
{
    "interface": [
        {
             "name": "dpn1-dp1.2",
             "type": "iana-if-type:l2vlan",
             "enabled": "true"
        }
    ]
}

-----------------

==== Step 5: Create VPN Instance

*REST API* : _PUT /config/l3vpn:vpn-instances/l3vpn:vpn-instance/_

*Sample JSON Data*

[source,json]
-----------------
{
  "vpn-instance": [
    {
        "description": "Test VPN Instance 1",
        "vpn-instance-name": "testVpn1",
        "ipv4-family": {
            "route-distinguisher": "4000:1",
            "vpnTargets": {
                "vpnTarget": [
                   {
                        "vrfRTValue": "4000:1",
                        "vrfRTType": "export_extcommunity"
                   },
                   {
                       "vrfRTValue": "5000:1",
                       "vrfRTType": "import_extcommunity"
                   },
                   {
                       "vrfRTValue": "6000:1",
                       "vrfRTType": "both"
                   }
                              ]
                          }
                       }
    }
  ]
}

-----------------

===== Following is expected as a result of these configurations

1. VPN ID is allocated and updated in data-store
2. Corresponding VRF is created in BGP
3. If there are vpn-interface configurations for this VPN, corresponding action is taken as defined in step 5

==== Step 5 : Create VPN-Interface and Local Adjacency

_this can be done in two steps as well_

===== 1. Create vpn-interface

*REST API* : _PUT /config/l3vpn:vpn-interfaces/l3vpn:vpn-interface/_

*Sample JSON Data*

[source,json]
-----------------
{
  "vpn-interface": [
    {
      "vpn-instance-name": "testVpn1",
      "name": "dpn1-dp1.2",
    }
  ]
}
-----------------

[NOTE]
name here is the name of VM interface created in step 3, 4

===== 2. Add Adjacencies on vpn-interafce

*REST API* : _PUT /config/l3vpn:vpn-interfaces/l3vpn:vpn-interface/dpn1-dp1.3/adjacency_

*Sample JSON Data*

[source,json]
-----------------
  {
     "adjacency" : [
            {
                "ip-address" : "169.144.42.168",
                "mac-address" : "11:22:33:44:55:66"
            }
       ]
   }
-----------------


[quote]
its a list, user can define more than one adjacency on a vpn_interface

Above steps can be carried out in a single step as following

[source,json]
-----------------
{
    "vpn-interface": [
        {
            "vpn-instance-name": "testVpn1",
            "name": "dpn1-dp1.3",
            "odl-l3vpn:adjacency": [
                {
                    "odl-l3vpn:mac_address": "11:22:33:44:55:66",
                    "odl-l3vpn:ip_address": "11.11.11.2",
                }
            ]
        }
    ]
}

-----------------


===== Following is expected as a result of these configurations

1. Prefix label is generated and stored in DS
2. Ingress table is programmed with flow corresponding to interface
3. Local Egress Group is created
4. Prefix is added to BGP for advertisement
5. BGP pushes route update to FIB YANG Interface
6. FIB Entry flow is added to FIB Table in OF pipeline


=== Using with OpenStack

VPNService now supports orchestration through openstack using the BGPVPN Plugin. This section requires familiarity with OpenStack and ODL configuration. If you are using OpenStack then this is the preferred method as it takes care of lots of configuration you'd need to do manually.

==== Installation
1. Edit 'etc/custom.properties' and set the following property:
'vpnservice.bgpspeaker.host.name = <bgpserver-ip>'
'<bgpserver-ip>' here refers to the IP address of the host where BGP is running.

2. Run ODL and install VPN Service OpenStack
'feature:install odl-vpnservice-openstack'

==== Devstack Settings

If you already have a working ODL+OpenStack setup you need to add following additional entries in local.conf to enable BGPVPN Plugin

*devstack/local.conf*

[literal]
--
enable_plugin networking-bgpvpn https://git.openstack.org/openstack/networking-bgpvpn.git

[[post-config|$NETWORKING_BGPVPN_CONF]]
[service_providers]
service_provider=BGPVPN:OpenDaylight:networking_bgpvpn.neutron.services.service_drivers.opendaylight.odl.OpenDaylightBgpvpnDriver:default
--

OpenStack will by default create bridge `br-int` to which all the VM Ports will be added. You will need `datapath-id` of each Compute Node's `br-int` to setup a tunnel mesh between them. Refer section ITM above on how to create tunnel mesh.

To configure L3VPN with OpenStack you need to create a BGPVPN Instance in OpenStack and then associate with a Neutron Network.

*Creating BGPVPN Instance*
[literal]
--
neutron bgpvpn-create --route-targets 10:4 --import-targets '10:1,10:2,10:3' --route-distinguishers '100:1'  --tenant_id <tenant-id> --name myVpn1
--

*Associating Network to BGPVPN Instance*
[literal]
--
neutron bgpvpn-net-assoc-create myVpn1 --network <network-id> 
--

Now you can create VMs as you normally would using `nova boot`. They will get associated to appropriate VPN Instance and VPN Interfaces will be created for them.

==== BGPVPN API Reference documentation

Refer BGPVPN API Reference for more information on how to configure BGPVPN.

* http://docs.openstack.org/developer/networking-bgpvpn/
