== API design principles and patterns contributed by southbound plugins

This section is intended to define common design patterns supporting extensions contributed by southbound plugins, which could be used in the SAL or or used in modelling any abstract extensible APIs.

NOTE: Wire protocol specific information (serialization, serialization constants , TLV identifiers, bit masks, field ordering) should not be part of the SAL. Also, APIs (interfaces, classes) should support extensibility using subclassing or other extension patterns. This allows for abstract APIs and also for concrete APIs to coexist in the SAL and to use common infrastructure.

=== Extensible enumeration pattern

This pattern is suitable for modelling or defining APIs for the enumeration of immutable data or types, which for example could represent ether type, protocol type, and others. The workflow for API definition is simple:

. Define a simple interface with the needed functionality.

. Declare an enum implementing the interface where the enum constants represent the known values.

. (optional) Include a factory method mapping from names to objects implementing the interface.

For more information, see the following links:

** http://jtechies.blogspot.com/2012/07/item-34-emulate-extensible-enums-with.html

** http://blogs.oracle.com/darcy/entry/enums_and_mixins

=== Type-value pairs pattern

This pattern is suitable for modelling or defining APIs for extensible set of fields, where the values could be of different types. The requirements for type-value pairs are: Extensible and Type safety.

==== Common antipatterns

This pattern is to replace the following constructs:


* Simple untyped approach to properties (pros: extensible, cons: does not provide semantics and type safety):

[literal]
// Ommited for clarity...
HashMap<String,Object> properties;


* More refined approach using the enumeration to define a set of supported field types (pros: provides semantics, cons: not extensible).

[literal]
enum Type {
  TYPE1(String.class),
  TYPE2(Boolean.class),
  private Class<?> valueType; // This line is optional.
  // ommited for clarity... 
}
class Field {
  Type type;
  Object value;
  // ommited for clarity...
}


=== Actual pattern

We can model this by using the abstract class and the generics to define value type and set of subclasses representing various types of fields. The instances of this class represents actual type-value pair, where class represents type and value is represented by object in the instance.

[literal]
abstract class Field<V> {
   private V value;
   public Field(V value) {
      this.value = value;
   }
   ...
}
 class Type1Field extends Field<String> {
  public Type1Field(String value){super(value);}
}
 class Type2Field extends Field<Boolean> {
  public Type2Field(Boolean value){super(value);}
}

The abstract class does not have to only define fields or values, but could also define additional methods (concrete or abstract) which could provide additional semantic about the field type. This example shows only one value field, but it is possible to have multiple fields. It is possible to model common part of API also as an interface and leave all the implementation to the super types. Map, which should store one instance of the field is: Map<Class<? extends Field<?>>,Field<?>>. It is possible to provide simpler facade on top of this map.

=== Extension interface pattern

The following Java design allows an object to be extended without changing its interface to clients. The object can implement additional extension interfaces. Clients can ask the object for extension interfaces that it implements.


In the interface present in the SAL models general approach or abstraction, the client code (applications) could ask for extension interface (which could be used to model protocol specific functionality, interfaces, data) by querying for the extension. Extension is identified by Java interface (the client code using extension must be compiled against this interface).


This pattern could be also used as an replacement for the field pattern. We have defined a set of fields provided by extension as separate class or interface, the values could be queried by using the extension class.
The strong point of this pattern is that the client code needs to be aware of the extension and its contract (be compiled against the base interface and also extension) in order to use the extension. The code which was not compiled against extension is not affected by introducing new extensions.

*Synopsis: Original pattern*

[literal]
public interface A {
   // Ommited for clarity...
  <T> T getExtension(Class<T> extensionType)
}

*Synopsis: Updated pattern*
[literal]
public interface Extensible<P> {
   // Ommited for clarity...
  <T extends Extension<P>> T getExtension(Class<T> extensionType)
}
public interface Extension<T> {
}

Where:

* Extensible is interface which is to be implemented by classes which provides extension support

* P - generic argument, usually interface / class which implements

* Extension is marker interface (for type-safety reasons) which marks interfaces / classes which are extensions

* T - generic argument, pointing to the class / interface to which this extension is associated.

=== Usage example

[literal]
ublic class Node extends Extensible<Node> {
  // contents ommited
  // the instatiated version of extension interface isExtension method is
  @Override
  <T extends Extension<Node> T getExtension(Class<T> extensionType) {
    // contents ommited
  }
}
public class OpenflowNode extends Extension<Node> {
   // contents ommited
}
Node node = provider.getNode(); // sample call returning node
OpenflowNode ofNode = node.getExtension(OpenflowNode.class);
if(ofNode != null) {
  // do openflow specific stuff
}
