== Running the OpenDaylight controller

NOTE: Download the latest build of the controller from https://jenkins.opendaylight.org/controller/job/controller-merge/lastSuccessfulBuild/artifact/opendaylight/distribution/opendaylight/target/[here]. The source code of the OpenDaylight controller is in a directory called opendaylight. In this directory (the corresponding directory in the git repository is usually the distribution/opendaylight/target/distribution.opendaylight-0.1.0-SNAPSHOT-osgipackage/opendaylight).

NOTE: The controller platform has specific core bundles, each of which export important services through Java interfaces. Here is a brief list of important ones that come in handy while developing network services. These are located at https://wiki.opendaylight.org/view/Controller_Projects%27_Modules/Bundles_and_Interfaces[Controller Projects' Modules, Bundles, and Interfaces].

NOTE: For a list of files in OpenDaylight karaf, see https://wiki.opendaylight.org/view/Karaf_Distribution_Folder_and_File_Guide[Karaf Distribution Folder and File Guide].

Apache Karaf is a small OSGi based runtime which provides a lightweight container onto which various components and applications can be deployed. It tends to be helpful to think of Karaf as providing an ecosystem for an application where various libraries and frameworks are collected and tested that they work well together, simplifying your runtime experience.

There are two ways to start the controller in Karaf.

. Run the command below to access the Karaf console:

[literal]

bin/karaf

. Run the command below to start Karaf as a background task, accessing the console using SSH:

[literal]

bin/start

SSH is listening on 8101 and the default username and password is karaf/karaf. Run the command below to access the console

[literal]
ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 8101 karaf@<controllerIP>

To log out of the SSH shell, run  the command below:

[literal]
shell: logout

==== Installing or uninstalling controller features

Features that are installed as part of the karaf-compatible-all integration job include the following files: 

* odl-restconf
* odl-mdsal-apidocs
* odl-integration-compatible-with-l2switch 

Before starting karaf, you can edit the file *etc/org.apache.karaf.features.cfg* to install additional features. Modify the line `featuresBoot=config,standard,region,package,kar,ssh,management` to be `featuresBoot=config,standard,region,package,kar,ssh,management,odl-restconf,odl-mdsal-apidocs, odl-integration-compatible-with-l2switch`



=== Karaf CLI

* To list only installed features, run the command: 

[literal]
 feature:list -i 
 

* Filter with grep

[literal]
feature:list | grep openflowplugin 

* List bundles loaded

[literal]
 bundle:list -s
 
List web endpoints

[literal]
web:list


Uninstall a feature


[literal]
 feature:uninstall odl-l2switch-switch 

 
=== Running the controller GUI


.  Navigate to http://controller-ip:8080 to open the web interface, then use the following credentials to log in:

** *User*: admin

** *Password*: admin


