OpenDaylight Virtual Tenant Network (VTN):VTN Coordinator:RestApi:How to test vlan-map in Mininet environment

== Overview
This example explains how to test vlan-map in a multi host scenario.

image::vlanmap_using_mininet[Example that demonstrates vlanmap testing in Mininet Environment]

== Requirements
* Save the mininet script given below as vlan_vtn_test.py and run the mininet script in the mininet environment where Mininet is installed.

[cols=*3,2a,^,options="header",width="75%"]
|===
|
from mininet.node import Host, RemoteController<br>
  from mininet.topo import Topo<br>
  class VLANHost( Host ):<br>
     def config( self, vlan=100, **params ):<br>
        """Configure VLANHost according to (optional) parameters:<br>
              vlan: VLAN ID for default interface"""<br>
        r = super( Host, self ).config( **params )<br>
        intf = self.defaultIntf()<br>
  # remove IP from default, "physical" interface<br>
       self.cmd( 'ifconfig %s inet 0' % intf )<br>
  # create VLAN interface<br>
       self.cmd( 'vconfig add %s %d' % ( intf, vlan ) )<br>
  # assign the host's IP to the VLAN interface<br>
       self.cmd( 'ifconfig %s.%d inet %s' % ( intf, vlan, params['ip'] ) )<br>
  # update the intf name and host's intf map<br>
       newName = '%s.%d' % ( intf, vlan )<br>
  # update the (Mininet) interface to refer to VLAN interface name<br>
       intf.name = newName<br>
  # add VLAN interface to host's name to intf map<br>
       self.nameToIntf[ newName ] = intf<br>
       return r<br>
  class MyTopo( Topo ):<br>
     "Simple topology example."<br>
  def __init__( self ):<br>
     "Create custom topo."<br>
  # Initialize topology<br>
      Topo.__init__( self )<br>
  # Add hosts and switches<br>
      host1=self.addHost( 'h1', cls=VLANHost, vlan=200)<br>
      host2=self.addHost( 'h2', cls=VLANHost, vlan=300)<br>
      host3=self.addHost( 'h3', cls=VLANHost, vlan=200)<br>
      host4=self.addHost( 'h4', cls=VLANHost, vlan=300)<br>
      host5=self.addHost( 'h5', cls=VLANHost, vlan=200)<br>
      host6=self.addHost( 'h6', cls=VLANHost, vlan=300)<br>
      s1 = self.addSwitch( 's1' )<br>
      s2 = self.addSwitch( 's2' )<br>
      s3 = self.addSwitch( 's3' )<br>
      self.addLink(s1,host1)<br>
      self.addLink(s1,s2)<br>
      self.addLink(s2,host2)<br>
      self.addLink(s2,host3)<br>
      self.addLink(s2,host4)<br>
      self.addLink(s1,s3)<br>
      self.addLink(s3,host5)<br>
      self.addLink(s3,host6)<br>
  topos = { 'mytopo': ( lambda: MyTopo() ) }<br>
|===
*  Run the mininet script:
sudo mn --controller=remote,ip=192.168.64.13 --custom vlan_vtn_test.py --topo mytopo
== Configuration

Please follow the below steps to test a vlan map using mininet:
[Mininet script]
* .Create a controller
curl --user admin:adminpass -H 'content-type: application/json'  -X POST -d '{"controller": {"controller_id": "controllerone", "ipaddr":"10.0.0.2", "type": "odc", "version": "1.0", "auditstatus":"enable"}}' http://127.0.0.1:8083/vtn-webapi/controllers

* .Create a VTN
curl -X POST -H 'content-type: application/json' -H 'username: admin' -H 'password: adminpass' -d '{"vtn" : {"vtn_name":"vtn1","description":"test VTN" }}' http://127.0.0.1:8083/vtn-webapi/vtns.json

* .Create a vBridge(vBridge1)
curl -X POST -H 'content-type: application/json' -H 'username: admin' -H 'password: adminpass' -d '{"vbridge" : {"vbr_name":"vBridge1","controller_id":"controllerone","domain_id":"(DEFAULT)" }}' http://127.0.0.1:8083/vtn-webapi/vtns/vtn1/vbridges.json

* .Create a vlan map with vlanid 200 for vBridge vBridge1
curl -X POST -H 'content-type: application/json' -H 'username: admin' -H 'password: adminpass' -d '{"vlanmap" : {"vlan_id": 200 }}' http://127.0.0.1:8083/vtn-webapi/vtns/vtn1/vbridges/vBridge1/vlanmaps.json

* .Create a vBridge (vBridge2)
curl -X POST -H 'content-type: application/json' -H 'username: admin' -H 'password: adminpass' -d '{"vbridge" : {"vbr_name":"vBridge2","controller_id":"controllerone","domain_id":"(DEFAULT)" }}' http://127.0.0.1:8083/vtn-webapi/vtns/vtn1/vbridges.json

* .Create a vlan map with vlanid 300 for vBridge vBridge2
curl -X POST -H 'content-type: application/json' -H 'username: admin' -H 'password: adminpass' -d '{"vlanmap" : {"vlan_id": 300 }}' http://127.0.0.1:8083/vtn-webapi/vtns/vtn1/vbridges/vBridge2/vlanmaps.json

== Verification

Ping all in mininet environment to view the host reachability.

[cols=*3,2a,^,options="header",width="75%"]
|===
| mininet> pingall
Ping: testing ping reachability
h1 -> X h3 X h5 X
h2 -> X X h4 X h6
h3 -> h1 X X h5 X
h4 -> X h2 X X h6
h5 -> h1 X h3 X X
h6 -> X h2 X h4 X
|===
[[Category:OpenDaylight Virtual Tenant Network]]

