=== SFC OpenFlow Layer 2 Renderer User Guide

==== Overview
Provide an overview of the feature and the use case. Also include the
audience who will use the feature. For example,  audience can be the
network administrator, cloud administrator, network engineer, system
administrators, and so on.

The SFC OpenFlow Layer 2 Renderer implements Service Chaining on Open Flow
switches. It listens for the creation of a Rendered Service Path, and once 
received it programs Service Function Forwarders that are hosted on Open
Flow capable switches to steer packets through the service chain.

==== SFC OFS Architecture

TODO add an SFCOFL2 architecture diagram here

TODO explain the SFCOFL2 Flow pipeline.

==== Administering or Managing <feature>

TODO list the necesary Karaf features for SFCOFL2.

==== SFCOFL2 Tutorial

TODO add an example SFC configuration that demonstrates a simple use-case.

====== Overview
An overview of the use case.

====== Prerequisites
Provide any prerequisite information, assumed knowledge, or environment
required to execute the use case.

====== Target Environment
Include any topology requirement for the use case. Ideally, provide
visual (abstract) layout of network diagrams and any other useful visual
aides.

====== Instructions
Use case could be a set of configuration procedures. Including
screenshots to help demonstrate what is happening is especially useful.
Ensure that you specify them separately. For example:

. *Setting up the VM*
To set up a VM perform the following steps.
.. Step 1
.. Step 2
.. Step 3

. *Installing the feature*
To install the feature perform the following steps.
.. Step 1
.. Step 2
.. Step 3

. *Configuring the environment*
To configure the system perform the following steps.
.. Step 1
.. Step 2
.. Step 3
