=== Service Function Grouping and Load Balancing User Guide

==== Overview
SFC Load-Balancing feature implements load balancing of Service Functions, rather than a one-to-one mapping between Service-Function-Forwarder and Service-Function. 

==== Load Balancing Architecture
Service-Function-Groups (SFG) can replace Service-Functions (SF) in the Service-Path model. 
A Service-Path can only be defined using SFG's or SF's, but not a combination of both.

Relevant objects in the YANG model are as follows:
1. Service-Function-Group-Algorithm:

	Service-Function-Group-Algorithms {
		Service-Function-Group-Algorithm {
			String name
			String type
		}
	}

2. Service-Function-Group:

	Service-Function-Groups {
		Service-Function-Group {
			String name
			String serviceFunctionGroupAlgorithmName
			String type
			Service-Function-Group-Element {
				String service-function-name
				int index
			}
		}
	}

3. ServiceFunctionHop: holds a reference to a name of SFG (or SF)

==== Tutorials
This tutorial will explain how to create a simple SFC configuration, with SFG instead of SF. In this example, the SFG will include two existing SF.

===== Setup SFC
For general SFC setup and scenarios, please see the SFC wiki page: https://wiki.opendaylight.org/view/Service_Function_Chaining:Main#SFC_101

===== Create an algorithm
POST - http://127.0.0.1:8181/restconf/config/service-function-group-algorithm:service-function-group-algorithms
{
    "service-function-group-algorithm": [
      {
        "name": "alg1"
      }
   ]
}

(Header "content-type": application/json)

===== Verify: get all algorithms
GET - http://127.0.0.1:8181/restconf/config/service-function-group-algorithm:service-function-group-algorithms

In order to delete all algorithms:
DELETE - http://127.0.0.1:8181/restconf/config/service-function-group-algorithm:service-function-group-algorithms

===== Create a group
POST - http://127.0.0.1:8181/restconf/config/service-function-group:service-function-groups 
{
    "service-function-group": [
    {
        "rest-uri": "http://localhost:10002",
        "ip-mgmt-address": "10.3.1.103",
        "algorithm": "alg1",
        "name": "SFG1",
        "type": "service-function-type:napt44",
		"sfc-service-function": [
			{
				"name":"napt44-104"
			}, 
			{
				"name":"napt44-103-1"
			}
		]
      }
	]
}

===== Verify: get all SFG's
GET - http://127.0.0.1:8181/restconf/config/service-function-group:service-function-groups 