=== Service Function Scheduler
Refer to this template to identify the required sections and information
that you should  provide for a User Guide. The user guide should contain
configuration, administration, management, using, and troubleshooting
sections for the feature.

==== Overview
Provide an overview of the feature and the use case. Also include the
audience who will use the feature. For example,  audience can be the
network administrator, cloud administrator, network engineer, system
administrators, and so on.

==== Architecture
Provide information about feature components and how they work together.
Also include information about how the feature integrates with
OpenDaylight. An architecture diagram could help.

==== Select SFs with Scheduler
Provide information about feature components and how they work together.
Also include information about how the feature integrates with
OpenDaylight. An architecture diagram could help.

===== Random
Ensure that the title starts with a gerund. For example using,
monitoring, creating, and so on.

====== Overview
An overview of the use case.

====== Prerequisites
Provide any prerequisite information, assumed knowledge, or environment
required to execute the use case.

====== Target Environment
Include any topology requirement for the use case. Ideally, provide
visual (abstract) layout of network diagrams and any other useful visual
aides.

====== Instructions
Use case could be a set of configuration procedures. Including
screenshots to help demonstrate what is happening is especially useful.
Ensure that you specify them separately. For example:

===== Round Robin
Ensure that the title starts with a gerund. For example using,
monitoring, creating, and so on.

====== Overview
An overview of the use case.

====== Prerequisites
Provide any prerequisite information, assumed knowledge, or environment
required to execute the use case.

====== Target Environment
Include any topology requirement for the use case. Ideally, provide
visual (abstract) layout of network diagrams and any other useful visual
aides.

====== Instructions
Use case could be a set of configuration procedures. Including
screenshots to help demonstrate what is happening is especially useful.
Ensure that you specify them separately. For example:

===== Load Balance
Ensure that the title starts with a gerund. For example using,
monitoring, creating, and so on.

====== Overview
An overview of the use case.

====== Prerequisites
Provide any prerequisite information, assumed knowledge, or environment
required to execute the use case.

====== Target Environment
Include any topology requirement for the use case. Ideally, provide
visual (abstract) layout of network diagrams and any other useful visual
aides.

====== Instructions
Use case could be a set of configuration procedures. Including
screenshots to help demonstrate what is happening is especially useful.
Ensure that you specify them separately. For example:

===== Shortest Path
Ensure that the title starts with a gerund. For example using,
monitoring, creating, and so on.

====== Overview
An overview of the use case.

====== Prerequisites
Provide any prerequisite information, assumed knowledge, or environment
required to execute the use case.

====== Target Environment
Include any topology requirement for the use case. Ideally, provide
visual (abstract) layout of network diagrams and any other useful visual
aides.

====== Instructions
Use case could be a set of configuration procedures. Including
screenshots to help demonstrate what is happening is especially useful.
Ensure that you specify them separately. For example:
