== Neutron Northbound

=== How to Write a SB Neutron Consumer

In Lithium, there will be two options for SB Neutron Consumers:

* Using the legacy I*Aware interfaces
* Listening for changes via the Neutron YANG model

=== How to use the legacy I*Aware interfaces

For each neutron data object, there is an I*Aware interface defined to allow
southbound providers that don't want to use the MD-SAL to register with the
Neutron service to be made aware of potential operations on that type of
object.  For each modification operation (create, update and delete), the
I*Aware interface defines a pair of calls (The general template
is shown in the following table, please see javadoc of the specific interface
for specific details)

.Table I*Aware Methods
|===
|Create |Update |Delete

|canCreate*()
|canUpdate*()
|canDelete*()

|neutron*Created()
|neutron*Updated()
|neutron*Deleted()
|===

==== The semantics of the can*() methods

Each of the can*() methods gives a southbound provider a vote on whether a
proposed change is acceptable or not. A southbound provider that implements
a particular can*() method is expected to return an HTTP response code as
its "vote" - values between 200 and 299 are a "yes" vote, other values are
a "no" vote.  The neutron white board pattern is an all or nothing affair:
if any one southbound provider votes no on a change, that change is rejected.

For the canCreate*() method, the southbound provider recieves the proposed
object.  In the case of canDelete*(), the southbound provider recieves the
current object that will be removed.  Lastly, the canUpdate*() method passed
the current object and the proposed delta.

==== The semantics of the neutron*() methods

Once all southbound providers vote yes for a particular change, the neutron
service transcribes the change into its caches/MD-SAL models and then calls
the appropriate neutron*() method on each registered southbound provider.
At this point, the southbound provider is expected to meet the request as
best they can and when they can, taking responsibility for any errors that
might be incurred (there is no back signalling of errors).  For these calls,
the modified object is provided in all cases, except for the neutron*Deleted()
method.  This passes an instance of the deleted object that will be garbage
collected once all the southbound providers are finished with it.

==== How to register your consumer with the Neutron Service

A southbound provider that wants to register with the neutron service
via a particular I*Aware interface must first implement that interface.
Then, in the init class of its Activator method, it should add the name of
the implemented I*Aware class as an interface that is managed, along with
the class that implements the interface as the implementation via the
setInterface method.  The following example from the Neutron test dummy
provider shows it is registering for *all* I*Aware interfaces:

[source,java]
----
    @Override
    public void init(BundleContext context, DependencyManager manager) throws Exception {
       manager.add(createComponent().setInterface(new String[] {
           INeutronFirewallAware.class.getName()}, null)
           .setImplementation(NeutronFirewallDummyProvider.class));
       manager.add(createComponent().setInterface(new String[] {
           INeutronFirewallPolicyAware.class.getName()}, null)
           .setImplementation(NeutronFirewallPolicyDummyProvider.class));
       manager.add(createComponent().setInterface(new String[] {
           INeutronFirewallRuleAware.class.getName()}, null)
           .setImplementation(NeutronFirewallRuleDummyProvider.class));
       manager.add(createComponent().setInterface(new String[] {
           INeutronFloatingIPAware.class.getName()}, null)
           .setImplementation(NeutronFloatingIPDummyProvider.class));
       manager.add(createComponent().setInterface(new String[] {
           INeutronLoadBalancerAware.class.getName()}, null)
           .setImplementation(NeutronLoadBalancerDummyProvider.class));
       manager.add(createComponent().setInterface(new String[] {
           INeutronLoadBalancerHealthMonitorAware.class.getName()}, null)
           .setImplementation(NeutronLoadBalancerHealthMonitorDummyProvider.class));
       manager.add(createComponent().setInterface(new String[] {
           INeutronLoadBalancerListenerAware.class.getName()}, null)
           .setImplementation(NeutronLoadBalancerListenerDummyProvider.class));
       manager.add(createComponent().setInterface(new String[] {
           INeutronLoadBalancerPoolAware.class.getName()}, null)
           .setImplementation(NeutronLoadBalancerPoolDummyProvider.class));
       manager.add(createComponent().setInterface(new String[] {
           INeutronLoadBalancerPoolMemberAware.class.getName()}, null)
           .setImplementation(NeutronLoadBalancerPoolMemberDummyProvider.class));
       manager.add(createComponent().setInterface(new String[] {
           INeutronNetworkAware.class.getName()}, null)
           .setImplementation(NeutronNetworkDummyProvider.class));
       manager.add(createComponent().setInterface(new String[] {
           INeutronPortAware.class.getName()}, null)
           .setImplementation(NeutronPortDummyProvider.class));
       manager.add(createComponent().setInterface(new String[] {
           INeutronRouterAware.class.getName()}, null)
           .setImplementation(NeutronRouterDummyProvider.class));
       manager.add(createComponent().setInterface(new String[] {
           INeutronSecurityGroupAware.class.getName()}, null)
           .setImplementation(NeutronSecurityGroupDummyProvider.class));
       manager.add(createComponent().setInterface(new String[] {
           INeutronSecurityRuleAware.class.getName()}, null)
           .setImplementation(NeutronSecurityRuleDummyProvider.class));
       manager.add(createComponent().setInterface(new String[] {
           INeutronSubnetAware.class.getName()}, null)
           .setImplementation(NeutronSubnetDummyProvider.class));
    }
----

=== How to use the Neutron YANG model

For each neutron data object, there is an Neutron*Interface defined within
the transcriber artifact that will write that object to the MD-SAL
configurational datastore. +
All Neutron*Interface extend AbstractNeutronInterface, in which two methods
are defined: +

* one takes the neutron object as input, and will create a data object from it. +
* one takes an uuid as input, and will create a data object containing the uuid.

----
protected abstract T toMd(S neutronObject);
protected abstract T toMd(String uuid);
----

In addition the AbstractNeutronInterface class provides several other
helper methods (addMd, updateMd, removeMd), which handle the actual
writing to the configuration datastore.

==== The semantics of the toMD() methods
Each of the Neutron YANG models defines structures containing data.
Further each YANG-modeled structures has it own builder.
A particular toMD() method instantiates an instance of the correct
builder, fills in the properties of the builder from the corresponding
values of the Neutron object and then creates the YANG-modeled structures
via the build() method.

As an example, one of the toMD code for Neutron Networks is
presented below:

----
    protected Network toMd(NeutronNetwork network) {
        NetworkBuilder networkBuilder = new NetworkBuilder();
        networkBuilder.setAdminStateUp(network.getAdminStateUp());
        if (network.getNetworkName() != null) {
            networkBuilder.setName(network.getNetworkName());
        }
        if (network.getShared() != null) {
            networkBuilder.setShared(network.getShared());
        }
        if (network.getStatus() != null) {
            networkBuilder.setStatus(network.getStatus());
        }
        if (network.getSubnets() != null) {
            List<Uuid> subnets = new ArrayList<Uuid>();
            for( String subnet : network.getSubnets()) {
                subnets.add(toUuid(subnet));
            }
            networkBuilder.setSubnets(subnets);
        }
        if (network.getTenantID() != null) {
            networkBuilder.setTenantId(toUuid(network.getTenantID()));
        }
        if (network.getNetworkUUID() != null) {
            networkBuilder.setUuid(toUuid(network.getNetworkUUID()));
        } else {
            logger.warn("Attempting to write neutron network without UUID");
        }
        return networkBuilder.build();
    }
----
