[[]]
=== End to End Inventory

The purpose of this section is to walk you through how to see the Inventory
Manager working end to end with the openflowplugin using OpenFlow 1.3.

Basically, you will learn how to:

1.  Run the Base/Virtualization/Service provider Edition with the new
openflowplugin:
OpenDaylight_OpenFlow_Plugin::Running_controller_with_the_new_OF_plugin[Running
the controller with the new OpenFlow Plugin]
2.  Start mininet to use OF 1.3:
OpenDaylight_OpenFlow_Plugin::Test_Environment[OpenFlow 1.3 Enabled
Software Switches / Environment]
3.  Use RESTCONF to see the nodes appear in inventory.

[[restconf-for-inventory]]
==== Restconf for Inventory

The REST url for listing all the nodes is:

------------------------------------------------------------------------
http://localhost:8181/restconf/operational/opendaylight-inventory:nodes/
------------------------------------------------------------------------

You will need to set the Accept header:

-----------------------
Accept: application/xml
-----------------------

You will also need to use HTTP Basic Auth with username: admin password:
admin.

Alternately, if you have a node's id you can address it as

---------------------------------------------------------------------------------
http://localhost:8181/restconf/operational/opendaylight-inventory:nodes/node/<id>
---------------------------------------------------------------------------------

for example

---------------------------------------------------------------------------------------
http://localhost:8181/restconf/operational/opendaylight-inventory:nodes/node/openflow:1
---------------------------------------------------------------------------------------

