[[odl-ofp-end-to-end-inventory_introduction-introduction]]
===== Introduction

The purpose of this page is to walk you through how to see the Inventory
Manager working end to end with the openflowplugin using OpenFlow 1.3.

Basically, you will learn how to:

1.  Run the Base/Virtualization/Service provider Edition with the new
openflowplugin:
OpenDaylight_OpenFlow_Plugin::Running_controller_with_the_new_OF_plugin[Running
the controller with the new OpenFlow Plugin]
2.  Start mininet to use OF 1.3:
OpenDaylight_OpenFlow_Plugin::Test_Environment[OpenFlow 1.3 Enabled
Software Switches / Environment]
3.  Use RESTCONF to see the nodes appear in inventory.

[[odl-ofp-end-to-end-flows_restconf-for-inventory]]
===== Restconf for Inventory

The REST url for listing all the nodes is:

------------------------------------------------------------------------
http://localhost:8181/restconf/operational/opendaylight-inventory:nodes/
------------------------------------------------------------------------

You will need to set the Accept header:

-----------------------
Accept: application/xml
-----------------------

You will also need to use HTTP Basic Auth with username: admin password:
admin.

Alternately, if you have a node's id you can address it as

---------------------------------------------------------------------------------
http://localhost:8181/restconf/operational/opendaylight-inventory:nodes/node/<id>
---------------------------------------------------------------------------------

for example

---------------------------------------------------------------------------------------
http://localhost:8181/restconf/operational/opendaylight-inventory:nodes/node/openflow:1
---------------------------------------------------------------------------------------

[[odl-ofp-end-to-end-flows_how-to-hit-restconf-with-postman]]
====== How to hit RestConf with Postman

https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en[Install
Postman for Chrome]

In the chrome browser bar enter

--------------
chrome://apps/
--------------

And click on Postman.

Enter the URL. Click on the Headers button on the far right. Enter the
Accept: header. Click on the Basic Auth Tab at the top and setup the
username and password. Send.

[[odl-ofp-end-to-end-flows_known-bug]]
===== Known Bug

If you have not had any switches come up, and though no children for
http://localhost:8080/restconf/datastore/opendaylight-inventory:nodes/
and exception will be thrown. I'm pretty sure I know how to fix this
bug, just need to get to it :)
