=== Running controller with the MD-SAL OpenFlow plugin

[[run-opendaylight-controller-with-the-new-openflow-1.01.3-plugin]]
==== Run OpenDaylight controller with the new OpenFlow 1.0/1.3 plugin

There are 2 ways. In integration project the plugin version is
controlled by startup parameter. Or there is distribution build
available directly in openflowplugin project.

1.  use *integration* project
* download and unzip latest build from
https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/integration/distribution-karaf/0.2.2-SNAPSHOT/
  `cd <extracted directory>/bin`
  `./karaf `
* or clone and build *integration* project:
  `git clone https://git.opendaylight.org/gerrit/p/integration.git`
  `cd integration/distributions/extra/karaf`
  `mvn clean install`
  `cd ./target/assembly/bin`
* and finally run
./karaf


2.  use *openflowplugin* project
* download and unzip latest build from
https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/openflowplugin/openflowplugin-karaf/0.1.0-SNAPSHOT/
  `cd <extracted directory>/bin`
  `./karaf `
* or clone and build *openflowplugin* project:
  `git clone https://git.opendaylight.org/gerrit/p/openflowplugin.git`
  `cd openflowplugin`
  `mvn clean install`
  `cd ./distribution/karaf/target/assembly/bin/`
* and run
./karaf

[[enable-restconf-and-controller-gui]]
===== Enable RESTCONF and Controller GUI

If you want to use RESTCONF with openflowplugin project, you have to
install _odl-restconf_ feature to enable that. To install _odl-restconf_
feature run the following command

#:

-----------------------------------
karaf#>feature:install odl-restconf
-----------------------------------

If you want to access the Controller GUI, you have to install
_odl-dlux-core_ feature to enable that. Run following command to install
it

#:

------------------------------------
karaf#>feature:install odl-dlux-core
------------------------------------

Once you enable the feature, access the Controller GUI using following
URL

#:

-------------------------------------------
http://<controller-ip>:8181/dlux/index.html
-------------------------------------------

[[run-opendaylight-controller-with-the-old-openflow-1.0-only-old-plugin]]
==== Run OpenDaylight controller with the old OpenFlow 1.0-only (old)
plugin

There are 2 ways. In integration project the plugin version is
controlled by startup parameter. Or there is distribution build
available directly in controller project.

1.  use *integration/distributions/base* project
* use the instructions from
OpenDaylight_OpenFlow_Plugin::Running_controller_with_the_new_OF_plugin#To_run_the_OpenDaylight_controller_with_the_new_OpenFlow_1.0/1.3_(new)_plugin[
1.0/1.3 plugin], but skip the plugin version parameter:
./run.sh


2.  use *controller/distribution/opendaylight* project
* download and unzip latest build from
https://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/controller/distribution.opendaylight/
  `cd opendaylight`
* or clone and build *controller* project:
  `git clone https://git.opendaylight.org/gerrit/p/controller.git`
  `cd controller/opendaylight/distribution/opendaylight`
  `mvn clean install`
  `cd target/distribution.opendaylight-osgipackage/opendaylight`
* and finally run (there is no version specific option, because the
1.0/1.3 (new) plugin is not available here at all)
./run.sh

*Give it a minute to come up 
