== OpenDaylight Controller

=== Overview ===

OpenDaylight Controller is Java-based model-driven controller using YANG
as its modeling language for various aspects of the system and applications
and with it's components serves as a base platform for other OpenDaylight
controller applications.

OpenDaylight Controller is

* built using following technologies:
** *OSGI* - This framework is the back-end of OpenDaylight as it allows
dynamically loading of bundles and packages JAR files, and binding bundles
together for exchanging information.
** *Karaf* - Application container built on top of OSGI, which simplifies
   operational aspects of packaging and installing applications.
** *YANG* - a data modeling language used to model configuration and
   state data manipulated by the applications, remote procedure calls, and
   notifications.

* provides following model-driven subsystems as a foundation for Java
applications:
** *Config* Subsystem - an activation, dependency-injection and configuration
   framework, which allows two-phase commits of configuration and dependency-injection
   and allow for run-time rewiring.
** *MD-SAL* - messaging and data storage functionality for data, notifications
   and RPCs modeled by application developers. MD-SAL uses YANG as the modeling
   language for both interface and data definitions, and provides a messaging
   and data-centric runtime for such services based on YANG modeling.
** *MD-SAL Clustering* - enables cluster support for core MD-SAL functionality
   and provides location-transparent accesss to YANG-modeled data.

* support for external access to applications and data using model-driven
protocols
** *NETCONF* - XML based RPC protocol, which provides abilities for client to
   invoke YANG-modeled RPCs, receive notifications and to read, modify and
   manipulate YANG modeled data.
** *RESTCONF* - HTTP based protocol, which provides REST-like APIs to manipulate
   YANG modeled data and invoke YANG modeled RPCs, using XML or JSON as payload
   format.


include::md-sal.adoc[MD-SAL]
include::restconf.adoc[Restconf]
include::config.adoc[Config Subsytem]
