=== Northbound (NETCONF servers)
OpenDaylight provides 2 types of NETCONF servers:

* *NETCONF server for config-subsystem (listening by default on port
  1830)*
  ** Serves as a default interface for config-subsystem and allows
  users to spawn/reconfigure/destroy modules (or applications) in OpenDaylight
* *NETCONF server for MD-SAL (listening by default on port 2830)*
** Serves as an alternative interface for MD-SAL (besides RESTCONF)
  and allows users to read/write data from MD-SAL's datastore and to
  invoke its rpcs (NETCONF notifications are not available in the
  Beryllium release of OpenDaylight)

NOTE: The reason for having 2 NETCONF servers is that config-subsystem and
MD-SAL are 2 different components of OpenDaylight and require different
approach for NETCONF message handling and data translation. These 2
components will probably merge in the future.

==== NETCONF server for config-subsystem
This NETCONF server is the primary interface for config-subsystem. It
allows the users to interact with config-subsystem in a standardized
NETCONF manner.

In terms of RFCs, these are supported:

* http://tools.ietf.org/html/rfc6241[RFC-6241]
* https://tools.ietf.org/html/rfc5277[RFC-5277]
* https://tools.ietf.org/html/rfc6470[RFC-6470]
** (partially, only the
  schema-change notification is available in Beryllium release)
* https://tools.ietf.org/html/rfc6022[RFC-6022]

For regular users it is recommended to use RESTCONF + the
controller-config loopback mountpoint instead of using pure NETCONF.
How to do that is spesific for each component/module/application
in OpenDaylight and can be found in their dedicated user guides.

==== NETCONF server for MD-SAL
This NETCONF server is just a generic interface to MD-SAL in OpenDaylight.
It uses the stadard MD-SAL APIs and serves as an alternative to
RESTCONF. It is
fully model driven and supports any data and rpcs that are supported
by MD-SAL.

In terms of RFCs, these are supported:

* http://tools.ietf.org/html/rfc6241[RFC-6241]
* https://tools.ietf.org/html/rfc6022[RFC-6022]

Notifications over NETCONF are not supported in the Beryllium release.

TIP: Install NETCONF northbound for MD-SAL by installing feature:
+odl-netconf-mdsal+ in karaf. Default binding port is *2830*.

===== Configuration
The default configuration can be found in file:
_08-netconf-mdsal.xml_. The file contains the configuration for all
necessary dependencies and a single SSH endpoint starting on port 2830.
There is also a (by default disabled) TCP endpoint. It is possible
to start multiple endpoints at the same time either in the initial
configuration file or while OpenDaylight is running.

The credentials for SSH endpoint can also be configured here, the
defaults are admin/admin. Credentials in the SSH endpoint are not yet
managed by the centralized AAA component and have to be configured
separately.

===== Verifying MD-SAL's NETCONF server
After the NETCONF server is available it can be examined by a
command line ssh tool:

----
ssh admin@localhost -p 2830 -s netconf
----

The server will respond by sending its HELLO message and can be used
as a regular NETCONF server from then on.

===== Mounting the MD-SAL's NETCONF server
To perform this operation, just spawn a new netconf-connector as described in
<<_spawning_additional_netconf_connectors_while_the_controller_is_running,
Spawning netconf-connector>>.
Just change the ip to "127.0.0.1" port to "2830" and its name to "controller-mdsal".

Now the MD-SAL's datastore can be read over RESTCONF via NETCONF by invoking:

GET http://localhost:8181/restconf/operational/network-topology:network-topology/topology/topology-netconf/node/controller-mdsal/yang-ext:mount

NOTE: This might not seem very useful, since MD-SAL can be accessed
directly from RESTCONF or from Application code, but the same method can be used to
mount and control other OpenDaylight instances by the "master OpenDaylight".
