[[bk-getting-started-guide]]
= OpenDaylight Getting Started Guide
:docinfo:

//////////////////////////
// BEGIN COMMENT
[dedication]
Example Dedication
------------------
Optional dedication.

This document is an AsciiDoc book skeleton containing briefly
annotated example elements plus a couple of example index entries and
footnotes.

Books are normally used to generate DocBook markup and the titles of
the preface, appendix, bibliography, glossary and index sections are
significant ('specialsections').


[preface]
Example Preface
---------------
Optional preface.

Preface Sub-section
~~~~~~~~~~~~~~~~~~~
Preface sub-section body.

Using OpenDaylight
--------------------------

[partintro]
.Optional part introduction title
--
Optional part introduction goes here.
--

OpenDaylight Add-ons
-------------------------

[partintro]
.Optional part introduction title
--
Optional part introduction goes here.
--
// END COMMENT
//////////////////////////

//////////////////////////
// BEGIN COMMENT
Please note and leave the blank line between include statements here.

It is a defensive measure to prevent individual projects' .adoc files
from eating the next section if they forget to leave a blank line at
the end of their file.
// END COMMENT
//////////////////////////

include::release-notes.adoc[OpenDaylight Release Notes]

include::general_installation.adoc[]

= Getting to know OpenDaylight

include::ch-introduction.adoc[]

include::ch-dlux.adoc[]

include::ch-xsql-commands.adoc[]

include::ch-clustering.adoc[]

include::chapter_security_considerations.adoc[]

= Project-specific Installation Guides

include::opflex/agent-ovs-install.adoc[]

include::ovsdb/ovsdb-install.adoc[]

include::tsdr/tsdr-h2-install.adoc[]

include::tsdr/tsdr-hbase-install.adoc[]

include::vtn/vtn-install.adoc[]

include::nemo/nemo_engine_install.adoc[]
:numbered!:

//////////////////////////
// BEGIN COMMENT
[appendix]
Example Appendix
----------------
One or more optional appendixes go here at section level 1.

Appendix Sub-section
~~~~~~~~~~~~~~~~~~~
Sub-section body.


[glossary]
Example Glossary
----------------
Glossaries are optional. Glossaries entries are an example of a style
of AsciiDoc labeled lists.

[glossary]
A glossary term::
  The corresponding (indented) definition.

A second glossary term::
  The corresponding (indented) definition.


[colophon]
Example Colophon
----------------
Text at the end of a book describing facts about its production.


[index]
Example Index
-------------
// END COMMENT
//////////////////////////

////////////////////////////////////////////////////////////////
The index is normally left completely empty, it's contents being
generated automatically by the DocBook toolchain.
////////////////////////////////////////////////////////////////

