== OpenDaylight Release Notes

=== Key Features

A list of the key functionality provided in OpenDaylight Helium can be found in the table in the <<_installing_the_components,section below>>.

////
The following table describes the key features provided by OpenDaylight Helium.

[cols="2",option="headers"]
|==============================================
| *Feature* | *Description*
|  Maven support | Used to simplify build automation.
| OSGi framework | Serves as the controller's back-end, allowing it to dynamically load bundles, package JAR files, and bind bundles together when exchanging information.
| Java interface support | Used by specific bundles to implement call-back functions for events and indicate the awareness of specific states.
| Model- Driven Service Abstraction Layer (MD-SAL) | Allows the controller to support multiple protocols (such as BGP-LS and OpenFlow) on the southbound interface. Also provides consistent services for modules and applications (which is where the business logic is embedded).
| Switch Manager | Once a network element has been discovered, its details (such as device type, software version, etc.) are stored by the Switch Manager.
| High Availability (HA) | The controller supports cluster-based HA, allowing you to connect multiple controllers and configure them to act as one in order to ensure the controller's continuous operation.
|==============================================
////
=== Target Environment

==== For Execution

The OpenDaylight Karaf container, OSGi bundles, and Java class files
are portable and should run on any Java 7- or Java 8-compliant JVM to
run. Certain projects and certain features of some projects may have
additional requirements. Those are noted in the project-specific
release notes.

// TODO: Do we want to call out specific projects that have other requirements?
// * TCP-MD5 requires 64-bit Linux
// * TSDR requirements for HBase?
// * SFC requirements for OVS (also lots of Linux I think)
// * SXP depends on TCP-MD5
// * SNBI for Linux, Docker, C and other things
// * OpFlex for lots of things
// * DLUX many things for development, what browsers?
// * AAA if you using SSSD which comes with Centos/RHEL

NOTE: If you are using Oracle, JDK version 1.7.0_45 or later is required.

==== For Development

OpenDaylight is written primarily in Java project and primarily uses
Maven as a build tool Consequently the two main requirements to develop
projects within OpenDaylight are:

* A Java 7- or Java 8-compliant JDK
* Maven 3.1.1 or later

Applications and tools built on top of OpenDaylight using it's REST
APIs should have no special requirements beyond whatever is needed to
run the application or tool and make the REST calls.

In some places, OpenDaylight makes use of the Xtend language. While
Maven will download the appropriate tools to build this, additional
plugins may be required for IDE support.

=== Known Issues and Limitations

Other than as noted in project-specific release notes, there are two
known limitations.

// I'm 99% sure we fixed this
// . The Karaf distribution of OpenDaylight requires internet access when run for the first time.

// TODO: We need a newer version of this
. There are scales beyond which the controller has been unreliable when
collecting flow statistics from OpenFlow switches. In tests, theses
issues became apparent when managing 10s of thousands of OpenFlow
switches, however this may vary depending on deployment and use cases.
Flow programming has been unaffected in our tests.
