#!/usr/bin/env python
import os
import shutil

chapterNames = []
guidesDirectory = 'developer-guide-autogenerated'
imagePath = 'developer-guide/images'


def isEquqalsSign(str):
    # Check if this line only contains '='
    if str.strip() == '':
        return False
    for ch in str:
        if ch != '=':
            return False
    return True


def isGuideHeader(title, equalsSign):
    if not isEquqalsSign(equalsSign.rstrip()):
        return False
    if len(title.rstrip()) == len(equalsSign.rstrip()):
        return True
    else:
        return False


def getLines(lines, start, end):
        # Get the text of one chapter
    out = ''
    while(start < end):
        out += lines[start]
        start += 1
    return out


def getGuides(lines, lineNumbers):
    output = []
    for i in range(0, len(lineNumbers)):
        if i != len(lineNumbers) - 1:
            start = lineNumbers[i] - 1
            end = lineNumbers[i + 1] - 1
            output.append(getLines(lines, start, end))
        else:
            start = lineNumbers[i] - 1
            end = len(lines)
            output.append(getLines(lines, start, end))
    return output


def printToFile(textList):
    guiderIndex = 0

    for text in textList:
        try:
            file = open(guidesDirectory + '/' +
                        chapterNames[guiderIndex] + '.rst', 'w')
        except:
            file = open(guidesDirectory + '/' +
                        chapterNames[guiderIndex] + '.rst', 'w')
        file.write(text)
        file.close()
        guiderIndex += 1
    return


def copyDirectory(src, dest):
    try:
        shutil.copytree(src, dest)
    # Directories are the same
    except shutil.Error as e:
        print('Directory not copied. Error: %s' % e)
    # Any error saying that the directory doesn't exist
    except OSError as e:
        print('Directory not copied. Error: %s' % e)


class FileWrapper(object):
    def __init__(self, f):
        self.f = f
        self.line = 0

    def close(self):
        return self.f.close

    def readline(self):
        self.line += 1
        return self.f.readline()

    def readlines(self):
        return self.f.readlines()

# Create guidesDirectory if necessary
if not os.path.exists(guidesDirectory):
            os.makedirs(guidesDirectory)

deGuide = FileWrapper(open("developer-guide/index.rst"))

lineAbove = deGuide.readline()
line = deGuide.readline()

lineNumbers = []

while (line != ''):
    if isGuideHeader(lineAbove, line):
        lineNumbers.append(deGuide.line - 1)
        chapterNames.append(lineAbove.lower().replace(' ', '-').rstrip())
    lineAbove = line
    line = deGuide.readline()

deGuide = FileWrapper(open("developer-guide/index.rst"))
lines = deGuide.readlines()
deGuide.close()
textList = getGuides(lines, lineNumbers)
printToFile(textList)

# Copy image path to developer-guide-autogenerated derectory
copyDirectory(imagePath, guidesDirectory + '/images')

# Initialize the index.rst file
# 1.rename opendaylight-developer-guide.rst(title + author) to index.rst
# 2.write toctree info to index.rst
indexPath = guidesDirectory + '/' + 'index.rst'
try:
    os.rename(guidesDirectory + '/' + chapterNames[0] + '.rst', indexPath)
except OSError:
    print chapterNames[0] + '.rst ' + 'not exists.'

rstIndexText = open(indexPath, 'a')
rstIndexText.write('.. toctree:: \n')
rstIndexText.write('	:maxdepth: 1 \n')
rstIndexText.write('\n')
for i in range(1, len(chapterNames)):
    rstIndexText.write('	' + chapterNames[i] + '\n')
rstIndexText.close()
