== OVSDB Openstack Installation Guide

=== Overview
This guide is geared towards installing OVSDB Openstack.

OpenVSwitch (OVS) is generally accepted as the unofficial standard for Virtual Switching in the Open hypervisor based solutions. Every other Virtual Switch implementation, properietery or otherwise, uses OVS in some form.
For information on OVS, see http://openvswitch.org/[Open vSwitch].

In Software Defined Networking (SDN), controllers and applications interact using two channels: OpenFlow and OVSDB. OpenFlow addresses the forwarding-side of the OVS functionality. OVSDB, on the other hand, addresses the management-plane. 
A simple and concise overview of Open Virtual Switch Database(OVSDB) is available at: http://networkstatic.net/getting-started-ovsdb/

=== Pre Requisites for Installing OVSDB Openstack
* JDK 1.7+
* Maven 3.1.1+
* A distribution of Opendaylight with the neutron plugin.

=== Preparing for Installation
The Vagrant file in the root of the OVSDB source code provides an easy way to create VMs for tests. 

* To install Vagrant on your machine, follow the steps at: https://docs.vagrantup.com/v2/installation/[Installing Vagrant].

*Prepare the openstack environment (in this case devstack)*

. Start the controller.
----
vagrant up devstack-control
vagrant ssh devstack-control
cd devstack
./stack.sh
----
[start=2]
. Run the following:
----
vagrant up devstack-compute-1
vagrant ssh devstack-compute-1
cd devstack
./stack.sh
----
[start=3]
. To start testing, create a new VM.
----
nova boot --flavor m1.tiny --image $(nova image-list | grep 'cirros-0.3.1-x86_64-uec\s' | awk '{print $2}') --nic net-id=$(neutron net-list | grep private | awk '{print $2}') test
----
To create three, use the following:
----
nova boot --flavor m1.tiny --image $(nova image-list | grep 'cirros-0.3.1-x86_64-uec\s' | awk '{print $2}') --nic net-id=$(neutron net-list | grep private | awk '{print $2}') --num-instances 3 test
----
[start=4]
.To get a mininet installation for testing:
----
vagrant up mininet
vagrant ssh mininet
----
[start=5]
. Use the following to clean up when finished:
----
vagrant destroy
----

=== Installing OVSDB Openstack
[[ovsdbBuildSteps]]
==== Building a Karaf feature and deploying it in an Opendaylight Karaf distribution +
This is a new method for Opendaylight distribution wherein there are no defined editions such 
as Base, Virtualization, or SP editions.  The end-customer can choose to deploy the required feature based on user deployment needs.

. From the root ovsdb/ directory, run *mvn clean install*.
. Unzip the distribution-karaf-<VERSION_NUMBER>-SNAPSHOT.zip file created from step 1 in the directory ovsdb/distribution/opendaylight-karaf/target:
----
unzip distribution-karaf-<VERSION_NUMBER>-SNAPSHOT.zip
----
==== Downloading OVSDB's Karaf distribution +
Instead of building, you can download the latest OVSDB distribution from the Nexus server. The link for that is:
----
http://nexus.opendaylight.org/content/repositories/opendaylight.snapshot/org/opendaylight/ovsdb/distribution.ovsdb/1.2.0-SNAPSHOT/
----
==== Running Karaf feature from OVSDB's Karaf distribution +

[[ovsdbStartingOdl]]
. Start ODL, from the unzipped directory
----
bin/karaf
----
. Once karaf has started, and you see the Opendaylight ascii art in the console, the last step is to start the OVSDB plugin framework with the following command in the karaf console: 
----
feature:install odl-ovsdb-openstack
----

For ovsdb northbound, you will also need to invoke
----
feature:install odl-ovsdb-northbound
----
===== Sample output from the Karaf console
----
opendaylight-user@root>feature:list | grep -i ovsdb 
odl-ovsdb-all                    | 1.0.0-SNAPSHOT      |           | ovsdb-1.0.0-SNAPSHOT        
OpenDaylight :: OVSDB :: all 
odl-ovsdb-library                | 1.0.0-SNAPSHOT      | x         | ovsdb-1.0.0-SNAPSHOT        
OVSDB :: Library 
odl-ovsdb-schema-openvswitch     | 1.0.0-SNAPSHOT      | x         | ovsdb-1.0.0-SNAPSHOT        
OVSDB :: Schema :: Open_vSwitch 
odl-ovsdb-schema-hardwarevtep    | 1.0.0-SNAPSHOT      | x         | ovsdb-1.0.0-SNAPSHOT        
OVSDB :: Schema :: hardware_vtep
odl-ovsdb-plugin                 | 1.0.0-SNAPSHOT      | x         | ovsdb-1.0.0-SNAPSHOT        
OpenDaylight :: OVSDB :: Plugin
odl-ovsdb-northbound             | 0.6.0-SNAPSHOT      |           | ovsdb-1.0.0-SNAPSHOT        
OpenDaylight :: OVSDB :: Northbound 
odl-ovsdb-openstack              | 1.0.0-SNAPSHOT      | x         | ovsdb-1.0.0-SNAPSHOT        
OpenDaylight :: OVSDB :: OpenStack Network Virtual 
odl-ovsdb-ovssfc                 | 0.0.1-SNAPSHOT      |           | ovsdb-0.0.1-SNAPSHOT        
OpenDaylight :: OVSDB :: OVS Service Function Chai
odl-openflow-nxm-extensions      | 0.0.3-SNAPSHOT      | x         | ovsdb-0.0.3-SNAPSHOT        
OpenDaylight :: Openflow :: Nicira Extensions
----

=== Verifying your Installation
To verify that the installation was successful, use the log:display command in karaf and check that there are no errors
logs relative to odl-ovsdb-openstack.

==== Troubleshooting
There are no easy way to troubleshoot an installation of odl-ovsdb-openstack. Perhaps a combination of
log:display in karaf, OpenVSwitch commands (ovs-vsdctl) and openstack logs will be useful but will not
explain everything. Another way is to ask in the #opendaylight-ovsdb channel on the freenode network (IRC).

=== Post Installation Configuration
Not applicable.

=== Upgrading From a Previous Release
Upgrading from upstream

Upgrading from release

=== Uninstalling OVSDB Openstack
Simply use the feature:uninstall odl-ovsdb-openstack command or stop the karaf container with
system:shutdown command.
