== Messaging4Transport Developer Guide

=== Overview
Messaging4Transport can be configured such that the data tree, RPCs, and notifications are sent to an external broker, or an integrated broker with OpenDaylight. Messaging4Transport uses ActiveMQ as the default external broker. It further uses AMQP as the messaging protocol for the Beryllium Release.


=== Messaging4Transport Architecture
The ActiveMQ client implementation for AMQP hides the implementation behind the Java Message Service (JMS) API. ActiveMQ further depends on https://qpid.apache.org/[QPid] for its AMQP clients and broker. Hence, QPid and JMS bundles are introduced as the dependencies to the odl-messaging4transport feature.


ActiveMQ also has a http://stomp.github.io/[Simple (or Streaming) Text Oriented Message Protocol (STOMP)] implementation in the same way through StompJmsConnectionFactory, a JMS mapping and interface for STOMP. http://activemq.apache.org/openwire.html[OpenWire] is a cross-language wire protocol from ActiveMQ. The OpenWire implementation of ActiveMQ follows the similar strategy and implementation. With almost no changes to the architecture, and minimal code changes, publishing to STOMP or OpenWire broker implementations (such as ActiveMQ) should be possible, from OpenDaylight/MD-SAL with the odl-messaging4transport feature.


There is also an http://mqtt.org/[MQTT] implementation in ActiveMQ, which is slightly different in the implementation from AMQP, STOMP, and OpenWire implementations, and does not seem to depend on JMS.


=== Key APIs and Interfaces
Messaging4Transport consists of the messaging4transport feature which offers an AMQP message-oriented middleware northbound to MD-SAL, as an alternative to the traditional RESTCONF northbound.


=== Use Cases

Multiple research and industrial https://wiki.opendaylight.org/view/Messaging4Transport:Use_Cases[use cases] of Messaging4Transport has been proposed. Since Messaging4Transport is still in its early stages, many of these use cases are still proof of concepts and novel research publications.

* Software-Defined Buildings

+ http://www.navigators.di.fc.ul.pt/w2/img_auth.php/9/90/Navtalk20151120_Kathiravelu.paper.pdf[Cassowary] is a middleware platform for context-aware smart buildings with software-defined sensor networks, by leveraging OpenDaylight Messaging4Transport. Messaging4Transport architecture has been extended by Cassowary approach to create a software-defined sensor and actuator network for smart buildings.

* Software-Defined Community Networks

+ http://www.gsd.inesc-id.pt/~pradeeban/SDS2016/IEEE_SDS_16_CHIEF.pdf[CHIEF] is a controller farm for clouds of software-defined community networks. CHIEF leverages the message-oriented middleware and OpenDaylight Messaging4Transport architecture to create a huge deployment of SDN for community clouds.