== YANG-PUSH
This section describes how to use the YANG-PUSH feature in OpenDaylight
and contains contains configuration, administration, and management
sections for the feature.

=== Overview
TBD: An overview of the YANG-PUSH feature and the use case and the
audience who will use the feature.

=== YANG-PUSH Architecture
TBD: Information about YANG-PUSH components and how they work together.
Also include information about how the feature integrates with
OpenDaylight.

=== YANG-PUSH Catalog
The NF Catalog contains metadata describing a NF.

==== Configuring YANG-PUSH Catalog
TBD: Describe how to configure YANG-PUSH Catalog after installation.

==== Administering YANG-PUSH Catalog
TBD: Include related command reference or operations
for using YANG-PUSH Catalog.

=== YANG-PUSH Workload Manager
The Workload Manager defines RPCs to manage instances.

=== Configuring YANG-PUSH Workload Manager
TBD: Describe how to configure YANG-PUSH Workload Manager after installation.

=== Administering YANG-PUSH Workload Manager
TBD: Include related command reference or operations
for using YANG-PUSH Workload Manager.

=== Tutorials
Below are tutorials for YANG-PUSH.

==== Using YANG-PUSH Catalog
TBD: State the purpose of tutorial

===== Overview
TBD: An overview of the YANG-PUSH Catalog tutorial

===== Prerequisites
TBD: Provide any prerequisite information, assumed knowledge, or environment
required to execute the use case.

===== Target Environment
TBD: Include any topology requirement for the use case.

===== Instructions
TBD: Step by step procedure for using YANG-PUSH Catalog.

==== Using YANG-PUSH Workload Manager
TBD: State the purpose of tutorial

===== Overview
TBD: An overview of the YANG-PUSH Workload Manager tutorial

===== Prerequisites
TBD: Provide any prerequisite information, assumed knowledge, or environment
required to execute the use case.

===== Target Environment
TBD: Include any topology requirement for the use case.

===== Instructions
TBD: Step by step procedure for using YANG-PUSH Workload Manager.
