== OVSDB Openstack Installation Guide

=== Overview
This guide is geared towards installing OpenDaylight to use the OVSDB project to provide Neutron support for OpenStack.

Open vSwitch (OVS) is generally accepted as the unofficial standard for Virtual Switching in the Open hypervisor based solutions.
For information on OVS, see http://openvswitch.org/[Open vSwitch].

With OpenStack within the SDN context, controllers and applications interact using two channels: OpenFlow and OVSDB. OpenFlow addresses the forwarding-side of the OVS functionality. OVSDB, on the other hand, addresses the management-plane.
A simple and concise overview of Open Virtual Switch Database (OVSDB) is available at: http://networkstatic.net/getting-started-ovsdb/

=== Pre Requisites for Installing OVSDB Openstack
* JRE 1.7+
* A distribution of OpenDaylight

=== Preparing for Installation
. Download a copy of the latest OpenDaylight release in a Pre-Build archive of your choosing.
http://www.opendaylight.org/software/downloads[Download OpenDaylight]


=== Installing OVSDB Openstack
. Extract the OpenDaylight distribution somewhere.
. Navigate to the /bin/ directory
. Execute the karaf binary file, that should bring up the OpenDaylight console
. Install the required features with these commands:
feature:install odl-ovsdb-openstack

===== Sample output from the Karaf console
----
opendaylight-user@root>feature:list | grep -i ovsdb
odl-ovsdb-all                    | 1.0.0-SNAPSHOT      |           | ovsdb-1.0.0-SNAPSHOT
OpenDaylight :: OVSDB :: all
odl-ovsdb-library                | 1.0.0-SNAPSHOT      | x         | ovsdb-1.0.0-SNAPSHOT
OVSDB :: Library
odl-ovsdb-schema-openvswitch     | 1.0.0-SNAPSHOT      | x         | ovsdb-1.0.0-SNAPSHOT
OVSDB :: Schema :: Open_vSwitch
odl-ovsdb-schema-hardwarevtep    | 1.0.0-SNAPSHOT      | x         | ovsdb-1.0.0-SNAPSHOT
OVSDB :: Schema :: hardware_vtep
odl-ovsdb-plugin                 | 1.0.0-SNAPSHOT      | x         | ovsdb-1.0.0-SNAPSHOT
OpenDaylight :: OVSDB :: Plugin
odl-ovsdb-northbound             | 0.6.0-SNAPSHOT      |           | ovsdb-1.0.0-SNAPSHOT
OpenDaylight :: OVSDB :: Northbound
odl-ovsdb-openstack              | 1.0.0-SNAPSHOT      | x         | ovsdb-1.0.0-SNAPSHOT
OpenDaylight :: OVSDB :: OpenStack Network Virtual
odl-ovsdb-ovssfc                 | 0.0.1-SNAPSHOT      |           | ovsdb-0.0.1-SNAPSHOT
OpenDaylight :: OVSDB :: OVS Service Function Chai
odl-openflow-nxm-extensions      | 0.0.3-SNAPSHOT      | x         | ovsdb-0.0.3-SNAPSHOT
OpenDaylight :: Openflow :: Nicira Extensions
----

=== Verifying your Installation
To verify that the installation was successful, use the log:display command in karaf and check that there are no errors
logs relating to odl-ovsdb-openstack.

==== Troubleshooting
There are no easy way to troubleshoot an installation of odl-ovsdb-openstack. Perhaps a combination of
log:display | grep -i ovsdb in karaf, Open vSwitch commands (ovs-vsdctl) and openstack logs will be useful but will not
explain everything.

=== Upgrading From a Previous Release
Upgrading from upstream

Upgrading from release

=== Uninstalling OVSDB Openstack
. Shutdown the karaf instance: system:shutdown
. Remove what is in the /data folder of the OpenDaylight Distribution.
