*Table of Contents*

*Introduction 
................??............................................................................................  
xx*

*Running the OF-CONFIG project 
............................................................................  
xx Support in Opendaylight 
...........................................................................................  
xx*

*The APIs in OFCONF
project.......................................................................................  
xx*

Introduction
------------

OF-CONFIG defines an OpenFlow switch as an abstraction called an
OpenFlow Logical Switch. The OF-CONFIG protocol enables configuration of
essential artifacts of an OpenFlow Logical Switch so that an OpenFlow
controller can communicate and control the OpenFlow Logical switch via
the OpenFlow protocol. OF-CONFIG introduces an operating context for one
or more OpenFlow data paths called an OpenFlow Capable Switch for one or
more switches. An OpenFlow Capable Switch is intended to be equivalent
to an actual physical or virtual network element (e.g. an Ethernet
switch) which is hosting one or more OpenFlow data paths by partitioning
a set of OpenFlow related resources such as ports and queues among the
hosted OpenFlow data paths. The OF-CONFIG protocol enables dynamic
association of the OpenFlow related resources of an OpenFlow Capable
Switch with specific OpenFlow Logical Switches which are being hosted on
the OpenFlow Capable Switch. OF­CONFIG does not specify or report how
the partitioning of resources on an OpenFlow Capable Switch is achieved.
OF-CONFIG assumes that resources such as ports and queues are
partitioned amongst multiple OpenFlow Logical Switches such that each
OpenFlow Logical Switch can assume full control over the resources that
is assigned to it.

Running the OF-CONFIG project
-----------------------------

*Check out the project using git*

git clone https://git.opendaylight.org/gerrit/of-config

The above command will create a directory called "of-config " with the
project.

*Run the distribution*

To run the OF-CONFIG, you can use the following command:

\1) Run the controller as below:

./distribution/karaf/target/assembly/bin/karaf

\2) start the of-conf feature as below:

feature:install odl-of-config-all

Support in Opendaylight
-----------------------

*Compatible with NETCONF*

1.       The NETCONF project is adopted to implement the OF-switch??s
accessing to the controller via RESTCONF interfaces, the URL and
commands are shown as below:

_URL:_http://localhost:8181/restconf/config/network-topology:network-topology/topology/topology-netconf/node/controller-config/yang-ext:mount/config:modules[http://localhost:8181/restconf/config/network-topology:network-topology/topology/topology-netconf/node/controller-config/yang-ext:mount/config:modules]__

 

"Content-Type" and "Accept" header attributes set to application/xml

<module xmlns="urn:opendaylight:params:xml:ns:yang:controller:config">

   <type
xmlns:prefix="urn:opendaylight:params:xml:ns:yang:controller:md:sal:connector:netconf">prefix:sal-netconf-connector</type>

   <name>testtool</name>

   <address
xmlns="urn:opendaylight:params:xml:ns:yang:controller:md:sal:connector:netconf">10.74.151.67</address>

   <port
xmlns="urn:opendaylight:params:xml:ns:yang:controller:md:sal:connector:netconf">830</port>

   <username
xmlns="urn:opendaylight:params:xml:ns:yang:controller:md:sal:connector:netconf">mininet</username>

   <password
xmlns="urn:opendaylight:params:xml:ns:yang:controller:md:sal:connector:netconf">mininet</password>

   <tcp-only
xmlns="urn:opendaylight:params:xml:ns:yang:controller:md:sal:connector:netconf">false</tcp-only>

   <event-executor
xmlns="urn:opendaylight:params:xml:ns:yang:controller:md:sal:connector:netconf">

     <type
xmlns:prefix="urn:opendaylight:params:xml:ns:yang:controller:netty">prefix:netty-event-executor</type>

     <name>global-event-executor</name>

   </event-executor>

   <binding-registry
xmlns="urn:opendaylight:params:xml:ns:yang:controller:md:sal:connector:netconf">

     <type
xmlns:prefix="urn:opendaylight:params:xml:ns:yang:controller:md:sal:binding">prefix:binding-broker-osgi-registry</type>

     <name>binding-osgi-broker</name>

   </binding-registry>

   <dom-registry
xmlns="urn:opendaylight:params:xml:ns:yang:controller:md:sal:connector:netconf">

     <type
xmlns:prefix="urn:opendaylight:params:xml:ns:yang:controller:md:sal:dom">prefix:dom-broker-osgi-registry</type>

     <name>dom-broker</name>

   </dom-registry>

   <client-dispatcher
xmlns="urn:opendaylight:params:xml:ns:yang:controller:md:sal:connector:netconf">

     <type
xmlns:prefix="urn:opendaylight:params:xml:ns:yang:controller:config:netconf">prefix:netconf-client-dispatcher</type>

     <name>global-netconf-dispatcher</name>

   </client-dispatcher>

   <processing-executor
xmlns="urn:opendaylight:params:xml:ns:yang:controller:md:sal:connector:netconf">

     <type
xmlns:prefix="urn:opendaylight:params:xml:ns:yang:controller:threadpool">prefix:threadpool</type>

     <name>global-netconf-processing-executor</name>

   </processing-executor>

 </module>

 

2.       NETCONF establishes the connections with capable switches using
the parameters in the previous step. The NETCONF also gets the
information of whether the of-switch supporting the NETCONF or not
during the signal handshaking. The information will be stored in the
NETCONF-TOPO as prosperity of a node as below.

 

[width="100%",cols="<100%",]
|=========================
|[multiblock cell omitted]
|=========================

 

3.       OF-CONFIG can be aware of the switch??s accessing and leaving
by monitoring the data changes in the NETCONF TOPO. For the detailed
information it can be refered to :

https://git.opendaylight.org/gerrit/gitweb?p=of-config.git;a=blob_plain;f=southbound/southbound-impl/src/main/java/org/opendaylight/ofconfig/southbound/impl/OdlOfconfigApiServiceImpl.java;hb=refs/heads/master[_https://git.opendaylight.org/gerrit/gitweb?p=of-config.git;a=blob_plain;f=southbound/southbound-impl/src/main/java/org/opendaylight/ofconfig/southbound/impl/OdlOfconfigApiServiceImpl.java;hb=refs/heads/master_]__

* *

*The establishment of OF-CONF TOPO*

Firstly, OF-CONFIG will check whether the newly accessed switch supports
OF-CONFIG or not by querying the NETCONF.

\1) During the NETCONF connection??s establishment, the NETCONF and the
switches will exchange the their capabilities via the ??hello??
message..

\2) OF-CONFIG gets the connection information between the NETCONF and
switches by monitoring the data changes via the interface of
DataChangeListener.

\3) After the NETCONF connection established, the OF-CONFIG module will
check whether OF-CONFIG capability is in the switch??s capabilities list
which is got in step 1).

\4) If the result of step 3 is yes, the OF-CONFIG will call the
following processing steps to create the TOPO database.

 

For the detailed information it can be referred to:

https://git.opendaylight.org/gerrit/gitweb?p=of-config.git;a=blob_plain;f=southbound/southbound-impl/src/main/java/org/opendaylight/ofconfig/southbound/impl/listener/OfconfigListenerHelper.java;hb=refs/heads/master[_https://git.opendaylight.org/gerrit/gitweb?p=of-config.git;a=blob_plain;f=southbound/southbound-impl/src/main/java/org/opendaylight/ofconfig/southbound/impl/listener/OfconfigListenerHelper.java;hb=refs/heads/master_]__

 

Secondly, the capable switch node and logical switch node are added in
the OF-CONFIG TOPO if the switch supports OF-CONFIG.

OF-CONFIG??s topology compromise: Capable Switch topology(underlay) and
logical Switch topology(overlay). Both of them are enhanced(augment) on

/topo:network-topology/topo:topology/topo:node.

The NETCONF will add the nodes in the Topology via the path
of                                                                    
??/topo:network-topology/topo:topology/topo:node?? if it gets the
configuration information of the switches.

 

For the detailed information it can be referred to :

https://git.opendaylight.org/gerrit/gitweb?p=of-config.git;a=blob;f=southbound/southbound-api/src/main/yang/odl-ofconfig-topology.yang;h=dbdaec46ee59da3791386011f571d7434dd1e416;hb=refs/heads/master[_https://git.opendaylight.org/gerrit/gitweb?p=of-config.git;a=blob;f=southbound/southbound-api/src/main/yang/odl-ofconfig-topology.yang;h=dbdaec46ee59da3791386011f571d7434dd1e416;hb=refs/heads/master_]__

The APIs in OFCONF project
--------------------------

The OF-CONFIG provides the APIs listed in the table as below..

[width="99%",cols="<16%,<14%,<14%,<14%,<14%,<14%,<14%",]
|=======================================================================
|*Short Name* |*Description* |*Type (at M2)* |*Type (at M3)* |*Type
(release)* |*Contract* |*Supporting Code*

|sync-conf-ocs |Synchronize the configuration with Openflow Capable
Switch |Tentative |Provisional |[multiblock cell omitted]
|[multiblock cell omitted] |[multiblock cell omitted]

|modify-controller-connection |Modify the configuration of controller
connection in Openflow Logic Switch |[multiblock cell omitted]
|Provisional |[multiblock cell omitted] |[multiblock cell omitted]
|[multiblock cell omitted]

|create-tls |Create TLS tuunel for Openflow Logic Switch and controller,
and configure authentication certificate |[multiblock cell omitted]
|Provisional |[multiblock cell omitted] |[multiblock cell omitted]
|[multiblock cell omitted]

|opt-flowtable |Operate flow table of Openflow Logic Switch
|[multiblock cell omitted] |Provisional |[multiblock cell omitted]
|[multiblock cell omitted] |[multiblock cell omitted]

|config-tunnel |Configure tunnel in Openflow Logic Switch
|[multiblock cell omitted] |Provisional |[multiblock cell omitted]
|[multiblock cell omitted] |[multiblock cell omitted]

|config-port |Configure port and queue in Openflow Capable Switch
|[multiblock cell omitted] |Provisional |[multiblock cell omitted]
|[multiblock cell omitted] |[multiblock cell omitted]

|config-ols-basic |Configure some basic item in Openflow Logic Switch,
such as dpid and lost-connection-behavior |[multiblock cell omitted]
|Provisional |[multiblock cell omitted] |[multiblock cell omitted]
|[multiblock cell omitted]
|=======================================================================

 

For the detailed implementation of the APIs can refer to :

https://git.opendaylight.org/gerrit/gitweb?p=of-config.git;a=blob;f=southbound/southbound-api/src/main/yang/odl-ofconfig-base-api.yang;h=302c9b1f5bfdb677e207c316ac2e248633ed958b;hb=refs/heads/master[_https://git.opendaylight.org/gerrit/gitweb?p=of-config.git;a=blob;f=southbound/southbound-api/src/main/yang/odl-ofconfig-base-api.yang;h=302c9b1f5bfdb677e207c316ac2e248633ed958b;hb=refs/heads/master_]__

 
