=== Service Function Grouping and Load Balancing Developer Guide

==== Overview
SFC Load-Balancing feature implements load balancing of Service Functions, rather than a one-to-one mapping between Service-Function-Forwarder and Service-Function. 

==== Load Balancing Architecture
Service-Function-Groups (SFG) can replace Service-Functions (SF) in the Rendered-Path model. 
A Service-Path can only be defined using SFG's or SF's, but not a combination of both.

Relevant objects in the YANG model are as follows:
1. Service-Function-Group-Algorithm:

	Service-Function-Group-Algorithms {
		Service-Function-Group-Algorithm {
			String name
			String type
		}
	}

	Available types: ALL, SELECT, INDIRECT, FAST_FAILURE
	
2. Service-Function-Group:

	Service-Function-Groups {
		Service-Function-Group {
			String name
			String serviceFunctionGroupAlgorithmName
			String type
			String groupId
			Service-Function-Group-Element {
				String service-function-name
				int index
			}
		}
	}

3. ServiceFunctionHop: holds a reference to a name of SFG (or SF)
 
==== Key APIs and Interfaces
This feature enhances the existing SFC API.

REST API commands include:
For Service Function Group (SFG): read existing SFG, write new SFG, delete existing SFG, add Service Function (SF) to SFG, and delete SF from SFG
For Service Function Group Algorithm (SFG-Alg): read, write, delete

Bundle providing the REST API: sfc-sb-rest
Service Function Groups and Algorithms are defined in: sfc-sfg and sfc-sfg-alg
Relevant JAVA API: SfcProviderServiceFunctionGroupAPI, SfcProviderServiceFunctionGroupAlgAPI