=== Service Function Selection Algorithm Developer Guide

==== Overview
The service function selection framework supports at least four algorithms (e.g. Random, Round Robin, Load Balancing, Shortest Path) to choose the most appropriate service function when instantiating the RSP. In addition, it is an extensible framework that allows 3rd party scheduler with optimized algorithms to be plugged in.

==== Service Function Selection Algorithm Architecture
Provide information about Service Function Selection Algorithm components and how they work together.
Also include information about how the Service Function Selection Algorithm integrates withOpenDaylight.

==== Key APIs and Interfaces

===== RESTConf
RESTConf Northbound SFC API provides GUI/REST interactions for choosing the service function selection algorithm.

===== MD-SAL
MD-SAL Datastore provides all supported service function selection algorithms, and provides APIs to enable one of the provided service function selection algorithm.

==== API Reference Documentation
Provide links to JavaDoc, REST API documentation, etc.
