== ODL-SDNi User Guide

=== Introduction
This user guide will help to setup the ODL-SDNi application.

=== Components
SDNiAggregator , SDNi API  and SDNiWrapper  are the three components in ODL-SDNi App  

 * SDNiAggregator: Connects with the MD-SAL datastore of controller to get the topology and Quality of Service (QoS) related data.
 * SDNi API: It is a Northbound REST API , which gives the required information by quering SDNiAggregator through RESTCONF.
 * SDNiWrapper: This component uses the SDNi instances of OpenDaylight Aggregator and gathers the information required to be shared among controllers.

=== Troubleshooting
To work with multiple controllers, you must change the configuration in custom.properties file. For example change the listening port of two controllers to 6653 in /root/sdninterfaceapp/karaf/target/assembly/etc/custom.properties (i.e., of.listenPort=6653).

.OpenFlow related system parameters
TCP port on which the controller is listening (default 6633) of.listenPort=6653

