== SXP User Guide

=== Overview
SXP project is an effort to enhance Opendaylight platform with IP-SGT bindings that can be learned from connected SXP-aware network nodes. Current implementation supports SXP protocol version 4 according to the Smith, Kandula - SXP IETF I-D. All protocol legacy versions 1-3 are supported as well. Additionally, version 4 adds bidirectional connection type as an extension of a unidirectional one.

=== SXP Architecture
The SXP Server manages all connected clients in separate threads and a common SXP Protocol agreement is used between connected peers. Each SXP network peer is modelled with its pertaining class, i.e. SXP Server represents the SXP Speaker, SXP Listener the Client. The server program creates the ServerSocket object on a specified port and waits until a client starts up and requests connect on the IP address and port of the server. The client program opens a Socket that is connected to the server running on the specified host IP address and port.

SXP Listener maintains connection with its speaker peer. From an opened channel pipeline, all incoming SXP messages are processed by various handlers. Message must be decoded, parsed and validated.

SXP Speaker is a counterpart to the SXP Listener. It maintains a connection with its listener peer and sends composed messages.

SXP Binding Handler extracts the IP-SGT binding from a message and pulls it into the SXP-Database. If an error is detected during the IP-SGT extraction, an appropriate error code and sub-code is selected and an error message is sent back to the connected peer. All transitive messages are routed directly to the output queue of SXP Binding Dispatcher.

IP-SGT Manager handles bindings from multiple connections. If a new data has been added into or deleted from the SXP-Database, or binding’s contributor change is detected, the manager performs an arbitration process above the SXP-Database to resolve the binding duplicity and prevent possible information loops. Finally, it updates the IP-SGT-Master database that consists only of valid and unique bindings, i.e. a single binding per IP address.

The IP-SGT Manager also contains RPCs that can be used by other ODL plugins, or by UI REST calls, to add, update or to delete bindings in or from the Master database.

SXP Binding Dispatcher represents a selector that will solve how many data from the Master database will be sent and when. It is responsible for message content composition based on maximum message length. 

=== Configuring SXP
The OpenDaylight Karaf distribution comes pre-configured with baseline SXP
configuration.

- *22-sxp-controller-one-node.xml* (defines the basic parameters)

=== Administering or Managing SXP
Byt RPC:
Add Connection, Delete Connection, Add Binding Entry,
Update Binding Entry, Delete Binding Entry,
Get Node Bindings, Get Binding SGTs, Get Connections

===== Overview
Cisco has a wide installed base of network devices supporting SXP. By including SXP in ODL, the binding of policy groups to IP addresses can be made available for possible further processing to a wide range of devices, and applications running on ODL. The range of applications that would be enabled is extensive. Here are just a few of them:

ODL based applications can take advantage of the IP-SGT binding information. For example, access control can be defined by an operator in terms of policy groups, while ODL can configure access control lists on network elements using IP addresses, i. e., existing technology.

Interoperability between different vendors. Vendors have different policy systems. Knowing the IP-SGT binding for Cisco makes it possible to maintain policy groups between Cisco and other vendors.

ODL can aggregate the binding information from many devices and communicate it to a network element. For example, a firewall can use the IP-SGT binding information to know how to handle IPs based on the group-based ACLs it has set. But to do this with SXP alone, the firewall has to maintain a large number of network connections to get the binding information. This incurs heavy overhead costs to maintain all of the SXP peering and protocol information. ODL can aggregate the IP-group information so that the firewall need only connect to ODL. By moving the information flow outside of the network elements to a centralized position, we reduce the overhead of the CPU consumption on the enforcement element. This is a huge savings - it allows the enforcement point to only have to make one connection rather than thousands, so it can concentrate on its primary job of forwarding and enforcing.

ODL can relay the binding information from one network element to others. Changes in group membership can be propagated more readily through a centralized model. For example, in a security application a particular host (e. g., user or IP Address) may be found to be acting suspiciously or violating established security policies. The defined response is to put the host into a different source group for remediation actions such as a lower Quality of Service, restricted access to critical servers, or special routing conditions to ensure deeper security enforcement (e. g., redirecting the host’s traffic through an IPS with very restrictive policies). Updated group membership for this host needs to be communicated to multiple network elements as soon as possible; a very efficient and effective method of propagation can be performed using ODL as a centralized point for relaying the information.

Although the IP-SGT binding is only one specific piece of information, and although SXP is implemented widely in a single vendor’s equipment, bringing the ability of ODL to process and distribute the bindings, is a very specific immediate useful implementation of policy groups. It would go a long way to develop both the usefulness of ODL and of policy groups. 

