=== Description of clustering singleton approach in plugin

==== Change against using EOS service listener

In this new clustering singleton approach plugin uses API from MD-SAL project. SingletonClusteringService which comes with three methods.

    instantiateServiceInstance()
    closeServiceInstance()
    getIdentifier()

This service has to be registered to a SingletonClusteringServiceProvider from MD-SAL which take care if mastership is changed in cluster environment. Plugin don't need to take care EOS change ownership messages and don't need to take care about double candidate approach entity registrations.

First method in SingletonClusteringService is being called when the cluster node becomes a MASTER. Second is being called when status changes to SLAVE or device is disconnected from cluster. Last method plugins returns NodeId as ServiceGroupIdentifier
Startup after device is connected

On the start up the plugin we need to initialize first four managers for each working area providing information and services

[source, java]
----
    Device manager
    RPC manager
    Role manager
    Statistics manager
----

After connection the device the listener Device manager get the event and start up to creating the context for this connection.
Startup after device connection

Lifecycle conductor doesn't exist anymore, we don't need to conduct the services. They are manager by SinlgetonClusteringServiceProvider from MD-SAL project. So in startup we simply create a instance of LifecycleService and register all contexts into it.
Role change

Plugin is no more registered as EOS listener therefore don't need and can't to respond on EOS change ownership changes.

===== Service start

Services start asynchronously but the start is managed by LifecycleService. If something goes wrong LifecycleService stop starting services in context and this speed up the reconnect process. But the services haven't changed and plugin need to start all this:

*    Activating transaction chain manager
*    Initial gathering of device statistics
*    Initial submit to DS
*    Sending role MASTER to device
*    RPC services registration
*    Statistics gathering start

===== Service stop

If closeServiceInstance occurred plugin just simply try to store all unsubmitted transactions and close the transaction chain manager, stop RPC services, stop Statistics gathering and after that all unregister txEntity from EOS. 