== Usecplugin-OpenFlow User Guide
The Usecplugin-OpenFlow User Guide contains information about configuration, administration,
management, using and troubleshooting the feature.

=== Overview
Usecplugin-OpenFlow collects information about potential OpenFlow Packet_In attacks to Opendaylight.
A threshold (water mark) can be set for the Packet_In rate which when breached will trigger Packet_In message
information collection. 

=== Usecplugin Architecture
Usecplugin listens on OpenFlow southbound interface for Packet_In messages. When the rate of Packet_In
breaches the water mark the application parses the message for header information which is subsequently
stored in Yang Data Store and a log file. Usecplugin has PacketHandler class that implements the PacketProcessing
interface to override the OnPacketReceived notification by which the application is notified of Packet_In messages.

=== Configuring Usecplugin-OpenFlow

Not Applicable

=== Administering or Managing Usecplugin-OpenFlow
Use REST API in the following format for entering global IP addresses.

Http POST command to http://

=== Tutorials
Will provided later.
