== Messaging4Transport User Guide

=== Overview
The OpenDaylight controller is based on an MD-SAL allows the modeling of data, RPCs, and notifications. Because of this model basis, adding new northbound bindings to the controller is simple, and everything modeled becomes exposed automatically. Currently the MD-SAL has RESTCONF northbound bindings, while more bindings such as AMQP and XMPP can easily be implemented and integrated. Messaging4Transport attempts to build more northbound interfaces to MD-SAL, with message-oriented middleware protocols. Messaging4Transport Beryllium offers an AMQP northbound to MD-SAL. 

=== Architecture
http://www.amqp.org[Advanced Message Queuing Protocol (AMQP)] is an open standard application layer protocol for message-oriented middleware. Messaging4Transport adds AMQP bindings to the MD-SAL, which would automatically make all MD-SAL APIs available via that mechanism. Messaging4Transport is built as an independent Karaf feature, that exposes the MD-SAL data tree, RPCs, and notifications via AMQP, when installed. While AMQP is the focus for the Beryllium Release, other message-oriented transport protocols will be considered for future releases.

A message broker internal or external to OpenDaylight receives the messages that are published by the MD-SAL, and sends them to the subscribers. Hence, the broker functions as an intermediary in messages from the controller to the listeners, and vice versa. ActiveMQ has been chosen as the default external broker in the Messaging4Transport Beryllium.

==== Installing Karaf Features

Install Messaging4Transport by using the karaf console.

 feature:install odl-mdsal-all odl-messaging4transport-api odl-messaging4transport


==== ActiveMQ Integration with Karaf
ActiveMQ broker can be integrated into the Karaf environment. The http://activemq.apache.org/osgi-integration.html[instructions page] is for Karaf 2.x. Please see the http://karaf.apache.org/manual/latest/update-notes.html[Karaf updates page]. Since OpenDaylight Helium is built on Karaf 3.x, the instructions are given below to install and activate ActiveMQ OSGi bundle into Karaf. 

* Installing ActiveMQ in Karaf
 feature:repo-add activemq 5.9.0

 feature:install activemq-broker


* Installing hawtio in http://hawt.io/getstarted/index.html[Karaf]

hawtio provides a user-friendly web user interface, that can be installed optionally to work with the project.

 feature:repo-add hawtio 1.4.51

 feature:install hawtio



=== Administering or Managing Messaging4Transport

The broker can be a stand-alone or a Karaf-based broker integrated into OpenDaylight. Just install the bundles as shown below for Karaf based integration. In such a case, broker will start with OpenDaylight. The publisher publishes the data tree. At least a dummy listener should be started before the publisher to receive the published messages.


You may further configure the broker by modifying the ActiveMQ configuration file in ODL_INSTALLATION_DIR/karaf/target/assembly/etc/org.apache.activemq.server-default.cfg


Make sure to set the transport connections in karaf/target/assembly/etc/activemq.xml, which is set by default in ActiveMQ stand-alone implementation; but not in the Karaf implementation.

It is suggested to limit concurrent connections to just 1000. However, probably we will need more concurrency, based on the requirements. Setting it to 100,000 for now.

 <transportConnectors>
 <!-- DOS protection, limit concurrent connections to 1000 and frame size to 100MB -->
 <!-- Uncomment whatever necessary. -->
 <transportConnector name="openwire" uri="tcp://0.0.0.0:61616?maximumConnections=100000&amp;wireFormat.maxFrameSize=104857600"/>
 <transportConnector name="amqp" uri="amqp://0.0.0.0:5672?maximumConnections=100000&amp;wireFormat.maxFrameSize=104857600"/>
 <!--transportConnector name="stomp" uri="stomp://0.0.0.0:61613?maximumConnections=100000&amp;wireFormat.maxFrameSize=104857600"/ -->
 <!--transportConnector name="mqtt" uri="mqtt://0.0.0.0:1883?maximumConnections=100000&amp;wireFormat.maxFrameSize=104857600"/ -->
 <!--transportConnector name="ws" uri="ws://0.0.0.0:61614?maximumConnections=100000&amp;wireFormat.maxFrameSize=104857600"/ -->
 </transportConnectors>


You may need to install/re-install the bundle after that and restart the container for the changes to take effort.

The MD-SAL will be the publisher that publishes the MD-SAL data tree, RPCs, and notifications via AMQP. The listener can be any consumer that consumes the data tree and the other data published by MD-SAL via the AMQP binding.

Once configured, the ActiveMQ console can be accessed from the http://localhost:8181/hawtio/[hawtio web console] with the credentials karaf/karaf.

Messaging4Transport can hence be configured to publish MD-SAL notifications to an external AMQP listener application through the broker. A simple listener application is included in the org.opendaylight.messaging4transport.sample package.