== Topology Processing Framework Developer Guide

=== Overview
Purpose of Topology Processing Framework is to allow developers to agregate and filter topologies according to defined correlations. It also provides functionality, which you can use to make your own topology model rendering (translation from one model to another, for example from inventory to pure network-topology).

=== Architecture
include::odl-topoprocessing-architecture-dev.adoc[]

=== Aggregation and Filtration
include::odl-topoprocessing-aggregation-filtration-dev.adoc[]

=== Link Computation
include::odl-topoprocessing-link-computation-dev.adoc[]

=== Wrapper, RPC Republishing, Writing Mechanism
include::odl-topoprocessing-wrapper-rpc-writing-dev.adoc[]

=== Topology Rendering Guide - Inventory Rendering
include::odl-topoprocessing-inventory-rendering-dev.adoc[]

=== Key APIs and Interfaces
Basic Provider class is TopoProcessingProvider which provides startup and shutdown
methods. Otherwise the framework communicates via requests and outputs stored
in DataStores.

=== API Reference Documentation
You can find API examples in https://wiki.opendaylight.org/view/Topology_Processing_Framework:Developer_Guide:End_to_End_Example[this wiki]
