== ALTO Developer Guide ==

=== Overview ===
This guide is not only for those who want to using the ALTO feature in Open
Daylight to help improve their own functionalities, but also for those who
want to enhance the ALTO services with some customized implementations.

In this document we will be mainly discussing 1) how to add alto projects as
dependencies, 2) how to put/fetch data from ALTO, and 3) how to use customized
service implementations.

=== Add ALTO Projects as Dependencies ===

Most ALTO packages can be added as dependencies in your own Maven projects by
putting the following code in the __pom.xml__ file.

    <dependency>
    	<groupId>org.opendaylight.alto</groupId>
        <artifactId>${THE_NAME_OF_THE_PACKAGE_YOU_NEED}</artifactId>
        <version>${ALTO_VERSION}</version>
    </dependency>

The current stable version for ALTO is `0.1.0-SNAPSHOT`.

=== Put/Fetch data from ALTO ===

==== Using RESTful API ====
There are two kinds of RESTful APIs for ALTO: the one provided by
`alto-northbound` which follows the formats defined in
link:https://tools.ietf.org/html/rfc7285[RFC 7285], and the one provided by
RESTCONF whose format is defined by the YANG model proposed in
link:https://tools.ietf.org/html/draft-shi-alto-yang-model-03[this draft]

One way to get the URLs for the resources from `alto-northbound` is to visit
the IRD service first where there is a `uri` field for every entry. However
IRD service is not yet implemented so currently the developers have to construct
the URLs themselves. The base URL is `/controller/nb/v2/alto/`, here is a list
of the specific paths defined in `AltoNorthbound.java` in `alto-northbound`
using Jersey `@Path` annotation:

. `/ird/{rid}`: the path to access __IRD__ services;
. `/networkmap/{rid}[/{tag}]`: the path to access __Network Map__ services;
. `/costmap/{rid}[/{tag}[/{mode}/{metric}]]`: the path to access __Cost Map__
services;
. `/filtered/networkmap/{rid}[/{tag}]`: the path to access __Filtered Network Map__
services;
. `/filtered/costmap/{rid}[/{tag}]`: the path to access __Filtered Cost Map__
services;
. `/endpointprop/lookup/{rid}[/{tag}]`: the path to access __Endpoint Property__
services;
. `/endpointcost/lookup/{rid}[/{tag}]`: the path to access __Endpoint Cost__
services.

NOTE: The segments in brackets are optional.

If you want to fetch the data using RESTCONF, it is highly recommended to take a
look at link:http://localhost:8181/apidoc/explorer/index.html[the `apidoc` page]
after installing the `alto-model` feature in karaf.

It is also worth pointing out that `alto-northbound` only supports `GET` and
`POST` operations so it is impossible to manipulate the data through its RESTful
APIs. To modify the data, you have to use `PUT` and `DELETE` methods with RESTCONF.

NOTE: The current implementation is using the `configuration` data store and
that's why developers can modify the data directly through RESTCONF. In the
future this approach might be disabled in the core packages of ALTO but may
still be avaiable as an extension.

==== Using AD-SAL ====
In package `service-api-rfc7285` five interfaces are defined, you can use the
`ServiceHelper` to get the instance and call the corresponding methods to get
the results. `alto-northbound` is using this method to fetch data.

==== Using MD-SAL ====
You can also fetch data from the data store directly. It is a little more
complex than the other methods but also the most straight-forward way.

First you must get the access to the data store. That wouldn't be hard if you
are developing a MD-SAL application: you only need to register your module with
a data broker.

Then an `InstanceIdentifier` must be created. Here is an example of how to build
an `InstanceIdentifier` for a __network map__:

    import org.opendaylight.yang.gen.v1.urn.opendaylight.alto.rev150404.Resources;
    import org.opendaylight.yang.gen.v1.urn.opendaylight.alto.rev150404.resources.NetworkMaps;
    import org.opendaylight.yang.gen.v1.urn.opendaylight.alto.rev150404.resources.network.maps.NetworkMap;
    import org.opendaylight.yang.gen.v1.urn.opendaylight.alto.rev150404.resources.network.maps.NetworkMapKey;
    ...
    protected InstanceIdentifier<NetworkMap> getNetworkMapIID(String resource_id) {
        NetworkMapKey key = new NetworkMapKey(ResourceId.getDefaultInstance(resource_id));
        InstanceIdentifier<NetworkMap> iid = InstanceIdentifier.builder(Resources.class)
                                                               .child(NetworkMaps.class)
                                                               .child(NetworkMap.class, key)
                                                               .build();
        return iid;
    }

With the `InstanceIdentifier` you can use `ReadOnlyTransaction`,
`WriteTransaction` and `ReadWriteTransaction` to manipulate the data
accordingly. `simple-impl`, which provides some of the AD-SAL APIs metioned
above, is using this method to get data from the data store and then convert
them into RFC7285-compatiable objects.

=== Providing Customized Implmentations ===

Currently it is very simple to provide a customized network map, the
only thing you have to do is to put the data into the data store. Cost maps are
more complex since there are no classes for the cost values by default, you have
to define it using `augment` in YANG. Here is an example in `alto-hosttracker`.

[source,yang]
include::augment.yang[]
