== ALTO User Guide

=== Overview
The ALTO project provides support for _Application Layer Traffic
Optimization_ services defined in link:https://tools.ietf.org/html/rfc7285[RFC
7285].

In the Beryllium release, ALTO uses the YANG model based on
link:https://tools.ietf.org/html/draft-shi-alto-yang-model-03[this draft].

=== ALTO Architecture

There are three kinds of ALTO packages in OpenDaylight.

. **Core**
The **core** packages include:
.. `alto-northbound`: Implements RESTful API framework
.. `alto-northbound-routes`: Implements the RFC7285-compatible RESTful API
.. `alto-resourcepool`: Provides a management module to maintain contexts
and resources
.. `alto-standard-types`: Defines basic types of ALTO protocol
.. `standard-service-models`: Defines the YANG model of ALTO services in MD-SAL

. **Basic**
The **basic** packages include:
.. Basic implementations of ALTO services:
... `simple-ird`: Implements a simple IRD service
... `endpointcostservice`: Implements the Endpoint Cost Service
.. Utilities:
... `resource-config`: Provides several interfaces to config networkmap and
costmap manually.
.. `alto-hosttracker`: Generates a network map, a corresponding cost map and
the endpoint cost service based on <<_l2switch_user_guide, l2switch>>.

=== Administering or Managing ALTO

To enable ALTO, the features must be installed first.

[source,bash]
karaf > feature:install odl-alto-release

==== Managing Resource with `alto-resourcepool`

After installing `odl-alto-release` feature in karaf, `alto-resourcepool` feature 
will be installed automatically. And you can manage all resources in ALTO via 
RESTCONF APIs provided by `alto-resourcepool`.

With the example bash script below you can get any resource infomation in a
given context.

[source,bash]
#!/bin/bash
RESOURCE_ID=$1
if [ $2 ] ; then
	CONTEXT_ID=$2
else
	CONTEXT_ID="00000000-0000-0000-0000-000000000000"
fi
URL="http://localhost:8181/restconf/operational/alto-resourcepool:context/"$CONTEXT_ID"/alto-resourcepool:resource/"$RESOURCE_ID
curl -X GET -u admin:admin $URL | python -m json.tool | sed -n '/default-tag/p' | sed 's/.*:.*\"\(.*\)\".*/\1/g'

==== Using `alto-hosttracker`

As a real instance of ALTO services, `alto-hosttracker` reads data from
`l2switch` and generates a network map with resource id
`hosttracker-network-map` and a cost map with resource id `hostracker-cost-map`.
It can only work with OpenFlow-enabled networks.

After installing the `odl-alto-hosttracker` feature, the corresponding network
map and cost map will be inserted into the data store.

=== Using `simple-ird`

At the default configuration, `simple-ird` feature will be installed automatically.
You can use basic ALTO IRD service via RESTCONF API or ALTO northbound.

The following example shows how to use `simple-ird` to get IRD infomation.

get_context_id.sh

[source,bash]
#!/bin/bash
COMMAND="curl -4 -X GET -u admin:admin http://localhost:8080/restconf/operational/alto-simple-ird:information"
if [ $1 ]; then
    $COMMAND | python -m json.tool
fi
$COMMAND | python -m json.tool | sed -n '/.*context-id.*/p' | sed 's/^.*:.*\"\(.*\)\".*/\1/g'

ird-display.sh

[source,bash]
#!/bin/bash
RESOURCE_ID=$1
URL="http://localhost:8181/restconf/config/alto-simple-ird:ird-instance-configuration/"$RESOURCE_ID"/"
curl -4 -X GET -u admin:admin $URL | python -m json.tool

display-ird.sh

[source,bash]
#!/bin/bash
CONTEXT_ID=$(./get_context_id.sh)
RP_URL="http://localhost:8181/restconf/operational/alto-resourcepool:context/"$CONTEXT_ID
RESOURCEPOOL=$(curl -4 -X GET -u admin:admin $RP_URL)
RESOURCES=$(echo $RESOURCEPOOL | python -m json.tool \
        | sed -n '/.*resource-id.*/p' \
        | sed 's/.*:.*\"\(.*\)\".*/\1/g')
for resource in $RESOURCES; do
    ./ird-display $resource
done

=== Manual Configuration

==== Using RESTCONF API

After installing `odl-alto-release` feature in karaf, it is possible to manage
network-maps and cost-maps using RESTCONF. Take a look at all the operations
provided by `resource-config` at the API service page which can be found at
`http://localhost:8181/apidoc/explorer/index.html`.

==== Using RPC

The `resource-config` package also provides a query RPC to config the resources.
You can CREATE, UPDATE and DELETE network-maps and cost-maps via query RPC

=== Basic Endpoint Cost Service

Endpoint Cost Service is a basic service of ALTO. And this service is provided by
`odl-alto-standard-northbound-route`.
