[[bk-install-guide]]
= OpenDaylight Installation Guide
:docinfo:


[dedication]
Example Dedication
------------------
Optional dedication.

This document is an AsciiDoc book skeleton containing briefly
annotated example elements plus a couple of example index entries and
footnotes.

Books are normally used to generate DocBook markup and the titles of
the preface, appendix, bibliography, glossary and index sections are
significant ('specialsections').


[preface]
Example Preface
---------------
Optional preface.

Preface Sub-section
~~~~~~~~~~~~~~~~~~~
Preface sub-section body.

//////////////////////////
Using OpenDaylight
--------------------------

[partintro]
.Optional part introduction title
--
Optional part introduction goes here.
--

OpenDaylight Add-ons
-------------------------

[partintro]
.Optional part introduction title
--
Optional part introduction goes here.
--
//////////////////////////



//////////////////////////
Please note and leave the blank line between include statements here.

It is a defensive measure to prevent individual projects' .adoc files
from eating the next section if they forget to leave a blank line at
the end of their file.
//////////////////////////
include::general_installation.adoc[]

include::addons/aaa.adoc[]

include::addons/bgpcep.adoc[]

include::addons/defense4all.adoc[]

include::addons/groupbasedpolicy.adoc[]

include::addons/l2switch.adoc[]

include::addons/lispflow.adoc[]

include::addons/ovsdb.adoc[]

include::addons/pcmm.adoc[]

include::addons/plugin2oc.adoc[]

include::addons/sfc.adoc[]

include::addons/snbi.adoc[]

include::addons/snmp4sdn.adoc[]

include::addons/ttp.adoc[]

include::addons/vtn.adoc[]

include::addons/yangtools.adoc[]

:numbered!:

[appendix]
Example Appendix
----------------
One or more optional appendixes go here at section level 1.

Appendix Sub-section
~~~~~~~~~~~~~~~~~~~
Sub-section body.


[glossary]
Example Glossary
----------------
Glossaries are optional. Glossaries entries are an example of a style
of AsciiDoc labeled lists.

[glossary]
A glossary term::
  The corresponding (indented) definition.

A second glossary term::
  The corresponding (indented) definition.


[colophon]
Example Colophon
----------------
Text at the end of a book describing facts about its production.


[index]
Example Index
-------------
////////////////////////////////////////////////////////////////
The index is normally left completely empty, it's contents being
generated automatically by the DocBook toolchain.
////////////////////////////////////////////////////////////////

