== OpenDaylight Controller Overview
The OpenDaylight project is a collaborative open source project that aims to accelerate adoption of Software-Defined Networking (SDN) 
and Network Functions Virtualization (NFV) with a transparent approach that fosters new innovation and reduces risk. 

OpenDaylight mainly consists of software designed to be run on top of a Java Virtual Machine (JVM) and can be run on any operating system
and hardware as long as it supports Java. OpenDaylight is an implementation of the
Software Defined Network (SDN) concept and makes use of the following third-party tools:

* *Maven*: OpenDaylight uses Maven for easier build automation. Maven uses pom.xml
(Project Object Model) to script the dependencies between bundles and also to describe
which bundles to load and start.

* *OSGi*: OSGi framework is the back-end of OpenDaylight as it allows dynamically
loading bundles and packages JAR files, and binding bundles together for exchanging
information.

* *JAVA interfaces*: Java interfaces are usually generated by compiling the YANG project. Java interfaces are used for event listening, specifications, and forming
patterns. This is the main way in which specific bundles implement call-back functions for events and also to indicate awareness of specific state.

* *REST APIs*: Most of the REST APIs in OpenDaylight are defined using YANG tools and are RESTCONF APIs.

* *Karaf*: TBD

Add content related to Lithium (TBD)

For a more detailed overview of the OpenDaylight controller, see the _OpenDaylight
Developer Guide_

