== Getting and Installing OpenDaylight Helium

This section should be reworked with content added.

=== Downloading the Karaf Distribution

// ==== Getting the Default Distribution

The default distribution can be found on the OpenDaylight Software Download page here: http://www.opendaylight.org/software/downloads

This distribution comes with no features enabled by default, but all
features are able to be installed and run.

CAUTION: Not all features can be run at the same time without negative
         consequences.

// ==== Using the Custom Distribution Download Tool

// Fill in info once this exists.

=== Running the Karaf distribution

. Unzip the zip file
. cd into the directory
. run ./bin/karaf

For example:

----
$ ls distribution-karaf-0.2.0-Helium.zip 
distribution-karaf-0.2.0-Helium.zip
$ unzip distribution-karaf-0.2.0-Helium.zip 
Archive:  distribution-karaf-0.2.0-Helium.zip
   creating: distribution-karaf-0.2.0-Helium/
   creating: distribution-karaf-0.2.0-Helium/configuration/
   creating: distribution-karaf-0.2.0-Helium/data/
   creating: distribution-karaf-0.2.0-Helium/data/tmp/
   creating: distribution-karaf-0.2.0-Helium/deploy/
   creating: distribution-karaf-0.2.0-Helium/etc/
   creating: distribution-karaf-0.2.0-Helium/externalapps/
...
  inflating: distribution-karaf-0.2.0-Helium/bin/start.bat  
  inflating: distribution-karaf-0.2.0-Helium/bin/status.bat  
  inflating: distribution-karaf-0.2.0-Helium/bin/stop.bat
$ cd distribution-karaf-0.2.0-Helium
$ ./bin/karaf 
                                                                                           
    ________                       ________                .__  .__       .__     __       
    \_____  \ ______   ____   ____ \______ \ _____  ___.__.|  | |__| ____ |  |___/  |_     
     /   |   \\____ \_/ __ \ /    \ |    |  \\__  \<   |  ||  | |  |/ ___\|  |  \   __\    
    /    |    \  |_> >  ___/|   |  \|    `   \/ __ \\___  ||  |_|  / /_/  >   Y  \  |      
    \_______  /   __/ \___  >___|  /_______  (____  / ____||____/__\___  /|___|  /__|      
            \/|__|        \/     \/        \/     \/\/            /_____/      \/          
                                                                                           

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown OpenDaylight.

opendaylight-user@root>
----

=== Installing Features

The following table describes a list of components in OpenDaylight Helium and the relevant Karaf feature to install in order to enable that component. To install a feature use the +feature:install+ Karaf command, for example:

-----
feature:install <feature-name>
-----

Multiple features can be installed in the same command:

-----
feature:install <feature1-name> <feature2-name> ... <featureN-name>
-----

.Karaf features
[options="header",cols="18%,50%,18%,14%"]
|=======================
| Component Name                   | Component Description | Karaf feature name                    | Compatibility
| BGPCEP                           | description           | odl-bgpcep-all                        | all
| LISP Flow Mapping                | Enable LISP control plane services including the mapping system services REST API and LISP protocol SB plugin | odl-lispflowmapping-all               | all
| MD-SAL Clustering                | description           | odl-mdsal-clustering                  | special
| Netconf over ssh                 | description           | odl-netconf-connector-ssh             | all
| OpenFlow Flow Programming        | description           | odl-openflowplugin-flow-services-ui   | all
| OVS Management                   | Enable OVS management using OVSDB plugin and its associated OVSDB northbound APIs | odl-ovsdb-all                         | all
| Packetcable PCMM                 | Enable flow-based dynamic QoS management of CMTS using in the DOCSIS infrastructure | odl-packetcable-all                   | all
| SDN Interface                    | description           | odl-sdninterfaceapp-all               | all
| RESTCONF API Support             | description           | odl-restconf                          | all
| Service Flow Chaining (SFC)      | description           | odl-sfc-all                           | all
| SFC over LISP                    | description           | odl-sfclisp                           | all
| SFC over L2                      | description           | odl-sfcofl2                           | all
| SFC over VXLAN                   | description           | odl-ovsdb-ovssfc                      | self+all
| Secure Networking Bootstrap      | Define a SNBI domain and associated white lists of devices to be accomodated to the domain | odl-snbi-all                          | all
| OpenFlow Table Type Patterns     | description           | odl-ttp-all                           | all
| SNMP4SDN                         | description           | odl-snmp4sdn-all                      | all
| Group Based Policy               | Enable Endpoint Registry and Policy Repository REST APIs and associated functionality for the Group Based Policy Proof of Concept demonstration | odl-groupbasedpolicy-ofoverlay        | self+all
| L2 Switch                        | description           | odl-l2switch-switch-ui                | self+all
| Plugin to OpenContrail           | description           | odl-plugin2oc                         | self+all
| OVSDB OpenStack Neutron          | OpenStack Network Virtualization using OpenDaylight's OVSDB support | odl-ovsdb-openstack                   | self+all
| VTN Manager                      | description           | odl-vtn-manager-all                   | self+all
|=======================

In the table a compatibility value of "all" means that it can be run with any other features. A value of "self+all" indicates that the feature can be installed with anything with a value of "all", but not any other features with a value of "self+all".

==== Installing MD-SAL Clustering

The MD-SAL clustering feature is noted to have "special" compatibility. It *must* be installed first, before any other features. That is, the first command run at the Karaf CLI should be:

----
feature:install odl-mdsal-clustering
----

==== Listing Available and Installed Karaf Features

Note, that this is not an exhaustive list of Karaf features, however you can find a full list by running the following command at the Karaf CLI:

----
feature:list
----

To just list the installed Karaf features, run the command:

----
feature:list -i
----

=== Project-Specific Installation Instructions

The Defense4All and Yang Tools projects provide project-specific installation instructions here. Other projects can either be installed by simply installing the appropriate Karaf feature(s) or, in some cases, further instructions can be found in the User Guide or Developer Guide.
